export type ConnectorPreset={id:string;name:string;category:string;description:string;kind:'mcp'|'api'|'storage';url?:string;auth:'token'|'optional'|'none'|'oauth'|'ssh';setup:string;docs:string;color:string;mark:string};
export const connectorCatalog:ConnectorPreset[]=[
 {id:'adma',name:'ADMA',category:'Data',description:'Browse agricultural files and folders, read text datasets and upload text files to ADMA.',kind:'api',auth:'token',setup:'Use your ADMA API token from adma.aisoup.net. ADMA uses Token authentication. An administrator can create a token for your account with the create_api_token management command. Never enter your account password here.',docs:'https://adma.aisoup.net/documentation/#api-endpoints',color:'#d00000',mark:'AD'},
 {id:'github',name:'GitHub',category:'Development',description:'Search repositories, inspect code, manage issues and pull requests.',kind:'mcp',url:'https://api.githubcopilot.com/mcp/',auth:'token',setup:'Use a GitHub personal access token with access to the repositories you want to use.',docs:'https://github.com/github/github-mcp-server',color:'#24292f',mark:'GH'},
 {id:'linear',name:'Linear',category:'Projects',description:'Find and manage issues, projects and team workflows.',kind:'mcp',url:'https://mcp.linear.app/mcp',auth:'token',setup:'Create a Linear API key in Settings. Its permissions determine what the connector can access.',docs:'https://linear.app/docs/mcp',color:'#5e6ad2',mark:'L'},
 {id:'notion',name:'Notion',category:'Documents',description:'Search shared pages, read their contents and append notes.',kind:'api',auth:'token',setup:'Create a Notion internal integration, copy its token, and grant it access to the pages you want to use.',docs:'https://developers.notion.com/docs/create-a-notion-integration',color:'#191919',mark:'N'},
 {id:'slack',name:'Slack',category:'Communication',description:'Browse conversations, read messages and send approved replies.',kind:'api',auth:'token',setup:'Use a Slack bot or user token with conversations read/history scopes and chat:write for sending. Add the app to the channels it should access.',docs:'https://docs.slack.dev/authentication/tokens/',color:'#611f69',mark:'S'},
 {id:'airtable',name:'Airtable',category:'Data',description:'Browse bases and tables, read records and create records.',kind:'api',auth:'token',setup:'Create an Airtable personal access token with schema.bases:read and data.records:read. Add data.records:write to create records and select the allowed bases.',docs:'https://support.airtable.com/docs/creating-personal-access-tokens',color:'#d49b00',mark:'A'},
 {id:'todoist',name:'Todoist',category:'Projects',description:'List projects and tasks, create tasks and mark them complete.',kind:'api',auth:'token',setup:'Copy your Todoist API token from Settings → Integrations → Developer.',docs:'https://developer.todoist.com/',color:'#dc4c3e',mark:'T'},
 {id:'brave',name:'Brave Search',category:'Research',description:'Search web pages, images, videos and news across the web using your Brave Search API subscription.',kind:'api',auth:'token',setup:'Use a Brave Search API key. Search requests use your provider quota and may incur provider charges.',docs:'https://api-dashboard.search.brave.com/documentation',color:'#f05a28',mark:'B'},
 {id:'youtube',name:'YouTube',category:'Research',description:'Search public YouTube videos, channels and playlists using the YouTube Data API.',kind:'api',auth:'token',setup:'Create a separate Google API key restricted to YouTube Data API v3. Public search does not require Google OAuth. Keep the Google Picker key restricted to Picker only.',docs:'https://developers.google.com/youtube/v3/getting-started',color:'#ff0033',mark:'YT'},
 {id:'unl-hcc',name:'UNL HCC',category:'Compute',description:'Browse Swan storage and submit, monitor, inspect and cancel Slurm jobs at the UNL Holland Computing Center.',kind:'api',auth:'ssh',setup:'Enter your HCC username. After adding the connector, open My connections and start a temporary compute session with your HCC password and Duo. AgenticWiKi does not save the password.',docs:'https://hcc.unl.edu/docs/connecting/',color:'#d00000',mark:'HCC'},
 {id:'deepwiki',name:'DeepWiki',category:'Development',description:'Explore documentation and ask questions about public code repositories.',kind:'mcp',url:'https://mcp.deepwiki.com/mcp',auth:'none',setup:'No API key is required. This connector accesses public repository documentation.',docs:'https://docs.devin.ai/work-with-devin/deepwiki-mcp',color:'#2870c8',mark:'D'},
 {id:'huggingface',name:'Hugging Face',category:'Research',description:'Find models, datasets, papers and tools from Hugging Face.',kind:'mcp',url:'https://huggingface.co/mcp',auth:'optional',setup:'You can connect without a token for public tools. Supply a Hugging Face access token for account-specific capabilities.',docs:'https://huggingface.co/docs/hub/agents-mcp',color:'#c0910b',mark:'HF'},
 {id:'google',name:'Google Drive',category:'Documents',description:'Read all Google Drive files and edit selected or app-created files with confirmation.',kind:'storage',auth:'oauth',setup:'Sign in to Google and authorize the requested file access.',docs:'https://drive.google.com',color:'#27874b',mark:'G'},
 {id:'dropbox',name:'Dropbox',category:'Documents',description:'Browse, read and organize files in Dropbox.',kind:'storage',auth:'oauth',setup:'Requires the Dropbox OAuth application to be configured on this server.',docs:'https://www.dropbox.com/developers/apps',color:'#0061ff',mark:'DB'},
 {id:'onedrive',name:'OneDrive',category:'Documents',description:'Browse, read and organize files in Microsoft OneDrive.',kind:'storage',auth:'oauth',setup:'Requires the Microsoft OAuth application to be configured on this server.',docs:'https://learn.microsoft.com/en-us/graph/auth-register-app-v2',color:'#0078d4',mark:'OD'},
];
export const presetById=(id:string)=>connectorCatalog.find(p=>p.id===id);
