'use client';
import {useEffect,useRef,useState} from 'react';
import {useDismissFloating} from '@/app/use-dismiss-floating';
import {Plug,X,RefreshCw} from 'lucide-react';
import {useUi} from '@/app/i18n/client';
import {connectorCatalog,type ConnectorPreset} from './catalog';
import type {Connection} from './contracts';
type Action={id:string;connectorId:string;tool:string;state:string;args?:unknown;result?:unknown};
export function ConnectorPanel(){
 const [view,setView]=useState<'catalog'|'connected'|'activity'>('catalog'),[query,setQuery]=useState(''),[category,setCategory]=useState('All'),[chosen,setChosen]=useState<ConnectorPreset|null>(null),[presetToken,setPresetToken]=useState(''),[sshUsername,setSshUsername]=useState(''),[sshPassword,setSshPassword]=useState(''),[duoResponse,setDuoResponse]=useState('phone'),[hccError,setHccError]=useState(''),[hccMessage,setHccMessage]=useState(''),[sessionStatus,setSessionStatus]=useState<Record<string,{connected:boolean;pending?:boolean;expiresAt?:number|null;message?:string;error?:string}>>({});
 const {t,locale:usePickerLocale}=useUi(),dialog=useRef<HTMLDialogElement>(null),[open,setOpen]=useState(false),[items,setItems]=useState<Connection[]>([]),[actions,setActions]=useState<Action[]>([]),[signed,setSigned]=useState(false),[configured,setConfigured]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[name,setName]=useState(''),[url,setUrl]=useState(''),[token,setToken]=useState('');
 useEffect(()=>{const status=new URLSearchParams(location.search).get('arcgis');if(status){setOpen(true);setView(status==='connected'?'connected':'catalog');if(status!=='connected')setError(status==='cancelled'?'ArcGIS authorization was cancelled.':'ArcGIS authorization failed. Please reconnect.');}},[]);
 useDismissFloating(open,dialog,()=>setOpen(false));
 async function load(){const r=await fetch('/api/connectors'),d=await r.json() as any;if(!r.ok)throw Error(d.error);setItems(d.connections);setActions(d.actions);setSigned(d.signedIn);setConfigured(d.configured);const sessions=(d.connections as Connection[]).filter(c=>(c.provider==='unl-hcc'||c.provider==='unl-vpn')&&c.connected);const next:Record<string,any>={};await Promise.all(sessions.map(async c=>{try{const s=await fetch('/api/connectors/'+c.id+'/hcc-session');if(s.ok)next[c.id]=await s.json();}catch{}}));setSessionStatus(next);}
 // A backgrounded mobile tab drops in-flight requests; the server-side login keeps
 // running, so polling resumes (and retries) until it reports a result.
 async function pollHcc(id:string){const deadline=Date.now()+150000;let d:{error?:string;message?:string;pending?:boolean;connected?:boolean;prompts?:string[]}={pending:true};while(d.pending&&Date.now()<deadline){await new Promise(resolve=>setTimeout(resolve,2000));try{const poll=await fetch('/api/connectors/'+id+'/hcc-session');d=await poll.json();if(!poll.ok)throw Error(d.error||'Could not check the HCC login.');}catch(e){if(e instanceof TypeError){d={pending:true};continue;}throw e;}if(d.pending)setHccMessage((d.message||'Waiting for Duo…')+(d.prompts?.length?' Swan: '+d.prompts[d.prompts.length-1]:''));}return d;}
 useEffect(()=>{void load().catch(()=>{});const id=setInterval(()=>void load().catch(()=>{}),15000);return()=>clearInterval(id);},[]);
 useEffect(()=>{if(open){dialog.current?.showModal();void load().catch(e=>setError(e.message));}else dialog.current?.close();},[open]);
 async function act(path:string,method:string,body?:unknown){setBusy(true);setError('');try{const r=await fetch(path,{method,headers:{'Content-Type':'application/json'},body:body?JSON.stringify(body):undefined}),d=await r.json() as any;if(!r.ok)throw Error(d.error);await load();return true;}catch(e){setError(e instanceof Error?e.message:'Could not update connector.');return false;}finally{setBusy(false);}}
 async function connectStorage(id:string){setBusy(true);setError('');try{const r=await fetch(id==='arcgis'?'/api/connectors/arcgis/start':'/api/storage/'+id+'/start',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({returnTo:location.pathname+location.search})}),d=await r.json() as {url?:string;error?:string};if(!r.ok||!d.url)throw Error(d.error||'Could not connect.');location.assign(d.url);}catch(e){setError(e instanceof Error?e.message:'Could not connect.');setBusy(false);}}
 async function connectHcc(id:string){setBusy(true);setError('');setHccError('');setHccMessage('');try{let d:{error?:string;message?:string;pending?:boolean;connected?:boolean;prompts?:string[]};try{const r=await fetch('/api/connectors/'+id+'/hcc-session',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({password:sshPassword,duoResponse:items.find(c=>c.id===id)?.provider==='unl-vpn'||id===''?'push':duoResponse})});d=await r.json();if(!r.ok)throw Error(d.error||'HCC authentication failed. Check your password and Duo response.');}catch(e){if(!(e instanceof TypeError))throw e;d={pending:true,message:'Reconnected to the page; the HCC login is still running…'};}
  setSshPassword('');if(d.pending){setHccMessage(d.message||'Waiting for Duo…');d=await pollHcc(id);}
  if(d.error)throw Error(d.error);if(d.pending)throw Error('The HCC login is still waiting for Duo. Answer the call or approve the request, then reopen this panel.');
  setHccMessage(d.message||'HCC compute session connected.');await load();return true;}catch(e){setHccError(e instanceof Error?e.message:'HCC authentication failed. Check your password and Duo response.');return false;}finally{setBusy(false);}}
 // One step from Discover: save the username, enable the connector and open the Duo session.
 async function setupHcc(preset:string){setBusy(true);setError('');setHccError('');setHccMessage('');let id='';try{// Replace earlier (possibly half-finished) connections of this kind.
 for(const old of items.filter(c=>c.provider===preset))await fetch('/api/connectors/'+old.id,{method:'DELETE'});const r=await fetch('/api/connectors',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({preset,username:sshUsername})}),d=await r.json() as {error?:string;id?:string;connections?:Connection[]};if(!r.ok)throw Error(d.error||'Could not add the connector.');id=d.id||d.connections?.find(c=>c.provider===preset)?.id||'';if(!id)throw Error('Could not add the connector.');await fetch('/api/connectors/'+id,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({enabled:true})});await load();}catch(e){setHccError(e instanceof Error?e.message:'Could not add the connector.');setBusy(false);return;}
  setBusy(false);if(await connectHcc(id)){setChosen(null);setSshUsername('');setView('connected');}}
 const update=(c:Connection,body:unknown)=>void act('/api/connectors/'+c.id,'PATCH',body);
 const presetConnection=(p:ConnectorPreset)=>items.find(c=>c.kind==='storage'?c.id===p.id:c.kind==='api'?c.provider===p.id:c.url===p.url);
 const catalog=connectorCatalog.filter(p=>(category==='All'||p.category===category)&&[p.name,t(p.description),t(p.category)].some(s=>s.toLowerCase().includes(query.toLowerCase())));
 // The setup form opens above the catalog; bring it into view (and focus its first field) so a
 // Connect click far down the list visibly does something.
 const setupRef=useRef<HTMLElement>(null);
 useEffect(()=>{if(!chosen)return;const frame=requestAnimationFrame(()=>{const el=setupRef.current;if(!el)return;el.scrollIntoView({block:'start'});el.querySelector<HTMLElement>('input,select,textarea')?.focus({preventScroll:true});});return()=>cancelAnimationFrame(frame);},[chosen?.id]);
 function choose(p:ConnectorPreset){if(p.auth==='oauth'){void connectStorage(p.id);return;}setChosen(p);setPresetToken('');setSshUsername('');setError('');}
 const pending=actions.filter(a=>a.state==='pending').length;
 return <><button className="connector-open" onClick={()=>setOpen(true)} title={t('Connectors')}><Plug size={18}/><span>{t('Connectors')}</span>{pending>0&&<b>{pending}</b>}</button><dialog ref={dialog} className="connector-dialog" onCancel={()=>setOpen(false)} onClose={()=>{setOpen(false);setToken('');setPresetToken('');setChosen(null);}} aria-labelledby="connector-heading"><header><div><h2 id="connector-heading">{t('Connectors')}</h2><p>{t('Enabled tools are available to the page generator and in-page agent.')}</p></div><button onClick={()=>setOpen(false)} aria-label={t('Close')}><X size={20}/></button></header>
 {!signed&&<p><a href="/auth/google">{t('Sign in to manage your connectors.')}</a></p>}
 {error&&<p role="alert" className="connector-error">{t(error)}</p>}
 <p className="connector-note">{t('Connections belong to your account. Other visitors use their own connections. Turning a connector off blocks new calls; already running calls may finish.')}</p>
 <nav className="connector-tabs" aria-label={t('Connector views')}>{(['catalog','connected','activity'] as const).map(v=><button key={v} aria-pressed={view===v} onClick={()=>setView(v)}>{t(v==='catalog'?'Discover':v==='connected'?'My connections':'Activity')}{v==='activity'&&pending>0?' ('+pending+')':''}</button>)}</nav>
 {view==='catalog'&&<><div className="connector-search"><input aria-label={t('Search connectors')} placeholder={t('Search connectors')} value={query} onChange={e=>setQuery(e.target.value)}/><select aria-label={t('Category')} value={category} onChange={e=>setCategory(e.target.value)}>{['All',...new Set(connectorCatalog.map(p=>p.category))].map(c=><option key={c} value={c}>{t(c)}</option>)}</select></div>
 {chosen&&<section ref={setupRef} className="connector-setup"><header><h3>{t('Connect')} {chosen.name}</h3><button onClick={()=>{setChosen(null);setPresetToken('');setSshUsername('');}} aria-label={t('Cancel')}>×</button></header><p>{t(chosen.setup)}</p><a href={chosen.docs} target="_blank" rel="noopener noreferrer">{t('Setup guide')}</a><form onSubmit={e=>{e.preventDefault();if(chosen.auth==='ssh'){void setupHcc(chosen.id);return;}void act('/api/connectors','POST',{preset:chosen.id,token:presetToken,...(chosen.auth==='password'?{username:sshUsername}:{})}).then(ok=>{if(ok){setChosen(null);setPresetToken('');setView('connected');}});}}>{chosen.auth==='password'?<><label>{t('UNL AD username')}<input autoComplete="username" required maxLength={64} placeholder="ypan12" value={sshUsername} onChange={e=>setSshUsername(e.target.value)}/></label><label>{t('UNL AD password')}<input type="password" autoComplete="current-password" required value={presetToken} onChange={e=>setPresetToken(e.target.value)}/></label></>:chosen.auth==='ssh'?<><label>{t(chosen.id==='unl-vpn'?'TrueYou username (NUID@nebraska.edu)':'HCC username')}<input autoComplete="username" required maxLength={80} value={sshUsername} onChange={e=>setSshUsername(e.target.value)}/></label><label>{t(chosen.id==='unl-vpn'?'TrueYou password':'HCC password')}<input type="password" autoComplete="current-password" required value={sshPassword} onChange={e=>setSshPassword(e.target.value)}/></label>{chosen.id==='unl-vpn'?<p className="connector-hcc-result">{t('A Duo Push will be sent to your phone. Approve it in Duo Mobile.')}</p>:<label>{t('Duo verification')}<select value={/^(phone|push)$/.test(duoResponse)?duoResponse:'passcode'} onChange={e=>setDuoResponse(e.target.value==='passcode'?'':e.target.value)}><option value="phone">{t('Phone call')}</option><option value="push">{t('Duo Push')}</option>{chosen.id!=='unl-vpn'&&<option value="passcode">{t('Duo Mobile passcode')}</option>}</select></label>}{chosen.id!=='unl-vpn'&&!/^(phone|push)$/.test(duoResponse)&&<label>{t('Passcode')}<input inputMode="numeric" autoComplete="one-time-code" required value={duoResponse} onChange={e=>setDuoResponse(e.target.value)}/></label>}{hccError&&<p className="connector-hcc-result connector-hcc-error" role="alert">{t(hccError)}</p>}{hccMessage&&<p className="connector-hcc-result connector-hcc-success" role="status">{t(hccMessage)}</p>}</>:chosen.auth!=='none'&&<label>{t(chosen.auth==='optional'?'API token (optional)':'API token')}<input type="password" autoComplete="off" required={chosen.auth==='token'} value={presetToken} onChange={e=>setPresetToken(e.target.value)}/></label>}<button disabled={busy||!signed||!configured}>{t(busy?(chosen.auth==='ssh'?'Waiting for Duo…':'Connecting…'):chosen.auth==='ssh'?'Connect and verify':'Add connector')}</button></form></section>}
 <div className="connector-catalog-grid">{catalog.map(p=>{const c=presetConnection(p),connected=c?.connected;return <section className="connector-directory-card" key={p.id}><div className="connector-logo" style={{background:p.color}} aria-hidden="true">{p.mark}</div><div><h3>{p.name}</h3><small>{t(p.category)}</small></div><p>{t(p.description)}</p><footer><span>{t(connected?'Connected':p.auth==='none'?'No API key':p.auth==='oauth'?'Account authorization':p.id==='unl-hcc'||p.id==='unl-vpn'?'Duo session':p.auth==='password'?'UNL AD account':p.auth==='ssh'?'SSH key':p.auth==='optional'?'API token (optional)':'API token')}</span><button disabled={busy||!connected&&(!signed||!configured||p.auth==='oauth'&&!c?.configured)} onClick={()=>connected?setView('connected'):choose(p)}>{t(connected?'Manage':'Connect')}</button></footer>{p.auth==='oauth'&&!c?.configured&&<small>{t('Server setup required')}</small>}</section>;})}</div>{!catalog.length&&<p>{t('No matching connectors.')}</p>}</>}
 <div hidden={view!=='connected'}><h3>{t('My connections')}</h3> <div className="connector-grid">{items.filter(c=>c.connected).map(c=><section key={c.id} className="connector-card"><div className="connector-card-heading"><strong>{c.name}</strong><label><input type="checkbox" role="switch" aria-label={t('Enable connector')+' '+c.name} checked={c.enabled} disabled={busy||!signed||!c.connected} onChange={e=>update(c,{enabled:e.target.checked})}/>{t(c.enabled?'On':'Off')}</label></div><p>{t('Turning on enables all tools. You can uncheck individual tools afterward.')}</p><p>{t(c.connected?'Connected':c.configured?'Not connected':'Server setup required')}</p>{c.kind==='mcp'&&c.url&&<small>{c.url}</small>}
 {(c.provider==='unl-hcc'||c.provider==='unl-vpn')&&<form className="connector-hcc-session" onSubmit={e=>{e.preventDefault();void connectHcc(c.id);}}><p className={'connector-hcc-result '+(sessionStatus[c.id]?.connected?'connector-hcc-success':'connector-hcc-error')} role="status">{t(sessionStatus[c.id]?.connected?(c.provider==='unl-vpn'?'VPN connected':'Compute session connected'):sessionStatus[c.id]?.pending?'Login in progress…':(c.provider==='unl-vpn'?'VPN not connected':'No compute session'))}{sessionStatus[c.id]?.connected&&sessionStatus[c.id]?.expiresAt?' · '+t('idle until')+' '+new Date(sessionStatus[c.id]!.expiresAt!).toLocaleTimeString():''}</p><label>{t(c.provider==='unl-vpn'?'TrueYou password':'HCC password')}<input type="password" autoComplete="current-password" required value={sshPassword} onChange={e=>setSshPassword(e.target.value)} aria-invalid={!!hccError}/></label>{c.provider==='unl-vpn'?<p className="connector-hcc-result">{t('A Duo Push will be sent to your phone. Approve it in Duo Mobile.')}</p>:<label>{t('Duo verification')}<select value={/^(phone|push)$/.test(duoResponse)?duoResponse:'passcode'} onChange={e=>setDuoResponse(e.target.value==='passcode'?'':e.target.value)} aria-describedby={'hcc-duo-help-'+c.id}><option value="phone">{t('Phone call')}</option><option value="push">{t('Duo Push')}</option>{<option value="passcode">{t('Duo Mobile passcode')}</option>}</select></label>}{!/^(phone|push)$/.test(duoResponse)&&<label>{t('Passcode')}<input inputMode="numeric" autoComplete="one-time-code" required value={duoResponse} onChange={e=>setDuoResponse(e.target.value)} aria-invalid={!!hccError}/></label>}{c.provider!=='unl-vpn'&&<small id={'hcc-duo-help-'+c.id}>{t('Phone call rings the number registered with Duo; answer it and press the key it asks for. Duo Push needs Duo Mobile on that phone.')}</small>}<button className="connector-hcc-connect" disabled={busy||!sshPassword}>{t(busy?'Waiting for Duo…':c.provider==='unl-vpn'?'Connect VPN':'Connect compute session')}</button>{hccError&&<p className="connector-hcc-result connector-hcc-error" role="alert">{t(hccError)}</p>}{hccMessage&&<p className="connector-hcc-result connector-hcc-success" role="status">{t(hccMessage)}</p>}<small>{t(c.provider==='unl-vpn'?'Your password is used only to sign in and is not saved. Approve the Duo prompt when it arrives. The tunnel is private to your account and stays up until the university ends the VPN session.':'Your password is used only to open this session and is not saved. Approve the Duo prompt when it arrives. The session closes after two hours without HCC activity; Slurm jobs continue running.')}</small></form>}
 <div className="connector-card-actions">{c.kind==='storage'&&!c.connected&&<button disabled={busy||!c.configured||!signed} onClick={()=>void connectStorage(c.id)}>{t('Connect account')}</button>}{c.kind==='mcp'&&<button disabled={busy} onClick={()=>update(c,{refresh:true})}><RefreshCw size={13}/>{t('Refresh tools')}</button>}{c.connected&&<button disabled={busy} onClick={()=>void act('/api/connectors/'+c.id,'DELETE')}>{t('Disconnect')}</button>}</div>
 {c.connected&&c.id==='google'&&<p><a href={"/drive-picker?language="+encodeURIComponent(usePickerLocale)+"&returnTo="+encodeURIComponent(typeof location!=='undefined'?location.pathname+location.search:'/')}>{t('Choose Google Drive files to edit')}</a></p>}{c.connected&&<details><summary>{t('Tools')} · {c.allowed.length}/{c.tools.length}</summary><p className="connector-note">{t('Checked tools can be called automatically by agents, including tools that change external data. Uncheck a tool to disable it.')}</p><div className="connector-tool-list">{c.tools.map(tool=><div className="connector-tool" key={tool.name}><label><input type="checkbox" checked={c.allowed.includes(tool.name)} disabled={busy} onChange={e=>update(c,{allowed:e.target.checked?[...c.allowed,tool.name]:c.allowed.filter(n=>n!==tool.name)})}/><strong>{tool.name}</strong></label><p>{tool.description}</p></div>)}</div></details>}</section>)}</div>{!items.some(c=>c.connected)&&<p>{t('No connections yet. Choose a service in Discover.')}</p>}</div>
 <details className="connector-add" hidden={view!=='catalog'}><summary>{t('Add MCP connector')}</summary><p>{t('Connect a Streamable HTTP MCP server using its HTTPS endpoint and optional bearer token. After connecting, choose tools and turn it on.')}</p><form onSubmit={e=>{e.preventDefault();void act('/api/connectors','POST',{name,url,token}).then(ok=>{if(ok){setName('');setUrl('');setToken('');}});}}><label>{t('Name')}<input required maxLength={80} value={name} onChange={e=>setName(e.target.value)}/></label><label>{t('MCP endpoint')}<input required type="url" placeholder="https://example.com/mcp" value={url} onChange={e=>setUrl(e.target.value)}/></label><label>{t('Bearer token (optional)')}<input type="password" autoComplete="off" value={token} onChange={e=>setToken(e.target.value)}/></label><button disabled={busy||!signed||!configured}>{t(busy?'Connecting…':'Connect and discover tools')}</button></form>{!configured&&<p>{t('Connector encryption is not configured on the server.')}</p>}</details>
 <section className="connector-activity" hidden={view!=='activity'}><h3>{t('Tool activity and approvals')}</h3><p>{t('Review the destination and arguments. Results may be used in the page or conversation; on a public page they may be visible to other readers.')}</p><button disabled={busy} onClick={()=>void load().catch(e=>setError(e.message))}>{t('Refresh')}</button>{!actions.length&&<p>{t('No tool calls awaiting review.')}</p>}{actions.map(a=><article key={a.id}><strong>{items.find(c=>c.id===a.connectorId)?.name||a.connectorId} · {a.tool}</strong><span>{t(a.state)}</span><details><summary>{t('Arguments and result')}</summary><pre>{JSON.stringify({arguments:a.args,result:a.result},null,2)}</pre></details>{a.state==='pending'&&<div><button disabled={busy} onClick={()=>void act('/api/connectors/actions/'+a.id,'POST',{approve:true})}>{t('Approve and run')}</button><button disabled={busy} onClick={()=>void act('/api/connectors/actions/'+a.id,'POST',{approve:false})}>{t('Cancel')}</button></div>}{a.state==='uncertain'&&<p>{t('The result is uncertain. Check the external service before requesting another call.')}</p>}</article>)}</section>
 </dialog></>;
}
