'use client';
import {useEffect,useRef,useState} from 'react';
import {Plug,X,RefreshCw} from 'lucide-react';
import {useUi} from '@/app/i18n/client';
import type {Connection} from './contracts';
type Action={id:string;connectorId:string;tool:string;state:string;args?:unknown;result?:unknown};
export function ConnectorPanel(){
 const {t}=useUi(),dialog=useRef<HTMLDialogElement>(null),[open,setOpen]=useState(false),[items,setItems]=useState<Connection[]>([]),[actions,setActions]=useState<Action[]>([]),[signed,setSigned]=useState(false),[configured,setConfigured]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[name,setName]=useState(''),[url,setUrl]=useState(''),[token,setToken]=useState('');
 async function load(){const r=await fetch('/api/connectors'),d=await r.json() as any;if(!r.ok)throw Error(d.error);setItems(d.connections);setActions(d.actions);setSigned(d.signedIn);setConfigured(d.configured);}
 useEffect(()=>{void load().catch(()=>{});const id=setInterval(()=>void load().catch(()=>{}),15000);return()=>clearInterval(id);},[]);
 useEffect(()=>{if(open){dialog.current?.showModal();void load().catch(e=>setError(e.message));}else dialog.current?.close();},[open]);
 async function act(path:string,method:string,body?:unknown){setBusy(true);setError('');try{const r=await fetch(path,{method,headers:{'Content-Type':'application/json'},body:body?JSON.stringify(body):undefined}),d=await r.json() as any;if(!r.ok)throw Error(d.error);await load();return true;}catch(e){setError(e instanceof Error?e.message:'Could not update connector.');return false;}finally{setBusy(false);}}
 async function connectStorage(id:string){setBusy(true);setError('');try{const r=await fetch('/api/storage/'+id+'/start',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({returnTo:location.pathname+location.search})}),d=await r.json() as {url?:string;error?:string};if(!r.ok||!d.url)throw Error(d.error||'Could not connect.');location.assign(d.url);}catch(e){setError(e instanceof Error?e.message:'Could not connect.');setBusy(false);}}
 const update=(c:Connection,body:unknown)=>void act('/api/connectors/'+c.id,'PATCH',body);
 const pending=actions.filter(a=>a.state==='pending').length;
 return <><button className="connector-open" onClick={()=>setOpen(true)} title={t('Connectors')}><Plug size={18}/><span>{t('Connectors')}</span>{pending>0&&<b>{pending}</b>}</button><dialog ref={dialog} className="connector-dialog" onCancel={()=>setOpen(false)} onClose={()=>setOpen(false)} aria-labelledby="connector-heading"><header><div><h2 id="connector-heading">{t('Connectors')}</h2><p>{t('Enabled tools are available to the page generator and in-page agent.')}</p></div><button onClick={()=>setOpen(false)} aria-label={t('Close')}><X size={20}/></button></header>
 {!signed&&<p><a href="/auth/google">{t('Sign in to manage your connectors.')}</a></p>}
 {error&&<p role="alert" className="connector-error">{t(error)}</p>}
 <p className="connector-note">{t('Connections belong to your account. Other visitors use their own connections. Turning a connector off blocks new calls; already running calls may finish.')}</p>
 <div className="connector-grid">{items.map(c=><section key={c.id} className="connector-card"><div className="connector-card-heading"><strong>{c.name}</strong><label><input type="checkbox" role="switch" aria-label={t('Enable connector')+' '+c.name} checked={c.enabled} disabled={busy||!signed||!c.connected} onChange={e=>update(c,{enabled:e.target.checked})}/>{t(c.enabled?'On':'Off')}</label></div><p>{t(c.connected?'Connected':c.configured?'Not connected':'Server setup required')}</p>{c.url&&<small>{c.url}</small>}
 <div className="connector-card-actions">{c.kind==='storage'&&!c.connected&&<button disabled={busy||!c.configured||!signed} onClick={()=>void connectStorage(c.id)}>{t('Connect account')}</button>}{c.kind==='mcp'&&<button disabled={busy} onClick={()=>update(c,{refresh:true})}><RefreshCw size={13}/>{t('Refresh tools')}</button>}{c.connected&&<button disabled={busy} onClick={()=>void act('/api/connectors/'+c.id,'DELETE')}>{t('Disconnect')}</button>}</div>
 {c.connected&&<details><summary>{t('Tools')} · {c.allowed.length}/{c.tools.length}</summary><p className="connector-note">{t('Allow automatic calls only for tools you trust. Other calls appear below for review.')}</p><div className="connector-tool-list">{c.tools.map(tool=><div className="connector-tool" key={tool.name}><label><input type="checkbox" checked={c.allowed.includes(tool.name)} disabled={busy} onChange={e=>update(c,{allowed:e.target.checked?[...c.allowed,tool.name]:c.allowed.filter(n=>n!==tool.name)})}/><strong>{tool.name}</strong></label><p>{tool.description}</p>{c.kind==='mcp'&&<label><input type="checkbox" checked={c.automatic.includes(tool.name)} disabled={busy||!c.allowed.includes(tool.name)} onChange={e=>update(c,{automatic:e.target.checked?[...c.automatic,tool.name]:c.automatic.filter(n=>n!==tool.name)})}/>{t('Allow automatic calls')}</label>}</div>)}</div></details>}</section>)}</div>
 <details className="connector-add"><summary>{t('Add MCP connector')}</summary><p>{t('Connect a Streamable HTTP MCP server using its HTTPS endpoint and optional bearer token. After connecting, choose tools and turn it on.')}</p><form onSubmit={e=>{e.preventDefault();void act('/api/connectors','POST',{name,url,token}).then(ok=>{if(ok){setName('');setUrl('');setToken('');}});}}><label>{t('Name')}<input required maxLength={80} value={name} onChange={e=>setName(e.target.value)}/></label><label>{t('MCP endpoint')}<input required type="url" placeholder="https://example.com/mcp" value={url} onChange={e=>setUrl(e.target.value)}/></label><label>{t('Bearer token (optional)')}<input type="password" autoComplete="off" value={token} onChange={e=>setToken(e.target.value)}/></label><button disabled={busy||!signed||!configured}>{t(busy?'Connecting…':'Connect and discover tools')}</button></form>{!configured&&<p>{t('Connector encryption is not configured on the server.')}</p>}</details>
 <section className="connector-activity"><h3>{t('Tool activity and approvals')}</h3><p>{t('Review the destination and arguments. Results may be used in the page or conversation; on a public page they may be visible to other readers.')}</p><button disabled={busy} onClick={()=>void load().catch(e=>setError(e.message))}>{t('Refresh')}</button>{!actions.length&&<p>{t('No tool calls awaiting review.')}</p>}{actions.map(a=><article key={a.id}><strong>{items.find(c=>c.id===a.connectorId)?.name||a.connectorId} · {a.tool}</strong><span>{t(a.state)}</span><details><summary>{t('Arguments and result')}</summary><pre>{JSON.stringify({arguments:a.args,result:a.result},null,2)}</pre></details>{a.state==='pending'&&<div><button disabled={busy} onClick={()=>void act('/api/connectors/actions/'+a.id,'POST',{approve:true})}>{t('Approve and run')}</button><button disabled={busy} onClick={()=>void act('/api/connectors/actions/'+a.id,'POST',{approve:false})}>{t('Cancel')}</button></div>}{a.state==='uncertain'&&<p>{t('The result is uncertain. Check the external service before requesting another call.')}</p>}</article>)}</section>
 </dialog></>;
}
