import test from 'node:test';import assert from 'node:assert/strict';import {DatabaseSync} from 'node:sqlite';import {readFileSync,readdirSync} from 'node:fs';import ts from 'typescript';
const load=async s=>import('data:text/javascript;base64,'+Buffer.from(ts.transpile(s,{module:ts.ModuleKind.ESNext,target:ts.ScriptTarget.ES2022})).toString('base64'));
const strip=p=>readFileSync(p,'utf8').replace(/import [\s\S]*?from ['"][^'"]+['"];?/g,'');
const {partialReply}=await load(readFileSync('app/chat/stream-reply.ts','utf8'));
test('streamed replies decode split escapes without leaking proposal fields',()=>{const reply='Hello "world"\n你好 😀 \\ path';const json=JSON.stringify({apply:true,discard:false,reply,title:'Secret proposal',body:'Do not stream this'});for(let i=0;i<=json.length;i++){const partial=partialReply(json.slice(0,i));assert.ok(reply.startsWith(partial));assert.ok(!partial.includes('Secret proposal'));}assert.equal(partialReply(json),reply);assert.equal(partialReply('{"reply":"\\uD83D'),'');assert.equal(partialReply('{"reply":"\\uD83D\\uDE00"}'),'😀');});
test('legacy discussions become page-visible exactly once and forks obey access',async()=>{
 const db=new DatabaseSync(':memory:');for(const f of readdirSync('drizzle').filter(f=>f.endsWith('.sql')).sort())db.exec(readFileSync('drizzle/'+f,'utf8'));
 const {legacyCommentsSql,legacyMemorySql}=await load(strip('app/chat/shared-history.ts'));
 const {pageForksSql}=await load(readFileSync('db/page-forks.ts','utf8'));
 const addPage=db.prepare("INSERT INTO pages(id,owner_id,question,title,summary,body,category,sources,visibility,created_at,language) VALUES(?,?,'same','Title','','','Reference','[]',?,'2026-01-01','en')");
 addPage.run('p','owner','private');addPage.run('fork','other','public');addPage.run('hidden','other','private');addPage.run('unrelated','owner','public');
 const q=db.prepare("INSERT INTO questions(id,page_id,normalized,question,embedding,created_at) VALUES(?,?,?,'question','[]','now')");for(const id of ['p','fork','hidden'])q.run(id,id,'same');q.run('unrelated','unrelated','different');
 db.exec("INSERT INTO agent_instances VALUES('a','page:p','owner',NULL,'now'),('b','page:p','guest:one',NULL,'now'),('c','page:fork','other',NULL,'now');INSERT INTO page_chat_turns(session_id,message,reply,created_at) VALUES('a','Old suggestion','Old reply','2026-01-01'),('c','Separate fork','reply','2026-01-02');INSERT INTO agent_memory(agent_id,action,result,created_at) VALUES('b','User: Legacy comment','{\"reply\":\"Legacy reply\"}','2026-01-01'),('b','Internal tool result','{\"reply\":\"Not a comment\"}','now')");
 const importFor=(viewer)=>{db.prepare(legacyCommentsSql).run(viewer,'Test name','p',viewer);db.prepare(legacyMemorySql).run(viewer,'Test name','p',viewer);};
 importFor('stranger');assert.equal(db.prepare('SELECT count(*) n FROM wiki_comments').get().n,0);
 importFor('owner');importFor('owner');assert.equal(db.prepare('SELECT count(*) n FROM wiki_comments').get().n,2);
 assert.deepEqual(db.prepare(pageForksSql).all('owner','p','owner','owner'),[]);db.exec("INSERT INTO page_forks VALUES('p','family',NULL,'2026-01-01'),('fork','family','p','2026-01-02'),('hidden','family','p','2026-01-03')");
 assert.deepEqual(db.prepare(pageForksSql).all('owner','p','owner','owner').map(p=>p.id).sort(),['fork','p']);assert.deepEqual(db.prepare(pageForksSql).all('stranger','p','stranger','stranger'),[]);
 db.exec("UPDATE pages SET visibility='public' WHERE id='p'");importFor('stranger');assert.equal(db.prepare('SELECT count(*) n FROM wiki_comments').get().n,2);assert.deepEqual(db.prepare(pageForksSql).all('stranger','p','stranger','stranger').map(p=>p.id).sort(),['fork','p']);
 assert.equal(db.prepare("SELECT count(*) n FROM wiki_comments WHERE page_id='fork'").get().n,0);db.close();
});
test('generation hands off to separate agents and uses registered files/chat or custom fallback',async()=>{
 const calls=[];globalThis.contextTest={askAgent:async(_a,_i,brief)=>({implementation:({'files-v1':'files','chat-v1':'chat','form-v1':'program'})[brief.templateId],templateId:brief.templateId}),spawnAgent:async(role,owner,parent)=>{calls.push(role);return {id:role,ownerId:owner}},recordAction:async()=>{},composeChat:async()=>({title:'Workspace',summary:'Continue here',config:{template:'agent-chat-v1',executor:'page-agent-v1',version:1,labels:{overview:''}},parameters:{},components:[]}),composeChart:async()=>{throw Error('not expected')},composePageProgram:async()=>{throw Error('sandbox must not run')},research:async()=>({title:'Article',body:'Verified',summary:'',sources:[],labels:{}}),parseConversion:async()=>({intent:'other'}),converterDefinition:async()=>{},composeConverter:async()=>[],sandboxStatus:()=>({configured:false,allowed:false})};
 const {generateContext}=await load(strip('app/page-programs/generate-context.ts')+'\nconst {askAgent,spawnAgent,recordAction,composeChat,composeChart,composePageProgram,research,parseConversion,converterDefinition,composeConverter,sandboxStatus}=globalThis.contextTest;');const ctx={ownerId:'owner',userId:'owner',language:'en'},router={id:'routing',ownerId:'owner'},signal=new AbortController().signal;
 const gen=templateId=>generateContext({question:'Task',templateId,fresh:false},ctx,router,undefined,signal);
 assert.equal((await gen('files-v1')).definition.config.template,'file-browser-v1');assert.equal((await gen('chat-v1')).definition.config.template,'agent-chat-v1');assert.equal((await gen('form-v1')).templateId,'chat-v1');assert.equal((await gen('wiki-v1')).answer.body,'Verified');assert.deepEqual(calls,['app-generation','app-generation','app-generation','content-generation']);delete globalThis.contextTest;
});
test('comment endpoint emits reply deltas before completion and only saves completed replies',async()=>{
 let writes=0,release,unlocked=false;const waiting=new Promise(r=>release=r);
 globalThis.commentStreamTest={startJob:async()=> 'job',finishJob:async()=>{},fileContext:async()=>({parts:[],metadata:[]}),database:()=>({prepare:()=>({bind:()=>({run:async()=>({}),all:async()=>({results:[]})})}),batch:async()=>{writes++;return [{meta:{changes:1}},{meta:{changes:1}}]}}),reply:(data,status=200)=>Response.json(data,{status}),lock:async()=> 'lease',unlock:async()=>{unlocked=true;},importLegacyComments:async()=>{},conversationContext:async()=>({turns:[]}),readEditDraft:async()=>null,saveEditDraft:async()=>{},editWiki:async(page,message,context,userId,agent,onReply)=>{onReply('First words');await waiting;onReply('First words complete');return {page,reply:'First words complete',editDraft:null}}};
 const {postWikiComment}=await load(strip('app/chat/wiki-comments.ts')+'\nconst {startJob,finishJob,fileContext,database,reply,lock,unlock,importLegacyComments,conversationContext,readEditDraft,saveEditDraft,editWiki}=globalThis.commentStreamTest;');
 const response=await postWikiComment(new Request('https://example.test/chat',{headers:{accept:'text/event-stream'}}),{id:'page',kind:'static',owned:false,language:'en'},{userId:'guest:test',userName:'Guest',cookie:null,agent:{}},{message:'Question'});
 const reader=response.body.getReader(),decoder=new TextDecoder();let text='';while(!text.includes('First words'))text+=decoder.decode((await reader.read()).value);assert.equal(writes,0);assert.ok(text.includes('"type":"reply"'));release();for(;;){const r=await reader.read();if(r.done)break;text+=decoder.decode(r.value);if(text.includes('"type":"done"'))assert.equal(unlocked,true);}assert.equal(writes,1);assert.ok(text.includes('"type":"done"'));delete globalThis.commentStreamTest;
});
test('router passes only typed declared inputs and keeps the navigation question separate from commands',async()=>{
 const {z}=await import('zod');globalThis.inputTest={z,parametersSchema:z.record(z.union([z.string(),z.number(),z.boolean()])),askAgent:async()=>({inputJson:JSON.stringify({city:'Beijing',year:2025,unknown:'ignored'})})};
 const {routeInputs,filterInputs,programNavigationInput}=await load('const {z,parametersSchema,askAgent}=globalThis.inputTest;\n'+strip('app/page-programs/inputs.ts'));
 const fields=[{name:'city',type:'string',description:'City',required:true},{name:'year',type:'number',description:'Year',required:true}];
 const params=await routeInputs('GDP of Beijing in 2025',{title:'GDP browser',dynamic:{inputFields:fields}},{});assert.deepEqual(params,{city:'Beijing',year:2025,query:'GDP of Beijing in 2025'});assert.throws(()=>filterInputs({year:'2025'},fields));const input=programNavigationInput(params);assert.equal(input.values.year,2025);assert.equal(input.message,undefined);delete globalThis.inputTest;
});
