const runtimeSource=readFileSync('app/agents/loop.ts','utf8')+'\nconst reasoningOptions=()=>({});const compactSession=async()=>({}),sessionContext=async()=>({}),sessionTools=[],sessionInstructions="",runJournal=()=>async()=>{},safeMemory=JSON.stringify;\n';
import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync,readdirSync} from 'node:fs';import {DatabaseSync} from 'node:sqlite';import ts from 'typescript';import {z} from 'zod';
const strip=p=>readFileSync(p,'utf8').replace(/^import .*;$/gm,'');const load=async s=>import('data:text/javascript;base64,'+Buffer.from(ts.transpile(s,{module:ts.ModuleKind.ESNext,target:ts.ScriptTarget.ES2022})).toString('base64'));
test('checked connector tools run automatically while account, disabled-tool and read-only restrictions remain enforced',async()=>{
 const db=new DatabaseSync(':memory:');for(const f of readdirSync('drizzle').filter(f=>f.endsWith('.sql')).sort())db.exec(readFileSync('drizzle/'+f,'utf8'));
 const vault=new Map();let calls=0,visibility='private',owned=true,nativePage=false;
 globalThis.connectorTest={arcgisTools:[],arcgisStatus:async()=>({configured:true,connected:false}),disconnectArcgis:async()=>{},z,database:()=>({prepare:sql=>({bind:(...args)=>({first:async()=>db.prepare(sql).get(...args),all:async()=>({results:db.prepare(sql).all(...args)}),run:async()=>({meta:{changes:db.prepare(sql).run(...args).changes}})})})}),getPage:async()=>({owned,visibility,...(nativePage?{dynamic:{template:'native-app-v1'}}:{})}),canUseConnectorsOn:p=>p.owned||(p.dynamic?.template==='native-app-v1'&&!p.dynamic?.pageCode),vaultPath:async(u,n)=>u+'/'+n,vaultRead:async p=>vault.get(p),vaultWrite:async(p,v)=>vault.set(p,v),vaultDelete:async p=>vault.delete(p),vaultReady:()=>true,signedIn:u=>{if(u.startsWith('guest:'))throw Error('Sign in');},storageStatus:async()=>[{provider:'google',name:'Google Drive',connected:true,configured:true}],storageToken:async()=>'',disconnectStorage:async()=>{},providerOperation:async()=>{calls++;return {ok:true};},storageRequest:{parse:x=>x},connectorUrl:u=>new URL(u),discoverMcp:async()=>[{name:'read',inputSchema:{type:'object'},annotations:{readOnlyHint:true}},{name:'write',inputSchema:{type:'object'}}],callMcp:async()=>{calls++;return {text:'result secret-token'};},lock:async()=> 'lease',unlock:async()=>{}};
 const m=await load('const {'+Object.keys(globalThis.connectorTest).join(',')+'}=globalThis.connectorTest;\n'+strip('app/connectors/contracts.ts').replace("import {z} from 'zod';",'')+'\n'+strip('app/connectors/service.ts'));
 const {id}=await m.createConnection('alice',{name:'Test',url:'https://example.org/mcp',token:'secret-token'});
 assert.equal((await m.connections('alice')).find(c=>c.id===id).enabled,false);assert.equal((await m.connections('bob')).some(c=>c.id===id),false);
 await assert.rejects(m.callConnector('alice',id,'read',{}),/disabled/);await assert.rejects(m.callConnector('bob',id,'read',{}),/disabled/);
 await m.updateConnection('alice',id,{enabled:true});
 assert.deepEqual(await m.callConnector('alice',id,'read',{}),{text:'result [redacted]'});
 assert.deepEqual(await m.callConnector('alice',id,'write',{}),{text:'result [redacted]'});assert.equal(calls,2);
 visibility='public';await m.callConnector('alice',id,'read',{},'page');assert.equal(calls,3);
 owned=false;await assert.rejects(m.callConnector('alice',id,'write',{},'page'),/read only/);assert.equal(calls,3);nativePage=true;await m.callConnector('alice',id,'write',{},'page');assert.equal(calls,4);calls=3;nativePage=false;owned=true;
 await m.updateConnection('alice',id,{allowed:['write']});await assert.rejects(m.callConnector('alice',id,'read',{}),/disabled/);
 assert.deepEqual((await m.connections('alice')).find(c=>c.id===id).automatic,['write']);
 await m.updateConnection('alice',id,{allowed:['read','write']});await m.callConnector('alice',id,'read',{});assert.equal(calls,4);
 assert.ok((await m.enabledConnectors('alice')).flatMap(c=>c.tools).every(t=>!t.confirmationRequired));
 await m.updateConnection('alice','google',{allowed:['list','upload']});assert.deepEqual(await m.callConnector('alice','google','upload',{name:'test'}),{ok:true});assert.equal(calls,5);
 owned=false;await assert.rejects(m.callConnector('alice','google','upload',{},'page'),/read only/);owned=true;
 await m.updateConnection('alice','google',{allowed:['list']});await assert.rejects(m.callConnector('alice','google','upload',{}),/disabled/);
 await m.updateConnection('alice',id,{enabled:false});await assert.rejects(m.callConnector('alice',id,'write',{}),/disabled/);
 await m.updateConnection('alice',id,{allowed:[]});await m.updateConnection('alice',id,{enabled:true});assert.deepEqual((await m.connections('alice')).find(c=>c.id===id).allowed,['read','write']);
 await m.updateConnection('alice',id,{allowed:['read']});assert.deepEqual((await m.connections('alice')).find(c=>c.id===id).allowed,['read']);
 await m.removeConnection('alice',id);assert.equal((await m.connections('alice')).some(c=>c.id===id),false);db.close();delete globalThis.connectorTest;
});
test('MCP initializes, sends session headers, follows pagination and closes its session',async()=>{
 const methods=[];globalThis.mcpTest={toolSchema:{parse:x=>x},remoteRequest:async(url,headers,body,signal,method)=>{if(method==='DELETE'){methods.push('DELETE');return {headers:{},data:null};}methods.push(body.method);if(body.method!=='initialize')assert.equal(headers['Mcp-Session-Id'],'session');return {headers:{'mcp-session-id':'session'},data:body.id?{id:body.id,result:body.method==='initialize'?{protocolVersion:'2025-03-26'}:body.params?.cursor?{tools:[{name:'second',inputSchema:{}}]}:{tools:[{name:'first',inputSchema:{}}],nextCursor:'next'}}:null};}};
 const m=await load('const {toolSchema,remoteRequest}=globalThis.mcpTest;\n'+strip('app/connectors/mcp.ts'));assert.equal((await m.discoverMcp('https://example.org/mcp')).length,2);assert.deepEqual(methods,['initialize','notifications/initialized','tools/list','tools/list','DELETE']);delete globalThis.mcpTest;
});
test('generation and in-page agents both dispatch connector calls as the current user',async()=>{
 let calls=0,owner,tool;
 globalThis.connectorLoop={connectorTools:[{type:'function',name:'list_connectors'},{type:'function',name:'call_connector'}],connectorInstructions:'Use enabled tools.',connectorAgentCall:async(u,n)=>{owner=u;tool=n;return n==='list_connectors'?{connectors:[{id:'adma-connection',name:'ADMA',tools:[{name:'list_files'}]},{id:'remote',name:'Other enabled service',tools:[{name:'read'}]}]}:{found:'authorized result'};},getPage:async()=>({owned:false,visibility:'public'}),canUseConnectorsOn:()=>false,database:()=>({prepare:()=>({bind:()=>({run:async()=>({}),all:async()=>({results:[]})})}),batch:async()=>[]}),model:()=> 'test',partialReply:()=>'',output:r=>r.output.filter(o=>o.type==='message').flatMap(o=>o.content).map(c=>c.text).join(''),api:async(path,p)=>{assert.ok(p.tools.some(t=>t.name==='call_connector'));assert.ok(p.instructions.includes('adma-connection'));assert.ok(p.instructions.includes('Other enabled service'));if(++calls%2===1)return {output:[{type:'function_call',name:'call_connector',call_id:'c',arguments:'{"connectorId":"remote","tool":"read","argumentsJson":"{}"}'}]};assert.ok(p.input.some(i=>i.type==='function_call_output'&&i.output.includes('authorized result')));return {output:[{type:'message',content:[{type:'output_text',text:'{"reply":"done"}'}]}]};},streamArticle:async()=>{},scoped:{pageContextTool:{},pageTaskTool:{}}};
 const source=(runtimeSource+strip('app/agents/runtime.ts')).replace("await (await import('./tools')).applicationToolbox(agent,options.context,signal)","({tools:connectorTools,instructions:JSON.stringify(await connectorAgentCall(agent.ownerId,'list_connectors',{})),execute:async(n,a)=>({data:await connectorAgentCall(agent.ownerId,n,a)})})");
 const m=await load('const {'+Object.keys(globalThis.connectorLoop).join(',')+'}=globalThis.connectorLoop;\n'+source);
 for(const role of ['content-generation','page:p']){const result=await m.askAgent({id:role,role,ownerId:'viewer'},'answer',{},{});assert.equal(result.reply,'done');assert.equal(owner,'viewer');assert.equal(tool,'call_connector');}assert.equal(calls,4);delete globalThis.connectorLoop;
});
