const runtimeSource=readFileSync('app/agent-runtime/loop.ts','utf8')+'\nconst compactSession=async()=>({}),sessionContext=async()=>({}),sessionTools=[],sessionInstructions="",runJournal=()=>async()=>{},safeMemory=JSON.stringify;\n';
import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync,readdirSync} from 'node:fs';import {DatabaseSync} from 'node:sqlite';import ts from 'typescript';import {z} from 'zod';
const strip=p=>readFileSync(p,'utf8').replace(/^import .*;$/gm,'');const load=async s=>import('data:text/javascript;base64,'+Buffer.from(ts.transpile(s,{module:ts.ModuleKind.ESNext,target:ts.ScriptTarget.ES2022})).toString('base64'));
test('connectors isolate accounts, block disabled tools and invalidate approvals after changes',async()=>{
 const db=new DatabaseSync(':memory:');for(const f of readdirSync('drizzle').filter(f=>f.endsWith('.sql')).sort())db.exec(readFileSync('drizzle/'+f,'utf8'));
 const vault=new Map();let calls=0,visibility='private';
 globalThis.connectorTest={z,database:()=>({prepare:sql=>({bind:(...args)=>({first:async()=>db.prepare(sql).get(...args),all:async()=>({results:db.prepare(sql).all(...args)}),run:async()=>({meta:{changes:db.prepare(sql).run(...args).changes}})})})}),getPage:async()=>({owned:true,visibility}),canWritePage:p=>p.owned,vaultPath:async(u,n)=>u+'/'+n,vaultRead:async p=>vault.get(p),vaultWrite:async(p,v)=>vault.set(p,v),vaultDelete:async p=>vault.delete(p),vaultReady:()=>true,signedIn:u=>{if(u.startsWith('guest:'))throw Error('Sign in');},storageStatus:async()=>[],storageToken:async()=>'',disconnectStorage:async()=>{},providerOperation:async()=>{},storageRequest:{parse:x=>x},connectorUrl:u=>new URL(u),discoverMcp:async()=>[{name:'read',inputSchema:{type:'object'},annotations:{readOnlyHint:true}},{name:'write',inputSchema:{type:'object'}}],callMcp:async()=>{calls++;return {text:'result secret-token'};},lock:async()=> 'lease',unlock:async()=>{}};
 const m=await load('const {'+Object.keys(globalThis.connectorTest).join(',')+'}=globalThis.connectorTest;\n'+strip('app/connectors/contracts.ts').replace("import {z} from 'zod';",'')+'\n'+strip('app/connectors/service.ts'));
 const {id}=await m.createConnection('alice',{name:'Test',url:'https://example.org/mcp',token:'secret-token'});
 assert.equal((await m.connections('alice'))[0].enabled,false);assert.deepEqual(await m.connections('bob'),[]);
 await assert.rejects(m.callConnector('alice',id,'read',{}),/disabled/);await assert.rejects(m.callConnector('bob',id,'read',{}),/disabled/);
 await m.updateConnection('alice',id,{enabled:true,automatic:['read']});assert.deepEqual(await m.callConnector('alice',id,'read',{}),{text:'result [redacted]'});assert.equal(calls,1);
 const pending=await m.callConnector('alice',id,'write',{name:'new'});assert.equal(pending.confirmationRequired,true);assert.equal(calls,1);
 await assert.rejects(m.resolveConnectorAction('bob',pending.actionId,true),/not found/);
 await m.updateConnection('alice',id,{enabled:false});await assert.rejects(m.resolveConnectorAction('alice',pending.actionId,true),/disabled/);
 await m.updateConnection('alice',id,{enabled:true});await assert.rejects(m.resolveConnectorAction('alice',pending.actionId,true),/settings changed/);
 const next=await m.callConnector('alice',id,'write',{});await m.resolveConnectorAction('alice',next.actionId,true);assert.equal(calls,2);await m.resolveConnectorAction('alice',next.actionId,true);assert.equal(calls,2);
 visibility='public';const shared=await m.callConnector('alice',id,'read',{},'page');assert.equal(shared.confirmationRequired,true);assert.equal(calls,2);
 await m.updateConnection('alice',id,{allowed:['write']});await assert.rejects(m.callConnector('alice',id,'read',{}),/disabled/);
 await m.removeConnection('alice',id);assert.deepEqual(await m.connections('alice'),[]);db.close();delete globalThis.connectorTest;
});
test('MCP initializes, sends session headers, follows pagination and closes its session',async()=>{
 const methods=[];globalThis.mcpTest={toolSchema:{parse:x=>x},remoteRequest:async(url,headers,body,signal,method)=>{if(method==='DELETE'){methods.push('DELETE');return {headers:{},data:null};}methods.push(body.method);if(body.method!=='initialize')assert.equal(headers['Mcp-Session-Id'],'session');return {headers:{'mcp-session-id':'session'},data:body.id?{id:body.id,result:body.method==='initialize'?{protocolVersion:'2025-03-26'}:body.params?.cursor?{tools:[{name:'second',inputSchema:{}}]}:{tools:[{name:'first',inputSchema:{}}],nextCursor:'next'}}:null};}};
 const m=await load('const {toolSchema,remoteRequest}=globalThis.mcpTest;\n'+strip('app/connectors/mcp.ts'));assert.equal((await m.discoverMcp('https://example.org/mcp')).length,2);assert.deepEqual(methods,['initialize','notifications/initialized','tools/list','tools/list','DELETE']);delete globalThis.mcpTest;
});
test('generation and in-page agents both dispatch connector calls as the current user',async()=>{
 let calls=0,owner,tool;
 globalThis.connectorLoop={connectorTools:[{type:'function',name:'list_connectors'},{type:'function',name:'call_connector'}],connectorInstructions:'Use enabled tools.',connectorAgentCall:async(u,n)=>{owner=u;tool=n;return n==='list_connectors'?{connectors:[{id:'adma-connection',name:'ADMA',tools:[{name:'list_files'}]},{id:'remote',name:'Other enabled service',tools:[{name:'read'}]}]}:{found:'authorized result'};},getPage:async()=>({owned:false,visibility:'public'}),canWritePage:()=>false,database:()=>({prepare:()=>({bind:()=>({run:async()=>({}),all:async()=>({results:[]})})}),batch:async()=>[]}),model:()=> 'test',partialReply:()=>'',output:r=>r.output.filter(o=>o.type==='message').flatMap(o=>o.content).map(c=>c.text).join(''),api:async(path,p)=>{assert.ok(p.tools.some(t=>t.name==='call_connector'));assert.ok(p.instructions.includes('adma-connection'));assert.ok(p.instructions.includes('Other enabled service'));if(++calls%2===1)return {output:[{type:'function_call',name:'call_connector',call_id:'c',arguments:'{"connectorId":"remote","tool":"read","argumentsJson":"{}"}'}]};assert.ok(p.input.some(i=>i.type==='function_call_output'&&i.output.includes('authorized result')));return {output:[{type:'message',content:[{type:'output_text',text:'{"reply":"done"}'}]}]};},streamArticle:async()=>{},scoped:{pageContextTool:{},pageTaskTool:{}}};
 const source=(runtimeSource+strip('app/components-registry/agents.ts')).replace("await import('@/app/chat/context-tools')",'globalThis.connectorLoop.scoped');
 const m=await load('const {'+Object.keys(globalThis.connectorLoop).join(',')+'}=globalThis.connectorLoop;\n'+source);
 for(const role of ['content-generation','page:p']){const result=await m.askAgent({id:role,role,ownerId:'viewer'},'answer',{},{});assert.equal(result.reply,'done');assert.equal(owner,'viewer');assert.equal(tool,'call_connector');}assert.equal(calls,4);delete globalThis.connectorLoop;
});
