import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';import ts from 'typescript';import {z} from 'zod';
const strip=p=>readFileSync(p,'utf8').replace(/^import .*;$/gm,'');const load=async s=>import('data:text/javascript;base64,'+Buffer.from(ts.transpile(s,{module:ts.ModuleKind.ESNext,target:ts.ScriptTarget.ES2022})).toString('base64'));
test('directory contains thirteen distinct working adapter or MCP presets',async()=>{const c=await load(strip('app/connectors/catalog.ts'));globalThis.catalogZ=z;const a=await load('const z=globalThis.catalogZ;\n'+strip('app/connectors/adapters.ts'));assert.equal(c.connectorCatalog.length,13);assert.equal(new Set(c.connectorCatalog.map(p=>p.id)).size,13);for(const p of c.connectorCatalog){assert.ok(p.docs.startsWith('https://'));if(p.kind==='api')assert.ok(a.apiTools[p.id]?.length);if(p.kind==='mcp')assert.ok(p.url.startsWith('https://'));}});
test('native adapter calls fix destinations, validate IDs, paginate and classify writes',async()=>{globalThis.catalogZ=z;const a=await load('const z=globalThis.catalogZ;\n'+strip('app/connectors/adapters.ts'));assert.throws(()=>a.apiOperation('todoist','complete_task',{taskId:'../projects'}));assert.throws(()=>a.apiOperation('slack','read_messages',{channel:'C123',url:'https://evil.example'}));assert.throws(()=>a.apiOperation('notion','arbitrary',{}));const search=a.apiOperation('brave','web_search',{query:'a & b'});assert.equal(new URL(search.url).searchParams.get('q'),'a & b');const list=a.apiOperation('airtable','list_records',{baseId:'app123',tableId:'tbl123',cursor:'next'});assert.equal(new URL(list.url).hostname,'api.airtable.com');assert.equal(new URL(list.url).searchParams.get('offset'),'next');const write=a.apiOperation('notion','append_note',{blockId:'11111111-1111-4111-8111-111111111111',text:'A note'});assert.equal(write.method,'PATCH');assert.equal(write.body.children[0].paragraph.rich_text[0].text.content,'A note');assert.equal(a.apiTools.slack.find(t=>t.name==='send_message').annotations.readOnlyHint,false);assert.equal(a.apiTools.todoist.find(t=>t.name==='list_tasks').annotations.readOnlyHint,true);});

test('ADMA uses Token auth, fixed documented routes, private multipart uploads and safe text downloads',async()=>{
 globalThis.catalogZ=z;const calls=[];globalThis.admaTransport=async(...args)=>{calls.push(args);return {data:{files:[]}};};
 const a=await load('const z=globalThis.catalogZ,remoteRequest=globalThis.admaTransport;\n'+strip('app/connectors/adapters.ts'));
 await a.verifyApiConnector('adma','test-token');assert.equal(calls[0][0],'https://adma.aisoup.net/api/v1/folders/');assert.equal(calls[0][1].Authorization,'Token test-token');
 const op=a.apiOperation('adma','list_files',{folder_id:'123',is_public:false,file_type:'csv'});const url=new URL(op.url);assert.equal(url.hostname,'adma.aisoup.net');assert.equal(url.searchParams.get('is_public'),'false');assert.equal(url.searchParams.get('folder_id'),'123');
 assert.equal(a.apiOperation('adma','folder_info',{folder_id:'abc-123'}).url,'https://adma.aisoup.net/api/v1/folders/abc-123/info/');
 await a.executeApiConnector('adma','test-token','read_text_file',{file_id:'123'});assert.equal(calls.at(-1)[6].textResponse,true);assert.ok(calls.at(-1)[0].endsWith('/123/download/'));
 const upload=a.apiOperation('adma','upload_text_file',{filename:'data.csv',content:'city,value\n北京,12'});assert.ok(a.apiOperation('adma','upload_text_file',{filename:'数据.csv',content:'x'}).body);assert.equal(upload.method,'POST');assert.ok(upload.body instanceof Uint8Array);assert.match(upload.headers['Content-Type'],/^multipart\/form-data; boundary=/);assert.match(upload.body.toString(),/name="files"; filename="data.csv"/);assert.match(upload.body.toString(),/name="is_public"\r\n\r\nfalse/);assert.match(upload.body.toString(),/北京,12/);
 assert.equal(a.apiTools.adma.find(t=>t.name==='upload_text_file').annotations.readOnlyHint,false);
 assert.throws(()=>a.apiOperation('adma','folder_info',{folder_id:'../auth/token'}));assert.throws(()=>a.apiOperation('adma','upload_text_file',{filename:'x.csv"\r\nX-Evil: 1',content:'x'}));assert.throws(()=>a.apiOperation('adma','list_files',{url:'https://evil.example'}));
 delete globalThis.admaTransport;
});
test('transport sends multipart bytes intact and rejects binary files in text mode',async()=>{
 const {EventEmitter}=await import('node:events'),{Readable}=await import('node:stream');let contentType='text/csv',sent;
 globalThis.admaHttp={lookup:async()=>[{address:'203.0.113.10'}],sourceUrl:u=>new URL(u),publicIPv4:()=>true,request:(_url,options,callback)=>{const req=new EventEmitter();req.end=body=>{sent=body;queueMicrotask(()=>{const res=Readable.from([Buffer.from('name,value\n北京,12')]);res.statusCode=200;res.headers={'content-type':contentType};callback(res);});};return req;}};
 const h=await load('const {lookup,sourceUrl,publicIPv4,request}=globalThis.admaHttp;\n'+strip('app/connectors/http.ts'));
 const body=Buffer.from('multipart bytes');const result=await h.remoteRequest('https://adma.aisoup.net/api/v1/files/1/download/',{},body,undefined,'GET',true,{textResponse:true});assert.equal(sent,body);assert.equal(result.data.content,'name,value\n北京,12');
 contentType='application/pdf';await assert.rejects(h.remoteRequest('https://adma.aisoup.net/api/v1/files/1/download/',{},undefined,undefined,'GET',true,{textResponse:true}),/not a supported text/);
 delete globalThis.admaHttp;
});
