import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';import ts from 'typescript';import {z} from 'zod';
const source=readFileSync('app/disambiguation/index.ts','utf8').replace(/import [\s\S]*?from ['"][^'"]+['"];?/g,'');
test('disambiguation creates precise destinations and upgrades an owned page in place',async()=>{
 let page={id:'p',owned:true,kind:'static',title:'Party',summary:'old',body:'old',labels:{},visibility:'private'},writes=0;
 const result={needed:true,title:'Party',summary:'Choose a meaning.',entries:[{question:'Political party',description:'An electoral organization.',group:'Politics'},{question:'Party (law)',description:'A participant in proceedings.',group:'Law'},{question:'party',description:'Do not self-link.',group:''},{question:'Party (law)',description:'Duplicate.',group:'Law'}]};
 globalThis.indexTest={z,askAgent:async()=>result,database:()=>({prepare(sql){return {bind(...args){return {sql,args,all:async()=>({results:[]})};}};},batch:async stmts=>{assert.equal(stmts.length,1);const s=stmts[0];assert.ok(!s.sql.includes('questions'));assert.ok(!s.sql.includes('visibility='));writes++;page={...page,title:s.args[0],summary:s.args[1],body:s.args[2],labels:JSON.parse(s.args[5])};}}),getPage:async()=>page,lock:async()=>'lease',unlock:async()=>{},relocateQuote:()=>[]};
 const m=await import('data:text/javascript;base64,'+Buffer.from(ts.transpile('const {'+Object.keys(globalThis.indexTest).join(',')+'}=globalThis.indexTest;\n'+source,{module:ts.ModuleKind.ESNext,target:ts.ScriptTarget.ES2022})).toString('base64'));
 const index=await m.classifyAmbiguity('party','en',{});assert.equal(index.entries.length,2);const updated=await m.upgradeIndex(page,index,'owner');assert.equal(updated.id,'p');assert.equal(updated.visibility,'private');assert.equal(updated.labels.templateId,'disambiguation-v1');assert.equal(writes,1);
 await m.upgradeIndex(updated,index,'owner');assert.equal(writes,1);assert.equal(await m.upgradeIndex({...updated,owned:false},index,'other'),null);delete globalThis.indexTest;
});
