import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';import ts from 'typescript';
const source=readFileSync('app/chat/edit-draft.ts','utf8').replace(/import [\s\S]*?from ['"][^'"]+['"];?/g,'');
test('save requires the current owner and exact current proposal; stale drafts cannot overwrite edits',async()=>{
 const objects=new Map();let writes=0,page={id:'p',owned:true,kind:'static',title:'Title',summary:'Summary',body:'Original',sources:[],visibility:'private'};
 globalThis.draftTest={env:{FILES:{get:async k=>objects.has(k)?{json:async()=>JSON.parse(objects.get(k))}:null,put:async(k,v)=>objects.set(k,v),delete:async k=>objects.delete(k)}},getPage:async()=>page,lock:async()=>'lease',unlock:async()=>{},relocateQuote:()=>[],database:()=>({prepare(sql){return {bind(...args){return {sql,args,all:async()=>({results:[]})};}};},batch:async statements=>{writes++;const s=statements[0];assert.ok(!s.sql.includes('questions'));assert.ok(!s.sql.includes('visibility='));page={...page,title:s.args[0],summary:s.args[1],body:s.args[2],updatedAt:s.args[3]};}})};
 const m=await import('data:text/javascript;base64,'+Buffer.from(ts.transpile('const {'+Object.keys(globalThis.draftTest).join(',')+'}=globalThis.draftTest;\n'+source,{module:ts.ModuleKind.ESNext,target:ts.ScriptTarget.ES2022})).toString('base64'));
 const a={id:'session',ownerId:'owner'},draft=await m.stageEdit(a,page,{title:'Title',summary:'Summary',body:'Proposed'});assert.equal(writes,0);assert.equal((await m.readEditDraft(a,'p')).id,draft.id);assert.equal(await m.readEditDraft({...a,ownerId:'other'},'p'),null);
 page={...page,body:'Concurrent edit'};await assert.rejects(m.saveEditDraft(a,'p',draft.id),/article changed/);assert.equal(writes,0);
 const fresh=await m.stageEdit(a,page,{title:'Title',summary:'Summary',body:'Confirmed'});await assert.rejects(m.saveEditDraft(a,'p',draft.id),/replaced/);
 const saved=await m.saveEditDraft(a,'p',fresh.id);assert.equal(saved.page.body,'Confirmed');assert.equal(saved.page.id,'p');assert.equal(saved.page.visibility,'private');assert.equal(await m.readEditDraft(a,'p'),null);assert.equal((await m.saveEditDraft(a,'p',fresh.id)).alreadySaved,true);assert.equal(writes,1);delete globalThis.draftTest;
});
