import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';import ts from 'typescript';import {z} from 'zod';import ExcelJS from 'exceljs';import {PDFDocument} from 'pdf-lib';import {parse} from 'csv-parse/sync';import yauzl from 'yauzl';
let accessible=true,reads=0;
globalThis.fileReaderDeps={Buffer,z,ExcelJS,PDFDocument,parse,yauzl,env:{FILES:{get:async()=>{reads++;return {arrayBuffer:async()=>new TextEncoder().encode('a,b\n1,2').buffer};}}},getPage:async()=>accessible?{id:'p'}:null,contextFiles:async()=>[{row:{id:'f',display_name:'table.csv',folder_path:'data'},data:{fileName:'original.csv',mimeType:'text/csv',location:'r2://FILES/uploads/f',size:7}}],listContextFiles:async()=>[{id:'f'}]};
const source=readFileSync('app/context-files/read.ts','utf8').replace(/^import .*;$/gm,'');const m=await import('data:text/javascript;base64,'+Buffer.from(ts.transpile('const {'+Object.keys(globalThis.fileReaderDeps).join(',')+'}=globalThis.fileReaderDeps;'+source,{module:ts.ModuleKind.ESNext,target:ts.ScriptTarget.ES2022})).toString('base64'));
test('CSV range reads preserve quoted newlines, UTF-8 and rows beyond model inline preview limits',async()=>{const rows=['name,value','"你好\nworld",42',...Array.from({length:1100},(_,i)=>'row'+i+','+i)];const d=(await m.decodeFile(Buffer.from(rows.join('\n')),'data.csv','text/csv',{start:2,count:1})).data;assert.deepEqual(d.rows,[['你好\nworld','42']]);assert.equal(d.nextRow,3);const late=(await m.decodeFile(Buffer.from(rows.join('\n')),'data.csv','text/csv',{start:1050,count:1})).data;assert.deepEqual(late.rows,[['row1047','1047']]);});
test('XLSX sheets, cell ranges and formula cached values are returned without evaluating formulas',async()=>{const wb=new ExcelJS.Workbook();wb.addWorksheet('First').addRow(['hello']);const s=wb.addWorksheet('Sales');s.addRow(['Name','Total']);s.addRow(['A',{formula:'20+22',result:42}]);const d=(await m.decodeFile(Buffer.from(await wb.xlsx.writeBuffer()),'data.xlsx','application/octet-stream',{sheet:'Sales',start:2,count:1,column:2,columns:1})).data;assert.equal(d.sheets.length,2);assert.deepEqual(d.rows,[[{formula:'20+22',cachedResult:42}]]);assert.equal(d.startColumn,2);assert.equal(d.nextRow,null);});
test('PDF reader sends only selected pages, and images are actual multimodal content',async()=>{const doc=await PDFDocument.create();for(let i=0;i<3;i++)doc.addPage().drawText('Page '+(i+1));const r=await m.decodeFile(Buffer.from(await doc.save()),'paper.pdf','application/pdf',{start:2,count:1});assert.equal(r.data.totalPages,3);assert.equal(r.data.nextPage,3);const sliced=await PDFDocument.load(Buffer.from(r.parts[0].file_data.split(',')[1],'base64'));assert.equal(sliced.getPageCount(),1);const image=await m.decodeFile(Buffer.from('image bytes'),'photo.png','image/png');assert.equal(image.parts[0].type,'input_image');assert.match(image.parts[0].image_url,/^data:image\/png;base64,/);});
test('text search cites original line numbers and unknown binaries are explicit',async()=>{const d=(await m.decodeFile(Buffer.from('zero\none\nneedle\nthree'),'notes.txt','text/plain',{query:'needle'})).data;assert.deepEqual(d.lines,[{line:3,text:'needle'}]);assert.equal((await m.decodeFile(Buffer.from([0,1]),'movie.mp4','video/mp4')).data.supported,false);await assert.rejects(m.decodeFile(Buffer.from([0]),'binary.txt','text/plain'),/Binary/);});
test('file reads enforce page and attachment access before storage retrieval',async()=>{accessible=false;await assert.rejects(m.readUploadedFile('p','u','f'),/inaccessible/);assert.equal(reads,0);accessible=true;await assert.rejects(m.readUploadedFile('p','u','other'),/inaccessible/);assert.equal(reads,0);const result=await m.readUploadedFile('p','u','f');assert.equal(reads,1);assert.equal(result.data.folderPath,'data');assert.deepEqual(result.data.rows,[['a','b'],['1','2']]);});
