import {customDesign} from './fixtures/custom-style.mjs';
import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';import ts from 'typescript';import {z} from 'zod';
const strip=p=>readFileSync(p,'utf8').replace(/^import .*;$/gm,'');
const load=s=>import('data:text/javascript;base64,'+Buffer.from(ts.transpile(s,{module:ts.ModuleKind.ESNext,target:ts.ScriptTarget.ES2022})).toString('base64'));
const base={subject:'SigPID: significant permission identification for android malware detection',subjectType:'publication',goal:'Understand the named paper',explicitConstraints:['Named publication'],assumptions:[],uncertainties:[],mustCover:['Identify the publication','Explain contributions and experiments'],sourceRequirements:['Original paper'],outputKind:'article',service:'none',fresh:false,needsDisambiguation:false,singleMeaningCertain:true,interpretations:['The named publication']};
test('analysis preserves original query, permits research, validates structure and normalizes ambiguity',async()=>{
 let answer=base,task,options;
 globalThis.intentUnit={z,askAgent:async(a,i,t,s,signal,onReply,files,o)=>{task=t;options=o;return answer;}};
 const m=await load('const {z,askAgent}=globalThis.intentUnit;\n'+strip('app/page-programs/custom-style.ts')+'\n'+strip('app/page-programs/visual-style.ts')+'\n'+strip('app/page-programs/generation-intent.ts'));
 const signal=new AbortController().signal;
 const plan=await m.analyzeGenerationIntent(base.subject,'en',{},signal);
 assert.equal(task.question,base.subject);assert.equal(options.webSearch,'auto');assert.deepEqual(plan.mustCover,base.mustCover);
 answer={...base,subject:'china',interpretations:['Country','Porcelain']};
 assert.equal((await m.analyzeGenerationIntent('china','en',{},signal)).needsDisambiguation,true);
 answer={...base,visualTheme:'custom',visualDesign:customDesign};
 assert.deepEqual((await m.analyzeGenerationIntent('Custom observatory','en',{},signal)).visualDesign,customDesign);
 answer={...base,visualTheme:'custom'};await assert.rejects(m.analyzeGenerationIntent('Missing design','en',{},signal));
 answer={...base,mustCover:[]};await assert.rejects(m.analyzeGenerationIntent('query','en',{},signal));
 answer={requirements:[{index:0,satisfied:true,evidence:'The paper identity is present.'}],reason:'Experiments are missing'};
 assert.equal((await m.reviewGeneratedDefinition('query',base,{}, {},signal)).accepted,false);
 answer={requirements:base.mustCover.map((_,index)=>({index,satisfied:true,evidence:'Specific evidence from the supplied definition.'})),reason:''};
 assert.equal((await m.reviewGeneratedDefinition('query',base,{}, {},signal)).accepted,true);
 assert.deepEqual(task.indexedRequirements,base.mustCover.map((requirement,index)=>({index,requirement})));
 answer={requirements:base.mustCover.map((_,i)=>({index:i+1,satisfied:true,evidence:'Concrete evidence in this supplied definition.'})).reverse(),reason:'All requirements fulfilled'};
 assert.equal((await m.reviewGeneratedDefinition('query',base,{}, {},signal)).accepted,true);
 answer.requirements[0].satisfied=false;assert.equal((await m.reviewGeneratedDefinition('query',base,{}, {},signal)).accepted,false);
 answer.requirements=[answer.requirements[1],answer.requirements[1]];assert.equal((await m.reviewGeneratedDefinition('query',base,{}, {},signal)).accepted,false);
 answer.requirements=[{index:1,satisfied:true,evidence:'Concrete evidence for only one requirement.'}];assert.equal((await m.reviewGeneratedDefinition('query',base,{}, {},signal)).accepted,false);
 delete globalThis.intentUnit;
});
