import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import ts from 'typescript';
const load=async s=>import('data:text/javascript;base64,'+Buffer.from(ts.transpile(s,{module:ts.ModuleKind.ESNext,target:ts.ScriptTarget.ES2022})).toString('base64'));
const {nearestQuestions}=await load(readFileSync('app/api/ask/ranking.ts','utf8'));
let confidence="uncertain",rows=[],decisions=[],checked=[],events=[],pages={};
globalThis.coverage={nearestQuestions,cosine:(_a,b)=>b[0],database:()=>({prepare:()=>({bind:()=>({all:async()=>({results:rows})})})}),getPage:async(id,user)=>{assert.equal(user,'visitor');return pages[id]||null;},assessQuestion:async(_q,c)=>{decisions.push(c.map(r=>r.id));return {questionId:c[0]?.id,confidence,reason:"Test decision"};},reviewMappedPage:async(q,p)=>{checked.push([q,p.id]);return {accepted:p.body==='Complete historical list',reason:p.body};},recordAction:async(_a,action,result)=>events.push({action,...result})};
const search=await load(readFileSync('app/api/ask/question-search.ts','utf8').replace(/^import .*;$/gm,'')+'\nconst normalize=s=>s.trim().toLowerCase();const repairKnownMappings=async()=>{};const importSessionRoutes=async()=>{};const ensureRoutingScopes=async()=>{};const importWikiRoutes=async()=>{};const {database,getPage,reviewMappedPage,cosine,assessQuestion,nearestQuestions,recordAction}=globalThis.coverage;');
function setup(){confidence="uncertain";decisions=[];checked=[];events=[];rows=[{id:'exact',question:'中国人民银行行长历任名单',page_id:'wrong',language:'zh-Hans',embedding:'[1]'},{id:'alias',question:'中国人民银行行长',page_id:'wrong',language:'zh-Hans',embedding:'[0.8]'},{id:'history',question:'历任央行行长和任期',page_id:'right',language:'zh-Hans',embedding:'[0.7]'}];pages={wrong:{id:'wrong',body:'Current governor only'},right:{id:'right',body:'Complete historical list'}};}
test('rejects the selected page without trying other candidates even when another page could answer',async()=>{setup();assert.equal(await search.matchQuestion('中国人民银行行长历任名单',[1],'zh-Hans','visitor',{}),null);assert.deepEqual(decisions,[['exact','alias','history']]);assert.deepEqual(checked.map(c=>c[1]),['wrong']);assert.equal(events.filter(e=>e.action==='Check mapped page answers question')[0].accepted,false);});
test('no answer-capable mapped page returns a cache miss rather than the incomplete page',async()=>{setup();pages.right.body='Another incomplete answer';assert.equal(await search.matchQuestion('中国人民银行行长历任名单',[1],'zh-Hans','visitor',{}),null);assert.equal(checked.length,1);});
test('inaccessible mapped pages are never reviewed or returned',async()=>{setup();delete pages.wrong;assert.equal(await search.matchQuestion('中国人民银行行长历任名单',[1],'zh-Hans','visitor',{}),null);assert.deepEqual(checked,[]);assert.equal(decisions.length,1);});
test('very confident equivalence skips the page-content check',async()=>{setup();confidence='high';assert.equal(await search.matchQuestion('中国人民银行行长历任名单',[1],'zh-Hans','visitor',{}),'wrong');assert.equal(checked.length,0);assert.equal(events[0].confidence,'high');});
test('a definite question mismatch skips page review and returns a cache miss',async()=>{setup();confidence='none';assert.equal(await search.matchQuestion('中国人民银行行长历任名单',[1],'zh-Hans','visitor',{}),null);assert.equal(checked.length,0);assert.equal(decisions.length,1);});

test('an uncertain selected page is reused when its content passes',async()=>{setup();pages.wrong.body='Complete historical list';assert.equal(await search.matchQuestion('中国人民银行行长历任名单',[1],'zh-Hans','visitor',{}),'wrong');assert.equal(decisions.length,1);assert.equal(checked.length,1);});

test('a rejected question cannot be rescued by its mapped page',async()=>{setup();confidence='none';pages.wrong.body='Complete historical list';assert.equal(await search.matchQuestion('中国人民银行行长历任名单',[1],'zh-Hans','visitor',{}),null);assert.equal(checked.length,0);});

test('specific meanings of an index require reading the selected page even with high or none model confidence',async()=>{for(const verdict of ['high','none']){setup();confidence=verdict;rows=[{id:'index',question:'Mandarin',normalized:'mandarin',canonical_question:'Mandarin',template_id:'disambiguation-v1',page_labels:JSON.stringify({indexEntries:[{question:'Mandarin Chinese'}]}),page_id:'wrong',language:'en',embedding:'[1]'}];assert.equal(await search.matchQuestion('Mandarin Chinese',[1],'en','visitor',{}),null);assert.deepEqual(checked,[['Mandarin Chinese','wrong']]);assert.equal(events[0].confidence,'uncertain');}});
