import test from 'node:test';import assert from 'node:assert/strict';import ts from 'typescript';import {readFileSync} from 'node:fs';import {pathToFileURL} from 'node:url';
const compile=s=>'data:text/javascript;base64,'+Buffer.from(ts.transpile(s,{module:ts.ModuleKind.ESNext,target:ts.ScriptTarget.ES2022})).toString('base64');
const contracts=compile(readFileSync('app/sandboxes/contracts.ts','utf8').replace("from 'zod'",`from '${pathToFileURL(process.cwd()+'/node_modules/zod/index.js')}'`));
const {runOpenAIProgram,hostedExecution}=await import(compile(readFileSync('app/sandboxes/openai-provider.ts','utf8').replace("from './contracts'",`from '${contracts}'`)));
const program={kind:'sandbox-program',language:'python',code:'def main(input): return input'};
test('saved code is run during setup; only the completed turn artifact is returned and session is deleted',async()=>{
 const original=globalThis.fetch;const calls=[];let sessionBody;
 globalThis.fetch=async(url,options={})=>{calls.push({url,method:options.method});if(url.endsWith('/sessions')){sessionBody=JSON.parse(options.body);return Response.json({id:'s1'});}if(url.includes('/turns?'))return Response.json({data:[{id:'t1',status:'completed'}]});if(url.includes('/artifacts?'))return Response.json({data:[{id:'wrong',turn_id:'old',path:'/workspace/outputs/execution.json',size_bytes:20},{id:'a1',turn_id:'t1',path:'/workspace/outputs/execution.json',size_bytes:80}],has_more:false});if(url.endsWith('/a1/content'))return Response.json({ok:true,result:{value:42},stdout:'',stderr:''});if(options.method==='DELETE')return Response.json({deleted:true});throw Error('Unexpected endpoint');};
 try{const result=await runOpenAIProgram(program,{},[],'secret-never-in-sandbox','existing-model',async()=>{});assert.equal(result.result.value,42);assert.equal(sessionBody.environment.network.access,'disabled');assert.equal(sessionBody.environment.setup_commands[0].command,'python3 /workspace/execute.py');assert.equal(JSON.stringify(sessionBody).includes('secret-never-in-sandbox'),false);assert.equal(calls.at(-1).method,'DELETE');}finally{globalThis.fetch=original;}
});
test('a failed turn is not accepted as execution and still cleans up',async()=>{
 const original=globalThis.fetch;let deleted=false;globalThis.fetch=async(url,options={})=>{if(options.method==='DELETE'){deleted=true;return Response.json({deleted:true});}if(url.endsWith('/sessions'))return Response.json({id:'s1'});return Response.json({data:[{id:'t1',status:'failed'}]});};
 try{await assert.rejects(()=>runOpenAIProgram(program,{},[],'key','model',async()=>{}),/TURN_FAILED/);assert.equal(deleted,true);}finally{globalThis.fetch=original;}
});
test('legacy file inputs are relocated without rewriting saved source; runner bounds execution and result size',()=>{const files=hostedExecution(program,{path:'/home/user/context/data.csv'},[{path:'/home/user/context/data.csv',data:new ArrayBuffer(0)}]);assert.equal(files.find(f=>f.path==='/workspace/input.json').data,'{"path":"/workspace/context/data.csv"}');assert.equal(files.find(f=>f.path==='/workspace/program.py').data,program.code);const runner=files.find(f=>f.path==='/workspace/execute.py').data;assert.match(runner,/wait\(timeout=30\)/);assert.match(runner,/st_size>128000/);assert.match(runner,/killpg/);});
