import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync,readdirSync} from 'node:fs';
import {DatabaseSync} from 'node:sqlite';
import ts from 'typescript';
const strip=p=>readFileSync(p,'utf8').replace(/import [\s\S]*?from ['"][^'"]+['"];?/g,'');
const load=async code=>import('data:text/javascript;base64,'+Buffer.from(ts.transpile(strip('app/page-permissions.ts')+'\n'+code,{module:ts.ModuleKind.ESNext,target:ts.ScriptTarget.ES2022})).toString('base64'));
test('three access levels control real saves, revocation and independent fork settings',async()=>{
 const db=new DatabaseSync(':memory:');for(const f of readdirSync('drizzle').filter(f=>f.endsWith('.sql')).sort())db.exec(readFileSync('drizzle/'+f,'utf8'));
 db.exec("INSERT INTO pages(id,owner_id,question,title,summary,body,category,sources,visibility,created_at,kind) VALUES('p','alice','Topic','Topic','','Original','Test','[]','public','now','static'),('fork','alice','Topic','Topic','','Fork body','Test','[]','private','now','static')");
 const objects=new Map();
 const database=()=>({prepare:sql=>({bind:(...args)=>({sql,args,first:async()=>db.prepare(sql).get(...args),all:async()=>({results:db.prepare(sql).all(...args)}),run:async()=>({meta:{changes:db.prepare(sql).run(...args).changes}})})}),batch:async statements=>statements.map(s=>({meta:{changes:db.prepare(s.sql).run(...s.args).changes}}))});
 const getPage=async(id,user)=>{const r=db.prepare("SELECT * FROM pages WHERE id=? AND (visibility='public' OR owner_id=?)").get(id,user);return r?{...r,owned:r.owner_id===user,publicWrite:r.public_write===1,sources:[],updatedAt:r.updated_at}:null;};
 globalThis.accessTest={database,getPage,env:{FILES:{get:async k=>objects.has(k)?{json:async()=>JSON.parse(objects.get(k))}:null,put:async(k,v)=>objects.set(k,v),delete:async k=>objects.delete(k)}},relocateQuote:()=>[],lock:async()=>{db.prepare('INSERT OR REPLACE INTO generation_locks VALUES(?,?,?)').run('refresh:p','lease',Date.now()+90000);return 'lease'},unlock:async()=>db.exec('DELETE FROM generation_locks')};
 const m=await load('const {'+Object.keys(globalThis.accessTest).join(',')+'}=globalThis.accessTest;\n'+strip('app/chat/edit-draft.ts'));
 const bob={id:'bob-session',ownerId:'bob'},change={title:'Topic',summary:'',body:'Edited'};
 assert.equal(m.pageAccess(await getPage('p','bob')),'public-read');
 assert.equal(await getPage('fork','bob'),null);
 await assert.rejects(m.stageEdit(bob,await getPage('p','bob'),change),/read-only/);
 db.exec("UPDATE pages SET public_write=1 WHERE id='p'");
 const draft=await m.stageEdit(bob,await getPage('p','bob'),change);
 assert.equal((await getPage('p','bob')).body,'Original');
 db.exec("UPDATE pages SET public_write=0 WHERE id='p'");
 await assert.rejects(m.saveEditDraft(bob,'p',draft.id),/read-only/);
 db.exec("UPDATE pages SET public_write=1 WHERE id='p'");
 assert.equal((await m.saveEditDraft(bob,'p',draft.id)).page.body,'Edited');
 assert.equal((await getPage('fork','alice')).body,'Fork body');
 assert.equal(m.pageAccess(await getPage('fork','alice')),'private');
 const route=await load('const {database,getPage,lock,unlock}=globalThis.accessTest;const getActor=async r=>({userId:r.headers.get("x-user"),finish:r=>r});const reply=(d,status=200)=>Response.json(d,{status});const sameOrigin=()=>true;\n'+strip('app/api/pages/[id]/route.ts'));
 const patch=async(user,access)=>route.PATCH(new Request('https://wiki.test/api/pages/p',{method:'PATCH',headers:{'x-user':user},body:JSON.stringify({access})}),{params:Promise.resolve({id:'p'})});
 assert.equal((await patch('bob','private')).status,403);
 assert.equal((await patch('alice','private')).status,200);
 assert.equal(await getPage('p','bob'),null);
 assert.equal(m.canWritePage(await getPage('p','alice')),true);
 const files=await load('const {database,getPage}=globalThis.accessTest;\n'+strip('app/context-files/tree.ts')+'\n'+strip('app/context-files/server.ts'));
 db.exec("UPDATE pages SET visibility='public',public_write=0 WHERE id='p';INSERT INTO components VALUES('upload','data',1,'bob','private','en','File','','{}','now')");
 await files.attachContextFile('p','upload','bob');
 assert.equal(db.prepare("SELECT scope FROM page_files").get().scope,'bob');
 db.exec("UPDATE pages SET public_write=1 WHERE id='p'");
 await files.attachContextFile('p','upload','bob');
 assert.deepEqual(db.prepare("SELECT scope FROM page_files ORDER BY scope").all().map(r=>r.scope),['','bob']);
 const listed=await files.listContextFiles('p','bob');assert.equal(listed.every(f=>f.removable),true);
 db.exec("UPDATE pages SET public_write=0 WHERE id='p'");
 assert.equal((await files.listContextFiles('p','bob')).filter(f=>f.removable).length,1);
 db.close();delete globalThis.accessTest;
});
test('page storage writes require live write access both when proposed and when approved',async()=>{
 const saved=new Map();let writes=0,writable=false;
 globalThis.storageAccess={getPage:async()=>({owned:false,visibility:'public',publicWrite:writable}),storageRequest:{parse:x=>x},isMutation:op=>!['list','read'].includes(op),signedIn:()=>{},vaultPath:async(u,id)=>u+'/'+id,vaultRead:async k=>saved.get(k),vaultWrite:async(k,v)=>saved.set(k,v),storageToken:async()=>'',providerOperation:async req=>{if(req.operation==='trash')writes++;return {ok:true}},lock:async()=> 'lease',unlock:async()=>{}};
 const m=await load('const {'+Object.keys(globalThis.storageAccess).join(',')+'}=globalThis.storageAccess;\n'+strip('app/storage/service.ts'));
 await m.executeStorage({operation:'list'},'bob','p');
 await assert.rejects(m.executeStorage({operation:'trash'},'bob','p'),/PAGE_READ_ONLY/);
 writable=true;const proposal=await m.executeStorage({operation:'trash'},'bob','p');assert.equal(writes,0);
 writable=false;await assert.rejects(m.approveStorage(proposal.actionId,'bob'),/PAGE_READ_ONLY/);assert.equal(writes,0);
 writable=true;await m.approveStorage(proposal.actionId,'bob');assert.equal(writes,1);
 delete globalThis.storageAccess;
});
