import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';import ts from 'typescript';
let decision,request;
globalThis.confidenceApi=async(_path,body)=>{request=body;return decision;};
const full=readFileSync('app/api/ask/ai.ts','utf8');
const source=full.slice(full.indexOf('export type Candidate='),full.indexOf('const metadataSchema='))+"\nconst model=()=> 'test';const api=(...args)=>globalThis.confidenceApi(...args);const output=r=>JSON.stringify(r);";
const {assessQuestion,verify}=await import('data:text/javascript;base64,'+Buffer.from(ts.transpile(source,{module:ts.ModuleKind.ESNext,target:ts.ScriptTarget.ES2022})).toString('base64'));
const candidates=[{id:'q',question:'Example',language:'en',score:1}];
test('high confidence requires all equivalence conditions; uncertain choices remain available for page review',async()=>{decision={requiresSenseAssumption:false,inputMayBeBroader:false,candidateMayBeBroader:false,answerToEitherFullyAnswersOther:true,questionId:'q',hasDoubt:false,confidence:'high',relation:'equivalent',sameSubject:true,sameScope:true,fullyAnswered:true,reason:'Same intent'};assert.equal((await assessQuestion('Example',candidates,'en')).confidence,'high');assert.equal(await verify('Example',candidates,'en'),'q');decision={...decision,confidence:'uncertain',relation:'ambiguous',sameScope:false};assert.equal((await assessQuestion('Example',candidates,'en')).questionId,'q');assert.equal(await verify('Example',candidates,'en'),null);assert.equal(request.text.format.schema.properties.confidence.enum.includes('uncertain'),true);});
test('known scope mismatches and fabricated candidate IDs cannot qualify',async()=>{decision={questionId:'q',confidence:'high',relation:'narrower',reason:'Different scope'};assert.equal((await assessQuestion('Example',candidates,'en')).confidence,'none');assert.equal((await assessQuestion('Example',candidates,'en')).questionId,'q');decision={...decision,questionId:'invented',relation:'equivalent',sameSubject:true,sameScope:true,fullyAnswered:true};assert.equal((await assessQuestion('Example',candidates,'en')).questionId,null);assert.equal((await assessQuestion('Example',candidates,'zh-Hans')).confidence,'none');});

test('any doubt overrides otherwise confident equivalence',async()=>{decision={questionId:'q',hasDoubt:true,confidence:'high',relation:'equivalent',sameSubject:true,sameScope:true,fullyAnswered:true,reason:'Scope may differ'};assert.equal((await assessQuestion('Example',candidates,'en')).confidence,'uncertain');assert.equal(await verify('Example',candidates,'en'),null);});

test('possible scope expansion in either direction prevents direct routing even when the model labels it high',async()=>{const equivalent={questionId:'q',requiresSenseAssumption:false,inputMayBeBroader:false,candidateMayBeBroader:false,answerToEitherFullyAnswersOther:true,hasDoubt:false,confidence:'high',relation:'equivalent',sameSubject:true,sameScope:true,fullyAnswered:true,reason:'Same'};for(const key of ['inputMayBeBroader','candidateMayBeBroader']){decision={...equivalent,[key]:true};assert.equal((await assessQuestion('Chinese language',candidates,'en')).confidence,'uncertain');}decision={...equivalent,answerToEitherFullyAnswersOther:false};assert.equal((await assessQuestion('Chinese people',candidates,'en')).confidence,'uncertain');});

test('an assumed interpretation blocks definite equivalence',async()=>{decision={requiresSenseAssumption:true,inputMayBeBroader:false,candidateMayBeBroader:false,answerToEitherFullyAnswersOther:true,questionId:'q',hasDoubt:false,confidence:'high',relation:'equivalent',sameSubject:true,sameScope:true,fullyAnswered:true,reason:'Assumes the language meaning'};assert.equal((await assessQuestion('Mandarin Chinese',candidates,'en')).confidence,'uncertain');assert.match(request.instructions,/ANY doubt/);});
