process.env.SANDBOX_LOCAL_JS='false';
import test from 'node:test';import assert from 'node:assert/strict';import ts from 'typescript';import {readFileSync} from 'node:fs';import {pathToFileURL} from 'node:url';
const compile=s=>'data:text/javascript;base64,'+Buffer.from(ts.transpile(s,{module:ts.ModuleKind.ESNext,target:ts.ScriptTarget.ES2022})).toString('base64');
const contracts=compile(readFileSync('app/sandboxes/contracts.ts','utf8').replace("from 'zod'",`from '${pathToFileURL(process.cwd()+'/node_modules/zod/index.js')}'`));
let creates=0,mode='success',states=[];
const db={prepare(sql){let args;return {bind(...a){args=a;return this;},async first(){return {n:0};},async run(){if(sql.startsWith('UPDATE sandbox_sessions'))states.push(args[0]);return {meta:{changes:1}};}};}};
class OpenAISandboxError extends Error{}
globalThis.__sandboxFixture={env:{OPENAI_API_KEY:'test-key-not-real'},db,OpenAISandboxError,async runOpenAIProgram(program,input,uploads,key,model,onSession,onCleanupFailure){creates++;assert.equal(key,'test-key-not-real');assert.equal(model,'existing-model');if(mode==='provider-failure')throw new OpenAISandboxError('OPENAI_SANDBOX_ACCESS_REQUIRED');await onSession('sess_test');if(mode==='cleanup-pending')await onCleanupFailure('sess_test');return {ok:mode!=='execution-failure',stdout:'',stderr:'',result:{answer:42}};}};
let source=readFileSync('app/sandboxes/service.ts','utf8').replace("import {env} from '@/server/runtime';","const env=globalThis.__sandboxFixture.env;").replace("import {database,lock,unlock,aiKey,model} from '@/db/store';","const database=()=>globalThis.__sandboxFixture.db;const lock=async()=> 'lease';const unlock=async()=>{};const aiKey=()=>env.OPENAI_API_KEY;const model=()=> 'existing-model';").replace("import {getComponent,type AgentContext} from '@/app/components-registry/registry';","const getComponent=async()=>{throw Error('unused')};").replace("from './contracts'",`from '${contracts}'`).replace("import {e2bProvider} from './provider';","const e2bProvider={};").replace("import {runOpenAIProgram,OpenAISandboxError} from './openai-provider';","const {runOpenAIProgram,OpenAISandboxError}=globalThis.__sandboxFixture;");
const {runProgram,sandboxStatus}=await import(compile(source));const program={kind:'sandbox-program',language:'javascript',code:'export function main(input){return {answer:42}}'};
test('OpenAI code execution uses existing key independently of optional E2B desktop',async()=>{const r=await runProgram(program,{value:2},{userId:'alice'});assert.equal(r.result.answer,42);assert.equal(states.at(-1),'closed');assert.equal(sandboxStatus('alice').configured,true);assert.equal(sandboxStatus('alice').desktopConfigured,false);assert.equal(sandboxStatus('alice').provider,'openai');});
test('guest and wrong agent principals fail before provider allocation',async()=>{const before=creates;await assert.rejects(()=>runProgram(program,{}, {userId:'guest:123'}),/SIGN_IN_REQUIRED/);await assert.rejects(()=>runProgram(program,{}, {userId:'alice',agent:{ownerId:'bob'}}),/PRINCIPAL_MISMATCH/);assert.equal(creates,before);});
test('failed programs close the record and access errors stay actionable',async()=>{mode='execution-failure';assert.equal((await runProgram(program,{}, {userId:'alice'})).ok,false);mode='provider-failure';await assert.rejects(()=>runProgram(program,{}, {userId:'alice'}),/OPENAI_SANDBOX_ACCESS_REQUIRED/);assert.equal(states.at(-1),'closed');});
test('cleanup failures retain provider ID and pending state instead of claiming termination',async()=>{mode='cleanup-pending';assert.equal((await runProgram(program,{}, {userId:'alice'})).cleanupPending,true);assert.equal(states.at(-1),'cleanup_pending');});
