import {MAX_FILE_BYTES} from './contracts';
import {fileName} from '@/app/context-files/tree';
export type BinaryFile={bytes:Uint8Array;name:string;mime:string;exported?:boolean};
export async function boundedBytes(response:Response,max=MAX_FILE_BYTES){if(!response.ok)throw Error('File service rejected the request ('+response.status+').');if(Number(response.headers.get('content-length'))>max)throw Error('File exceeds the 10 MB transfer limit.');const reader=response.body?.getReader();if(!reader)return new Uint8Array();let n=0;const chunks:Uint8Array[]=[];try{for(;;){const part=await reader.read();if(part.done)break;n+=part.value.length;if(n>max)throw Error('File exceeds the transfer limit.');chunks.push(part.value);}}finally{await reader.cancel().catch(()=>{});}const bytes=new Uint8Array(n);let offset=0;for(const chunk of chunks){bytes.set(chunk,offset);offset+=chunk.length;}return bytes;}
const enc=encodeURIComponent;
const g='https://www.googleapis.com/drive/v3',m='https://graph.microsoft.com/v1.0/me/drive',a='https://adma.aisoup.net/api/v1';
export async function downloadBinary(space:string,id:string,token:string,transport:typeof fetch=fetch):Promise<BinaryFile>{
 const headers={Authorization:(space==='adma'?'Token ':'Bearer ')+token};
 const send=async(url:string,init:RequestInit={})=>{const r=await transport(url,{headers,redirect:'error',signal:AbortSignal.timeout(45000),...init});if(!r.ok)throw Error('File service rejected the request ('+r.status+').');return r;};
 const json=async(url:string,init?:RequestInit)=>await (await send(url,init)).json() as any;
 let exported=false;let name='',mime='application/octet-stream',response:Response;
 if(space==='google'){const meta=await json(g+'/files/'+enc(id)+'?fields=id,name,mimeType,size');name=meta.name;mime=meta.mimeType;const exports:Record<string,[string,string]>={'application/vnd.google-apps.document':['application/vnd.openxmlformats-officedocument.wordprocessingml.document','.docx'],'application/vnd.google-apps.spreadsheet':['application/vnd.openxmlformats-officedocument.spreadsheetml.sheet','.xlsx'],'application/vnd.google-apps.presentation':['application/vnd.openxmlformats-officedocument.presentationml.presentation','.pptx']};if(exports[mime]){exported=true;const format=exports[mime];mime=format[0];name+=format[1];response=await send(g+'/files/'+enc(id)+'/export?mimeType='+enc(mime));}else{if(mime.startsWith('application/vnd.google-apps.'))throw Error('This Google Workspace file cannot be exported by this transfer tool.');response=await send(g+'/files/'+enc(id)+'?alt=media');}}
 else if(space==='dropbox'){response=await send('https://content.dropboxapi.com/2/files/download',{method:'POST',headers:{...headers,'Dropbox-API-Arg':JSON.stringify({path:id})}});const meta=JSON.parse(response.headers.get('Dropbox-API-Result')||'{}');name=meta.name;mime=response.headers.get('content-type')||mime;}
 else if(space==='onedrive'){const meta=await json(m+'/items/'+enc(id)+'?$select=name,file,@microsoft.graph.downloadUrl');const url=new URL(meta['@microsoft.graph.downloadUrl']);if(url.protocol!=='https:'||url.username||url.password||!['.sharepoint.com','.1drv.com','.onedrive.com','.onedrive.live.com'].some(s=>url.hostname.endsWith(s)))throw Error('Unsupported OneDrive download host.');name=meta.name;mime=meta.file?.mimeType||mime;response=await send(url.href,{headers:{}});}
 else if(space==='adma'){const meta=await json(a+'/files/'+enc(id)+'/metadata/');name=meta.name||meta.file?.name;response=await send(a+'/files/'+enc(id)+'/download/');mime=response.headers.get('content-type')||mime;}
 else throw Error('Unsupported file provider.');
 return {bytes:await boundedBytes(response),name:fileName(name),mime,exported};
}
export async function uploadBinary(space:string,parent:string,file:BinaryFile,token:string,transport:typeof fetch=fetch){
 const name=fileName(file.name);if(file.bytes.length>MAX_FILE_BYTES)throw Error('File exceeds the 10 MB transfer limit.');let url='',method='POST',body:BodyInit;const headers:Record<string,string>={Authorization:(space==='adma'?'Token ':'Bearer ')+token};
 if(space==='google'){const boundary='wiki-'+crypto.randomUUID();headers['Content-Type']='multipart/related; boundary='+boundary;body=new Blob(['--'+boundary+'\r\nContent-Type: application/json; charset=UTF-8\r\n\r\n'+JSON.stringify({name,parents:[parent||'root']})+'\r\n--'+boundary+'\r\nContent-Type: '+file.mime.replace(/[\r\n]/g,'')+'\r\n\r\n',new Uint8Array(file.bytes),'\r\n--'+boundary+'--']);url='https://www.googleapis.com/upload/drive/v3/files?uploadType=multipart&fields=id,name';}
 else if(space==='dropbox'){url='https://content.dropboxapi.com/2/files/upload';headers['Content-Type']='application/octet-stream';headers['Dropbox-API-Arg']=JSON.stringify({path:(parent==='root'?'':parent)+'/'+name,mode:'add',autorename:false,strict_conflict:true,mute:false});body=new Uint8Array(file.bytes);}
 else if(space==='onedrive'){url=m+(parent&&parent!=='root'?'/items/'+enc(parent):'/root')+':/'+enc(name)+':/content?@microsoft.graph.conflictBehavior=fail';method='PUT';headers['Content-Type']=file.mime;body=new Uint8Array(file.bytes);}
 else if(space==='adma'){url=a+'/files/upload/';const form=new FormData();form.set('is_public','false');if(parent)form.set('folder_id',parent);form.append('files',new Blob([new Uint8Array(file.bytes)],{type:file.mime}),name);body=form;}
 else throw Error('Unsupported file provider.');
 const response=await transport(url,{method,headers,body,redirect:'error',signal:AbortSignal.timeout(60000)});if(!response.ok)throw Error('Upload failed ('+response.status+'). No overwrite was requested.');const result=await response.json() as any;if(space==='adma'&&(!result.files?.length||result.rejected_count))throw Error('ADMA rejected this file type. No file was copied.');return space==='adma'?{files:result.files.map((f:any)=>({id:f.id,name:f.name}))}:{id:result.id,name:result.name,size:result.size};
}
