'use client';
import {useEffect,useRef,useState} from 'react';
import {useUi} from '@/app/i18n/client';
import type {Mention,Resource} from './contracts';
import {resourceKey} from './contracts';
import './style.css';
export function ResourcePicker({pageId,onClose,onSelect,initialQuery='',copyMode=false,initialSources=[]}:{pageId:string;onClose:()=>void;onSelect?:(items:Mention[])=>void;initialQuery?:string;copyMode?:boolean;initialSources?:Resource[]}){
 const {t}=useUi(),[roots,setRoots]=useState<Resource[]>([]),[trail,setTrail]=useState<Resource[]>([]),[items,setItems]=useState<Resource[]>([]),[selected,setSelected]=useState<Mention[]>(initialSources.map(resource=>({type:'resource',resource}))),[query,setQuery]=useState(initialQuery),[cursor,setCursor]=useState<string|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[destination,setDestination]=useState(false),[result,setResult]=useState<any>(null);
 const operation=useRef<{signature:string;id:string}|null>(null);
 const panel=useRef<HTMLDivElement>(null),search=useRef<HTMLInputElement>(null),seq=useRef(0),active=trail.at(-1),endpoint='/api/pages/'+pageId+'/resources';
 useEffect(()=>{const c=new AbortController();fetch(endpoint,{signal:c.signal}).then(async r=>{const d=await r.json() as any;if(!r.ok)throw Error(d.error);setRoots(d.roots);}).catch(e=>{if(!c.signal.aborted)setError(String(e));});if(!copyMode)void browse([{space:'page',id:'',kind:'folder',name:t('Page files')}],false,true);search.current?.focus();return()=>c.abort();},[endpoint]);
 useEffect(()=>{const dismiss=(e:KeyboardEvent)=>{if(e.key==='Escape'){e.preventDefault();e.stopPropagation();onClose();}if(e.key==='Tab'){const nodes=panel.current?.querySelectorAll<HTMLElement>('button:not(:disabled),input,select,[tabindex="0"]');if(!nodes?.length)return;const first=nodes[0],last=nodes[nodes.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}}};window.addEventListener('keydown',dismiss);return()=>window.removeEventListener('keydown',dismiss);},[onClose,busy]);
 async function browse(next:Resource[],more=false,preserveQuery=false){const version=++seq.current;setTrail(next);setBusy(true);setError('');if(!more){setItems([]);if(!preserveQuery)setQuery('');setCursor(null);}try{const folder=next.at(-1);if(!folder){setItems([]);return;}const r=await fetch(endpoint+'?'+new URLSearchParams({folder:JSON.stringify(folder),...(more&&cursor?{cursor}:{})})),d=await r.json() as any;if(!r.ok)throw Error(d.error);if(seq.current!==version)return;setItems(old=>more?[...old,...d.items]:d.items);setCursor(d.next);}catch(e){if(seq.current===version)setError(String(e));}finally{if(seq.current===version)setBusy(false);}}
 const key=(m:Mention)=>m.type==='resource'?resourceKey(m.resource):m.type==='tool'?m.connectorId+':'+m.name:m.id;
 function toggle(m:Mention){setSelected(old=>old.some(x=>key(x)===key(m))?old.filter(x=>key(x)!==key(m)):old.length<30?[...old,m]:old);}
 function chooseDestination(){setSelected(old=>old.filter(m=>m.type==='resource'));setDestination(true);setTrail([]);setQuery('');setError('');}
 async function copy(){if(!active)return;setBusy(true);setError('');try{const sources=selected.filter(m=>m.type==='resource').map(m=>(m as {resource:Resource}).resource),signature=JSON.stringify({sources,destination:active});if(operation.current?.signature!==signature)operation.current={signature,id:crypto.randomUUID()};const r=await fetch(endpoint,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({operationId:operation.current.id,sources,destination:active})}),d=await r.json() as any;if(!r.ok)throw Error(d.error);setResult(d);window.dispatchEvent(new CustomEvent('page-files-changed',{detail:{pageId}}));}catch(e){setError(String(e));}finally{setBusy(false);}}
 const shown=(active?items:roots).filter(r=>(!destination||r.kind==='folder')&&r.name.toLocaleLowerCase().includes(query.toLocaleLowerCase()));
 return <div className="resource-picker-overlay" onMouseDown={e=>{if(e.target===e.currentTarget)onClose();}}><div className="resource-picker" ref={panel} role="dialog" aria-modal="true" aria-label={t(destination?'Choose destination':'Files and folders')}>
 <header><strong>{t(destination?'Choose destination':'Files and folders')}</strong><button type="button" onClick={onClose} aria-label={t('Close')}>×</button></header>
 <input ref={search} aria-label={t('Search resources')} placeholder={t('Search resources')} value={query} onChange={e=>setQuery(e.target.value)} onKeyDown={e=>{if(e.key==='ArrowDown'){e.preventDefault();panel.current?.querySelector<HTMLElement>('.resource-row button')?.focus();}}}/>
 <><nav className="resource-breadcrumb"><button type="button" onClick={()=>void browse([])}>{t('All sources')}</button>{trail.map((r,i)=><button type="button" key={i} onClick={()=>void browse(trail.slice(0,i+1))}>/ {r.name}</button>)}</nav>{active&&!destination&&<button type="button" onClick={()=>toggle({type:'resource',resource:active})}>{t('Select this folder')}</button>}<div className="resource-list" role="listbox" aria-label={t('Files and folders')} aria-multiselectable={!destination}>{shown.map(r=><div className="resource-row" key={resourceKey(r)}><button type="button" disabled={busy} role="option" aria-selected={selected.some(m=>m.type==='resource'&&resourceKey(m.resource)===resourceKey(r))} onClick={()=>r.kind==='folder'?void browse([...trail,r]):toggle({type:'resource',resource:r})}>{r.kind==='folder'?'▸':'▤'} {r.name}<small>{r.space}</small></button>{!destination&&<button type="button" aria-label={t('Select')+' '+r.name} aria-pressed={selected.some(m=>m.type==='resource'&&resourceKey(m.resource)===resourceKey(r))} onClick={()=>toggle({type:'resource',resource:r})}>＋</button>}</div>)}{!busy&&!shown.length&&<p>{t('No items found.')}</p>}{cursor&&<button type="button" disabled={busy} onClick={()=>void browse(trail,true)}>{t('Load more')}</button>}</div></>
 {!!selected.length&&<div className="resource-selected">{selected.map(m=><button type="button" key={key(m)} disabled={busy} onClick={()=>toggle(m)}>{m.type==='resource'?m.resource.name:m.name} ×</button>)}</div>}
 {busy&&<p role="status">{t('Working…')}</p>}{error&&<p role="alert">{error}</p>}{result&&<div role="status"><p>{t(result.state==='complete'?'Copy complete':'Copy partially completed')} · {result.copied?.length||0} {t('Copied')} · {result.failed?.length||0} {t('Failed')}</p>{result.failed?.map((f:any,i:number)=><p key={i}>{f.source?.name}: {f.error}</p>)}</div>}
 <footer>{copyMode&&<small>{t('Copy limits: 10 MB per file, 100 MB and 200 items per operation.')}</small>}<div>{destination?<><button type="button" disabled={busy} onClick={()=>{setDestination(false);setResult(null);}}>{t('Back')}</button><button type="button" disabled={busy||!active||!!result||!selected.length||active.space==='adma'&&active.id==='third-party'} onClick={()=>void copy()}>{t('Copy here')}</button></>:<>{copyMode&&<button type="button" disabled={busy||!selected.some(m=>m.type==='resource')} onClick={chooseDestination}>{t('Copy to…')}</button>}{onSelect&&<button type="button" disabled={busy||!selected.length} onClick={()=>{onSelect(selected);onClose();}}>{t('Mention selected')}</button>}</>}</div></footer>
 </div></div>;
}
