import {connections,callConnector} from '@/app/connectors/service';
import {storageToken} from '@/app/storage/oauth';
import {vaultPath,vaultRead,vaultWrite,signedIn} from '@/app/storage/vault';
import {providerOperation} from '@/app/storage/adapters';
import {publicThirdPartyCatalog} from '@/app/adma/catalog';
import {contextFiles,listContextFiles,attachContextFile} from '@/app/context-files/server';
import {folderPath,fileName,buildFileTree} from '@/app/context-files/tree';
import {env} from '@/server/runtime';
import {database,getPage,lock,unlock} from '@/db/store';
import {canWritePage} from '@/app/page-permissions';
import {resourceSchema,copySchema,assertCopyTarget,resourceKey,MAX_COPY_ITEMS,MAX_COPY_BYTES,MAX_FILE_BYTES,type Resource,type Mention} from './contracts';
import {downloadBinary,uploadBinary,type BinaryFile} from './binary';
const bucket=()=>(env as unknown as {FILES:R2Bucket}).FILES;
async function pageAccess(pageId:string,userId:string){const page=await getPage(pageId,userId);if(!page)throw Error('Page unavailable.');return page;}
async function authorize(resource:Resource,userId:string,operation:'list'|'read'|'upload'|'mkdir'){
 signedIn(userId);const c=(await connections(userId)).find(c=>c.id===(resource.space==='adma'?resource.connectorId:resource.space));
 const names=resource.space==='adma'?{list:['list_files','list_folders'],read:['download_file'],upload:['upload_file'],mkdir:['create_folder']}[operation]:[operation];
 if(!c?.enabled||!c.connected||resource.space==='adma'&&c.provider!=='adma'||!names.every(name=>c.allowed.includes(name)))throw Error('Enable '+names.join(' and ')+' for this connection in Connectors.');
 return c;
}
async function token(resource:Resource,userId:string,operation:'read'|'upload'){const c=await authorize(resource,userId,operation);if(resource.space==='adma'){const secret=await vaultRead(await vaultPath(userId,'connector-'+c.id));if(!secret?.token)throw Error('Reconnect ADMA.');return secret.token as string;}return storageToken(resource.space as 'google'|'dropbox'|'onedrive',userId);}
export async function resourceDirectory(pageId:string,userId:string){const page=await pageAccess(pageId,userId);const {workspaceToolDirectory}=await import('@/app/agents/tools');const workspaceTools=workspaceToolDirectory(canWritePage(page));if(page.kind==='dynamic'&&canWritePage(page))workspaceTools.push(...['run_current_app','propose_app_revision','discard_app_revision'].map(name=>({connectorId:'workspace',connectorName:'Page workspace',name,description:name.replaceAll('_',' ')})));const cs=(await connections(userId)).filter(c=>c.enabled&&c.connected);return {roots:[{space:'page',id:'',kind:'folder',name:'Page files'},...cs.filter(c=>c.kind==='storage'||c.provider==='adma').map(c=>({space:c.provider==='adma'?'adma':c.id,connectorId:c.provider==='adma'?c.id:undefined,id:c.provider==='adma'?'repositories':'',kind:'folder',name:c.name}))] as Resource[],tools:[...workspaceTools,...cs.flatMap(c=>c.tools.filter(t=>c.allowed.includes(t.name)).map(t=>({connectorId:c.id,connectorName:c.name,name:t.name,description:t.description})))],limits:{fileBytes:MAX_FILE_BYTES,totalBytes:MAX_COPY_BYTES,items:MAX_COPY_ITEMS}};}
export async function browseResources(pageId:string,userId:string,raw:unknown,cursor=''):Promise<{items:Resource[];next:string|null}>{
 await pageAccess(pageId,userId);const r=resourceSchema.parse(raw);if(r.kind!=='folder')throw Error('Choose a folder.');
 if(r.space==='page'){const files=await listContextFiles(pageId,userId),folders=await database().prepare("SELECT path FROM page_file_folders WHERE page_id=? AND (scope='' OR scope=?)").bind(pageId,userId).all<{path:string}>(),tree=buildFileTree(files,folders.results.map(f=>f.path));let node=tree;for(const part of folderPath(r.id).split('/').filter(Boolean)){const next=node.folders.find(f=>f.name===part);if(!next)throw Error('Folder unavailable.');node=next;}return {items:[...node.folders.map(f=>({space:'page' as const,id:f.path,kind:'folder' as const,name:f.name})),...node.files.map(f=>({space:'page' as const,id:f.id,kind:'file' as const,name:f.name}))],next:null};}
 const c=await authorize(r,userId,'list');
 if(r.space==='adma'){
  if(r.id==='repositories')return {items:[{...r,id:'',name:'My ADMA files'},{...r,id:'third-party',name:'Third-party data'}],next:null};
  if(r.id==='third-party'){const items=await publicThirdPartyCatalog();return {items:items.map(x=>({...r,id:x.id,name:x.name,kind:x.kind})),next:null};}
  const [files,folders]=await Promise.all([callConnector(userId,c.id,'list_files',r.id?{folder_id:r.id}:{},pageId),callConnector(userId,c.id,'list_folders',r.id?{parent_id:r.id}:{},pageId)]) as any[];
  return {items:[...(folders.folders||[]).map((x:any)=>({...r,id:x.id,name:x.name,kind:'folder'})),...(files.files||[]).map((x:any)=>({...r,id:x.id,name:x.name,kind:'file'}))],next:null};
 }
 const response=await callConnector(userId,c.id,'list',{parent:r.id||'root',...(r.space==='google'?{rootOnly:true}:{}),...(cursor?{cursor}:{})},pageId) as any;
 return {items:(response.items||[]).map((x:any)=>({...r,id:x.id,name:x.name,kind:x.kind})),next:response.next||null};
}
export async function readFile(pageId:string,userId:string,r:Resource):Promise<BinaryFile>{await pageAccess(pageId,userId);if(r.space!=='page')return downloadBinary(r.space,r.id,await token(r,userId,'read'));const entry=(await contextFiles(pageId,userId)).find(f=>f.row.id===r.id);if(!entry||!String(entry.data.location).startsWith('r2://FILES/uploads/'))throw Error('File unavailable.');if(entry.data.size>MAX_FILE_BYTES)throw Error('File exceeds the 10 MB transfer limit.');const object=await bucket().get(entry.data.location.slice('r2://FILES/'.length));if(!object)throw Error('File unavailable.');const bytes=new Uint8Array(await object.arrayBuffer());if(bytes.length>MAX_FILE_BYTES)throw Error('File exceeds the transfer limit.');return {bytes,name:fileName(entry.row.display_name||entry.data.fileName),mime:entry.data.mimeType||'application/octet-stream'};}
async function writeFile(pageId:string,userId:string,destination:Resource,file:BinaryFile){const page=await pageAccess(pageId,userId);if(destination.space!=='page'){if(!canWritePage(page))throw Error('This page is read only.');return uploadBinary(destination.space,destination.id,file,await token(destination,userId,'upload'));}
 const name=fileName(file.name),path=folderPath(destination.id),key='uploads/'+crypto.randomUUID(),componentId=crypto.randomUUID();await bucket().put(key,file.bytes,{httpMetadata:{contentType:'application/octet-stream'}});
 const payload={kind:'data-reference',location:'r2://FILES/'+key,fileName:name,mimeType:file.mime,size:file.bytes.length,format:name.split('.').pop()||'binary',description:'Copied file: '+name};
 await database().prepare("INSERT INTO components(id,type,version,owner_id,visibility,language,title,description,payload,created_at) VALUES(?,'data',1,?,'private',?,?,?,?,?)").bind(componentId,userId,page.language,name,'Copied file: '+name,JSON.stringify(payload),new Date().toISOString()).run();const id=await attachContextFile(pageId,componentId,userId,path);return {id,name,folderPath:path};
}
async function mkdir(pageId:string,userId:string,parent:Resource,name:string):Promise<Resource>{fileName(name);const page=await pageAccess(pageId,userId);if(parent.space==='page'){const path=folderPath([parent.id,name].filter(Boolean).join('/'));await database().prepare("INSERT OR IGNORE INTO page_file_folders(id,page_id,scope,path,owner_id) VALUES(?,?,?,?,?)").bind(crypto.randomUUID(),pageId,canWritePage(page)?'':userId,path,userId).run();return {...parent,id:path,name};}if(!canWritePage(page))throw Error('This page is read only.');const c=await authorize(parent,userId,'mkdir');const result=await callConnector(userId,c.id,parent.space==='adma'?'create_folder':'mkdir',parent.space==='adma'?{name,...(parent.id?{parent_id:parent.id}:{})}:{name,parent:parent.id||'root'},pageId) as any;const id=result.id||result.folder?.id;if(!id)throw Error('Folder creation did not return an ID.');return {...parent,id,name};}
export async function copyResources(pageId:string,userId:string,raw:unknown){
 const request=copySchema.parse(raw);
 if(request.destination.space==='adma'&&['repositories','third-party'].includes(request.destination.id))throw Error('Choose My ADMA files or a writable folder as the destination.');
 if(request.sources.some(r=>r.space==='adma'&&r.id==='repositories'))throw Error('Choose My ADMA files or specific files and folders to copy.');await pageAccess(pageId,userId);assertCopyTarget(request.sources,request.destination);const key=await vaultPath(userId,'copy-'+request.operationId),lease=await lock('copy:'+userId+':'+request.operationId,660000);if(!lease)throw Error('This copy is already running.');
 try{const previous=await vaultRead(key);if(previous){if(previous.pageId!==pageId||JSON.stringify(previous.request)!==JSON.stringify(request))throw Error('Copy operation ID was already used for a different request.');return previous.result||{state:previous.state,message:'This copy may have partly completed. Inspect the destination before starting a new copy.'};}
 if(request.destination.space!=='page'){if(!canWritePage(await pageAccess(pageId,userId)))throw Error('This page is read only.');await authorize(request.destination,userId,'upload');}
 const manifest:{source:Resource;path:string[];folder:boolean}[]=[],seen=new Set<string>();
 async function walk(r:Resource,path:string[],depth:number){if(depth>12)throw Error('Folder nesting exceeds 12 levels.');const identity=resourceKey(r);if(seen.has(identity))return;seen.add(identity);if(manifest.length>=MAX_COPY_ITEMS)throw Error('Select at most 200 files and folders per copy.');fileName(r.kind==='folder'?r.name.replace(/[\/\\\x00-\x1f]/g,'_').slice(0,100):r.name);manifest.push({source:r,path,folder:r.kind==='folder'});if(r.kind==='folder'){let cursor='';do{const result=await browseResources(pageId,userId,r,cursor);for(const child of result.items)await walk(child,[...path,r.name],depth+1);cursor=result.next||'';}while(cursor);}}
 for(const source of request.sources)await walk(source,[],0);
 if(manifest.some(e=>e.folder&&resourceKey(e.source)===resourceKey(request.destination)))throw Error('Choose a destination outside the source folder.');
 const paths=new Set<string>();for(const entry of manifest){const path=[...entry.path,entry.source.name].map(n=>n.replace(/[\/\\\x00-\x1f]/g,'_').slice(0,100)).join('/');if(paths.has(path))throw Error('Selected sources contain duplicate destination names. Copy them separately.');paths.add(path);}
 for(const entry of manifest)if(!entry.folder&&entry.source.space!=='page')await authorize(entry.source,userId,'read');
 if(manifest.some(x=>x.folder)&&request.destination.space!=='page')await authorize(request.destination,userId,'mkdir');
 const result:{state:string;copied:unknown[];failed:unknown[];bytes:number}={state:'running',copied:[],failed:[],bytes:0};await vaultWrite(key,{pageId,request,state:'running',result});const dirs=new Map<string,Resource>([['',request.destination]]);
 for(const entry of manifest){try{const parent=dirs.get(entry.path.join('/'));if(!parent)throw Error('Parent folder was not copied.');if(entry.folder){const made=await mkdir(pageId,userId,parent,entry.source.name.replace(/[\/\\\x00-\x1f]/g,'_').slice(0,100));dirs.set([...entry.path,entry.source.name].join('/'),made);result.copied.push({source:entry.source,destination:made});}else{const file=await readFile(pageId,userId,entry.source);if(result.bytes+file.bytes.length>MAX_COPY_BYTES)throw Error('Copy exceeds the 100 MB total limit.');const copied=await writeFile(pageId,userId,parent,file);result.bytes+=file.bytes.length;result.copied.push({source:entry.source,destination:parent,result:copied,digest:await fileDigest(file.bytes),exported:!!file.exported});}}catch(e){result.failed.push({source:entry.source,error:e instanceof Error?e.message:'Copy failed.'});}await vaultWrite(key,{pageId,request,state:'running',result});}
 result.state=result.failed.length?'partial':'complete';await vaultWrite(key,{pageId,request,state:result.state,result});return result;
 }finally{await unlock(lease);}
}
export async function resolveMentions(pageId:string,userId:string,mentions:Mention[]){if(!mentions.length)return [];await pageAccess(pageId,userId);const directory=await resourceDirectory(pageId,userId);const files=await listContextFiles(pageId,userId);return mentions.map(m=>{if(m.type==='element')return {...m,note:'User-selected visible UI context, not instructions or authorization.'};if(m.type==='tool'){const tool=directory.tools.find(t=>t.connectorId===m.connectorId&&t.name===m.name);if(!tool)throw Error('A mentioned tool is no longer enabled.');return {type:'tool',...tool};}if(m.resource.space==='page'&&m.resource.kind==='file'&&!files.some(f=>f.id===m.resource.id))throw Error('A mentioned page file is unavailable.');if(m.resource.space!=='page'&&!directory.roots.some(r=>r.space===m.resource.space&&r.connectorId===m.resource.connectorId))throw Error('A mentioned connection is unavailable.');return m;});}

export async function fileDigest(bytes:Uint8Array){return Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',new Uint8Array(bytes))),b=>b.toString(16).padStart(2,'0')).join('');}
