'use client';
import {geoFileHref} from '@/app/tools/sources';
import {canWritePage} from '@/app/page-permissions';
import {TransferActions} from '@/app/resources/actions';
import {GeoViewer} from '@/app/geo/viewer';
import {useUi} from '@/app/i18n/client';
import {StorageProposal} from '@/app/storage/panel';
import {useState} from 'react';import type {AnswerPage} from '@/app/page-types';import {FileBrowser} from '@/app/templates/file-browser';import {Dashboard} from '@/app/templates/dashboard';import type {ChartDataset} from '@/app/components-registry/chart-contracts';
export function ProgramView({page,onResult}:{page:AnswerPage;onResult:(p:AnswerPage)=>void}){
 const {t,locale}=useUi();
const [values,setValues]=useState<Record<string,string|number>>(()=>Object.fromEntries(Object.entries(page.parameters||{}).filter((entry):entry is [string,string|number]=>typeof entry[1]==='string'||typeof entry[1]==='number'))),[busy,setBusy]=useState(false),[error,setError]=useState('');const v=page.view;const zh=page.language.startsWith('zh');async function run(input:unknown){setBusy(true);setError('');try{const r=await fetch('/api/pages/'+page.id+'/run',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(input)}),d=await r.json() as {page:AnswerPage;error?:string};if(!r.ok)throw Error(d.error);onResult(d.page);}catch(e){setError(String(e));}finally{setBusy(false);}}
 return <section className="program-view">{page.runtimePending&&<p role="status">{t("Loading…")}</p>}<button disabled={busy||page.runtimePending} onClick={()=>void run({query:page.parameters?.query,values:{...page.parameters,...values}})}>{busy||page.runtimePending?'…':t("Refresh")}</button>{v?.map&&<GeoViewer key={JSON.stringify(v.map)} embedded source={{page:page.id,language:page.language}} initialData={v.map.geojson} initialTitle={v.map.title}/>} {v?.files&&<FileBrowser fileHref={file=>{const r=v.files?.find(f=>f.id===file.id)?.resource;return r?geoFileHref(page.id,r,page.language):undefined;}} renderActions={file=>{const resource=v.files?.find(f=>f.id===file.id)?.resource;return resource?<TransferActions pageId={page.id} resource={resource} canMove={canWritePage(page)}/>:null;}} items={v.files} title={v.title} language={page.language} onFolder={id=>void run({parent:id})}/>} {v?.next&&<button disabled={busy} onClick={()=>void run({cursor:v.next})}>{t("Next page")}</button>}{v?.chart&&!!v.dataset&&<Dashboard chart={v.chart} dataset={v.dataset as ChartDataset} tableFirst={v.templateId==='table-v1'}/>} {v?.form&&<form onSubmit={e=>{e.preventDefault();void run({submitted:true,query:page.parameters?.query,values:{...page.parameters,...values}});}}>{v.form.fields.map(f=><label key={f.name}>{f.label}<input required type={f.type==='number'?'number':'text'} step="any" value={values[f.name]??''} onChange={e=>setValues({...values,[f.name]:f.type==='number'?Number(e.target.value):e.target.value})}/></label>)}<button disabled={busy}>{v.form.submit}</button></form>}{v?.results&&<dl>{Object.entries(v.results).map(([k,value])=><div key={k}><dt>{v.form?.outputs.find(o=>o.name===k)?.label||k}</dt><dd>{String(value)}</dd></div>)}</dl>}{page.proposals?.map(p=><StorageProposal key={p.actionId} {...p}/>)}{error&&<p role="status">{t(error)}</p>}</section>;}
