import {z} from 'zod';
import {arcgisToken} from './oauth';
import {arcgisServiceUrl} from './tools';
import {resourceSchema} from '@/app/resources/contracts';
import {boundedBytes} from '@/app/resources/binary';
import {readFile} from '@/app/resources/service';
import {getPage} from '@/db/store';
import {canWritePage} from '@/app/page-permissions';
import {normalizeGeoJSON,csvGeoJSON} from '@/app/geo/data';
import {webMap} from '@/app/arcgis-publisher/publish';
const id=z.string().regex(/^[a-f0-9]{32}$/i),root='https://www.arcgis.com/sharing/rest';
export async function executeArcgis(userId:string,tool:string,raw:unknown,currentPage?:string){const {token,username}=await arcgisToken(userId),user='content/users/'+encodeURIComponent(username);
 async function request(path:string,args:Record<string,string|Blob>={}){const url=path.startsWith('https:')?path:root+'/'+path;const body=new FormData();body.set('f','json');body.set('token',token);for(const [k,v] of Object.entries(args))body.set(k,v);const r=await fetch(url,{method:'POST',redirect:'error',body,signal:AbortSignal.timeout(45000)});const text=new TextDecoder().decode(await boundedBytes(r,4*1024*1024));const d=JSON.parse(text.split(token).join('[redacted]')); if(!r.ok||d.error)throw Error(String(d.error?.message||'ArcGIS request failed.').split(token).join('[redacted]'));return d;}
 const item=(itemId:string)=>request('content/items/'+id.parse(itemId));const links=(itemId:string)=>({itemUrl:'https://www.arcgis.com/home/item.html?id='+itemId,mapUrl:'https://www.arcgis.com/apps/mapviewer/index.html?webmap='+itemId});
 if(tool==='get_account'){z.object({}).strict().parse(raw);const me=await request('community/self');return {username:me.username,fullName:me.fullName,orgId:me.orgId,role:me.role,privileges:me.privileges};}
 if(tool==='search_items'){const d=z.object({query:z.string().min(1).max(2000),start:z.number().int().min(1).max(10000).default(1),num:z.number().int().min(1).max(50).default(20)}).strict().parse(raw);return request('search',{q:d.query,start:String(d.start),num:String(d.num)});}
 if(tool==='get_item'){const d=z.object({itemId:id,includeData:z.boolean().default(false)}).strict().parse(raw),metadata=await item(d.itemId);return {metadata,...links(d.itemId),...(d.includeData?{data:await request('content/items/'+d.itemId+'/data')}:{})};}
 if(tool==='get_layer'){const d=z.object({itemId:id,layerId:z.number().int().min(0)}).strict().parse(raw),m=await item(d.itemId);if(m.type!=='Feature Service')throw Error('Choose a Feature Service item.');return request(arcgisServiceUrl(m.url)+'/'+d.layerId);}
 if(tool==='query_layer'){const d=z.object({itemId:id,layerId:z.number().int().min(0),where:z.string().max(4000).default('1=1'),outFields:z.string().max(2000).default('*'),offset:z.number().int().min(0).default(0),count:z.number().int().min(1).max(200).default(100)}).strict().parse(raw),m=await item(d.itemId);if(m.type!=='Feature Service')throw Error('Choose a Feature Service item.');return request(arcgisServiceUrl(m.url)+'/'+d.layerId+'/query',{where:d.where,outFields:d.outFields,resultOffset:String(d.offset),resultRecordCount:String(d.count),outSR:'4326',returnGeometry:'true'});}
 if(tool==='publication_status'){const d=z.object({itemId:id,jobId:z.string().max(200).optional()}).strict().parse(raw);return {...await request(user+'/items/'+d.itemId+'/status',{jobType:'publish',...(d.jobId?{jobId:d.jobId}:{})}),...links(d.itemId)};}
 if(tool==='create_web_map'){const d=z.object({title:z.string().trim().min(1).max(200),layerItemIds:z.array(id).min(1).max(10)}).strict().parse(raw);const map=webMap(d.title,'','',[]);for(const itemId of d.layerItemIds){const m=await item(itemId);if(m.type!=='Feature Service')throw Error('Each layer item must be a Feature Service.');const url=arcgisServiceUrl(m.url),service=await request(url);if(!service.layers?.length)throw Error('Feature service has no layers.');map.operationalLayers.push(...webMap(m.title,itemId,url,service.layers).operationalLayers);}const saved=await request(user+'/addItem',{type:'Web Map',title:d.title,tags:'AgenticWiKi',text:JSON.stringify(map)});if(!saved.id)throw Error('ArcGIS did not return a map ID.');return {itemId:saved.id,access:'private',...links(saved.id)};}
 if(tool==='publish_file'){const d=z.object({pageId:z.string().uuid(),resource:resourceSchema}).strict().parse(raw);if(currentPage&&currentPage!==d.pageId)throw Error('Use the current page for publishing.');const page=await getPage(d.pageId,userId);if(!page||!canWritePage(page))throw Error('Publishing requires an editable page.');let file=await readFile(d.pageId,userId,d.resource);if(d.resource.space==='adma'&&/\.shp$/i.test(file.name)){const {callConnector}=await import('@/app/connectors/service');const metadata=await callConnector(userId,d.resource.connectorId!,'file_metadata',{file_id:d.resource.id},d.pageId) as any;const layer=String(metadata.geoserver_layer_name||'');if(!/^[A-Za-z0-9_.-]+$/.test(layer))throw Error('Select a complete shapefile ZIP; this ADMA file has no published geometry service.');const url='https://adma.aisoup.net/geoserver/ows?'+new URLSearchParams({service:'WFS',version:'1.0.0',request:'GetFeature',outputFormat:'application/json',typeName:layer});const response=await fetch(url,{redirect:'error',signal:AbortSignal.timeout(30000)});file={...file,bytes:await boundedBytes(response),name:file.name.replace(/\.shp$/i,'.geojson')};}let blob:Blob,type:string,filetype:string;if(/\.zip$/i.test(file.name)){blob=new Blob([file.bytes as BlobPart]);type='Shapefile';filetype='shapefile';}else if(/\.(geojson|json|csv|tsv)$/i.test(file.name)){const text=new TextDecoder().decode(file.bytes),data=/\.(csv|tsv)$/i.test(file.name)?csvGeoJSON(text):normalizeGeoJSON(JSON.parse(text));blob=new Blob([JSON.stringify(data)],{type:'application/geo+json'});type='GeoJson';filetype='geojson';}else throw Error('Use GeoJSON, coordinate CSV/TSV, or a complete zipped shapefile.');const added=await request(user+'/addItem',{type,title:file.name,tags:'AgenticWiKi',file:new File([blob],filetype==='geojson'?'data.geojson':'data.zip')});if(!added.id)throw Error('Source upload did not return an ID; inspect ArcGIS Content before retrying.');try{const published=await request(user+'/publish',{itemID:added.id,filetype,publishParameters:JSON.stringify({name:'wiki_'+crypto.randomUUID().replaceAll('-','')})});return {sourceItemId:added.id,services:published.services,state:'submitted',sourceUrl:links(added.id).itemUrl,instruction:'Check publication_status before creating a Web Map. Items are private.'};}catch{return {sourceItemId:added.id,state:'uncertain',sourceUrl:links(added.id).itemUrl,instruction:'Source uploaded, but publication could not be confirmed. Inspect ArcGIS Content before retrying; do not upload again automatically.'};}}
 throw Error('Unknown ArcGIS tool.');
}
