import {createHash,randomBytes} from 'node:crypto';
import {vaultPath,vaultRead,vaultWrite,vaultDelete,vaultReady,signedIn,setting} from '@/app/storage/vault';
import {database,lock,unlock} from '@/db/store';
import {safeReturnTo,validateOAuthState} from '@/app/connections/google-drive/crypto';
import {arcgisTools} from './tools';
const root='https://www.arcgis.com/sharing/rest';
export async function arcgisStatus(userId:string){const configured=!!setting('ARCGIS_CLIENT_ID')&&vaultReady(),saved=configured&&!userId.startsWith('guest:')?await vaultRead(await vaultPath(userId,'arcgis')):null;return {configured,connected:!!saved&&saved.ownerId===userId&&saved.refreshExpires>Date.now(),username:saved?.ownerId===userId?saved.username:undefined};}
export async function beginArcgis(userId:string,origin:string,returnTo:unknown){signedIn(userId);if(!(await arcgisStatus(userId)).configured)throw Error('ArcGIS OAuth is not configured.');const state=crypto.randomUUID(),verifier=randomBytes(32).toString('base64url'),redirect=(process.env.APP_URL||origin)+'/api/connectors/arcgis/callback';await vaultWrite(await vaultPath(userId,'arcgis-state-'+state),{ownerId:userId,verifier,redirect,returnTo:safeReturnTo(returnTo),expires:Date.now()+600000});const url=new URL(root+'/oauth2/authorize');url.search=new URLSearchParams({client_id:setting('ARCGIS_CLIENT_ID'),response_type:'code',redirect_uri:redirect,state,code_challenge:createHash('sha256').update(verifier).digest('base64url'),code_challenge_method:'S256',expiration:'120'}).toString();return {state,url:url.href};}
async function exchange(values:Record<string,string>){const r=await fetch(root+'/oauth2/token',{method:'POST',redirect:'error',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams({f:'json',client_id:setting('ARCGIS_CLIENT_ID'),...values}),signal:AbortSignal.timeout(20000)});const d=await r.json() as any;if(!r.ok||d.error||!d.access_token)throw Error('Reconnect ArcGIS in Connectors.');return d;}
export async function finishArcgis(userId:string,state:string,cookie:string,code:string,cancelled:boolean){signedIn(userId);if(!/^[a-f0-9-]{36}$/.test(state)||state!==cookie)throw Error('Invalid ArcGIS OAuth state.');const lease=await lock('arcgis-oauth:'+state,60000);if(!lease)throw Error('OAuth request already used.');try{const path=await vaultPath(userId,'arcgis-state-'+state),pending=await vaultRead(path);validateOAuthState(pending,userId,state,cookie);await vaultDelete(path);if(cancelled)return pending.returnTo;const t=await exchange({grant_type:'authorization_code',code,code_verifier:pending.verifier,redirect_uri:pending.redirect});if(!t.refresh_token||!t.username)throw Error('ArcGIS did not return a refreshable user session.');await vaultWrite(await vaultPath(userId,'arcgis'),{ownerId:userId,username:t.username,accessToken:t.access_token,refreshToken:t.refresh_token,expires:Date.now()+t.expires_in*1000,refreshExpires:Date.now()+(t.refresh_token_expires_in||1209600)*1000});const names=arcgisTools.map(t=>t.name);await database().prepare("INSERT INTO user_connectors(id,owner_id,name,kind,url,enabled,tools,allowed,automatic) VALUES('arcgis',?,'ArcGIS Online','api','api:arcgis',1,?,?,?) ON CONFLICT(owner_id,id) DO UPDATE SET enabled=1,revision=user_connectors.revision+1").bind(userId,JSON.stringify(arcgisTools),JSON.stringify(names),JSON.stringify(names)).run();return pending.returnTo;}finally{await unlock(lease);}}
export async function arcgisToken(userId:string){signedIn(userId);const path=await vaultPath(userId,'arcgis'),lease=await lock('arcgis-token:'+userId,30000);if(!lease)throw Error('ArcGIS connection is busy. Retry shortly.');try{const t=await vaultRead(path);if(!t||t.ownerId!==userId||t.refreshExpires<=Date.now())throw Error('Connect your own ArcGIS account in Connectors.');if(t.expires>Date.now()+60000)return {token:String(t.accessToken),username:String(t.username)};const fresh=await exchange({grant_type:'refresh_token',refresh_token:t.refreshToken});if(fresh.username&&fresh.username!==t.username)throw Error('ArcGIS account changed; reconnect.');await vaultWrite(path,{...t,accessToken:fresh.access_token,expires:Date.now()+fresh.expires_in*1000,...(fresh.refresh_token?{refreshToken:fresh.refresh_token}:{}),...(fresh.refresh_token_expires_in?{refreshExpires:Date.now()+fresh.refresh_token_expires_in*1000}:{})});return {token:String(fresh.access_token),username:String(t.username)};}finally{await unlock(lease);}}
export async function disconnectArcgis(userId:string){signedIn(userId);await vaultDelete(await vaultPath(userId,'arcgis'));}
