'use client';
import {useEffect,useRef,useState} from 'react';
import {Folder,File,Search,Plus,Upload,Grid2X2,List,RefreshCw,HardDrive,Clock,Star,Users,Trash2,ChevronRight,Download,ExternalLink} from 'lucide-react';
import {useUi} from '@/app/i18n/client';
type DriveFile={id:string;name:string;mimeType:string;size?:string;modifiedTime?:string;capabilities?:{canEdit?:boolean;canTrash?:boolean;canCopy?:boolean;canDownload?:boolean}};
type View='my'|'recent'|'starred'|'shared'|'trash';
export function DriveApp({pageId,language,writable,initialParent='root',initialQuery=''}:{pageId:string;language:string;writable:boolean;initialParent?:string;initialQuery?:string}){
 const {t}=useUi(),zh=language.startsWith('zh'),label=(en:string,cn:string)=>zh?cn:t(en);
 const [items,setItems]=useState<DriveFile[]>([]),[view,setView]=useState<View>('my'),[trail,setTrail]=useState<{id:string;name:string}[]>(initialParent==='root'?[]:[{id:initialParent,name:label('Folder','文件夹')}]),[search,setSearch]=useState(initialQuery),[query,setQuery]=useState(initialQuery),[grid,setGrid]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[next,setNext]=useState<string|null>(null),[revision,setRevision]=useState(0),[selected,setSelected]=useState<DriveFile|null>(null),[dialog,setDialog]=useState<{operation:string;file?:DriveFile}|null>(null),[name,setName]=useState(''),[destination,setDestination]=useState('root'),[folderTrail,setFolderTrail]=useState<{id:string;name:string}[]>([]),[folders,setFolders]=useState<DriveFile[]>([]),[folderNext,setFolderNext]=useState<string|null>(null);
 const dialogRef=useRef<HTMLFormElement>(null);useEffect(()=>{if(dialog)dialogRef.current?.querySelector<HTMLElement>('input,button')?.focus();},[dialog]);
 const upload=useRef<HTMLInputElement>(null),endpoint='/api/pages/'+encodeURIComponent(pageId)+'/drive',parent=trail.at(-1)?.id||'root';
 const tabs:[View,string,typeof Folder][]=[['my',label('My Drive','我的云端硬盘'),HardDrive],['recent',label('Recent','最近'),Clock],['starred',label('Starred','已加星标'),Star],['shared',label('Shared with me','与我共享'),Users],['trash',label('Trash','回收站'),Trash2]];
 const message=(text:string)=>text==='STORAGE_PERMISSION_REQUIRED'?label('Google requires permission for this file. Select it with Google Picker, then retry.','Google 需要此文件的操作权限。请先通过 Google Picker 选择文件，然后重试。'):text==='PAGE_READ_ONLY'?label('This page is read only. Fork it to use file actions.','此页面为只读。创建分支后可使用文件操作。'):t(text);
 async function json(url:string,init?:RequestInit){const r=await fetch(url,init),data=await r.json() as {error?:string;items:DriveFile[];next:string|null};if(!r.ok)throw Error(data.error||'Could not load files.');return data;}
 useEffect(()=>{const controller=new AbortController();setBusy(true);setError('');setSelected(null);setItems([]);setNext(null);json(endpoint+'?'+new URLSearchParams({parent,view,search:query}),{signal:controller.signal}).then(d=>{setItems(d.items);setNext(d.next);}).catch(e=>{if(!controller.signal.aborted)setError(message(e.message));}).finally(()=>{if(!controller.signal.aborted)setBusy(false);});return()=>controller.abort();},[endpoint,parent,view,query,revision]);
 async function more(){setBusy(true);try{const d=await json(endpoint+'?'+new URLSearchParams({parent,view,search:query,cursor:next!}));setItems(old=>[...old,...d.items]);setNext(d.next);}catch(e){setError(message((e as Error).message));}finally{setBusy(false);}}
 async function folderList(id:string,cursor?:string){try{const d=await json(endpoint+'?'+new URLSearchParams({parent:id,...(cursor?{cursor}:{})}));setFolders(old=>cursor?[...old,...d.items.filter((f:DriveFile)=>f.mimeType==='application/vnd.google-apps.folder')]:d.items.filter((f:DriveFile)=>f.mimeType==='application/vnd.google-apps.folder'));setFolderNext(d.next);}catch(e){setError(message((e as Error).message));}}
 function start(operation:string,file?:DriveFile){setDialog({operation,file});setName(operation==='copy'?label('Copy of ','副本 ')+(file?.name||''):file?.name||'');setDestination(parent);setFolderTrail([...trail]);if(operation==='move'||operation==='copy')void folderList(parent);}
 async function apply(){if(!dialog)return;setBusy(true);setError('');try{const args={...(dialog.file?{id:dialog.file.id}:{}),...(['mkdir','rename','copy'].includes(dialog.operation)?{name}:{}),...(['mkdir','move','copy'].includes(dialog.operation)?{parent:dialog.operation==='mkdir'?parent:destination}:{})};await json(endpoint,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({operation:dialog.operation,args})});setDialog(null);setSelected(null);setRevision(v=>v+1);}catch(e){setError(message((e as Error).message));}finally{setBusy(false);}}
 async function uploadFiles(files:FileList|null){if(!files)return;setBusy(true);setError('');try{for(const file of Array.from(files)){if(file.size>20*1024*1024)throw Error('Choose a file up to 20 MB.');await json(endpoint+'?'+new URLSearchParams({parent,name:file.name}),{method:'PUT',headers:{'Content-Type':file.type||'application/octet-stream'},body:file});}}catch(e){setError(message((e as Error).message));}finally{setBusy(false);setRevision(v=>v+1);if(upload.current)upload.current.value='';}}
 function open(file:DriveFile){if(file.mimeType==='application/vnd.google-apps.folder'){setTrail(query||view!=='my'?[{id:file.id,name:file.name}]:[...trail,{id:file.id,name:file.name}]);setView('my');setSearch('');setQuery('');}else window.open('https://drive.google.com/file/d/'+encodeURIComponent(file.id)+'/view','_blank','noopener,noreferrer');}
 return <section className="drive-app" aria-label="Google Drive"><aside className="drive-sidebar"><div className="drive-brand"><svg width="34" height="30" viewBox="0 0 87.3 78" aria-hidden="true"><path fill="#00832d" d="M6.6 66.9 0 55.5 25.2 11.8 38.4 34.6 19.7 67z"/><path fill="#0066da" d="M6.6 66.9 19.7 44.1h50.7l13.2 22.8L77 78H13.1z"/><path fill="#ffba00" d="M25.2 11.8 31.8 0h26.3l29.2 50.6-13.2 22.8L38.4 11.8z"/></svg><strong>Google Drive</strong></div><button className="drive-new" disabled={!writable||busy} onClick={()=>start('mkdir')}><Plus size={22}/>{label('New folder','新建文件夹')}</button><button disabled={!writable||busy} onClick={()=>upload.current?.click()}><Upload size={18}/>{label('Upload files','上传文件')}</button><nav>{tabs.map(([key,text,Icon])=><button key={key} aria-current={view===key?'page':undefined} onClick={()=>{setView(key);setTrail([]);setSearch('');setQuery('');}}><Icon size={18}/>{text}</button>)}</nav></aside><div className="drive-main"><form className="drive-search" onSubmit={e=>{e.preventDefault();setQuery(search.trim());}}><Search size={20}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder={label('Search in Drive','在云端硬盘中搜索')} aria-label={label('Search in Drive','在云端硬盘中搜索')}/><button>{label('Search','搜索')}</button></form><header><nav aria-label={t('Breadcrumbs')}><button onClick={()=>{setTrail([]);setQuery('');setSearch('');}}>{tabs.find(tab=>tab[0]===view)?.[1]}</button>{trail.map((folder,i)=><span key={folder.id}><ChevronRight size={17}/><button onClick={()=>setTrail(trail.slice(0,i+1))}>{folder.name}</button></span>)}</nav><div><button aria-label={t('Refresh')} disabled={busy} onClick={()=>setRevision(v=>v+1)}><RefreshCw size={18}/></button><button aria-label={t('List view')} aria-pressed={!grid} onClick={()=>setGrid(false)}><List size={18}/></button><button aria-label={t('Grid view')} aria-pressed={grid} onClick={()=>setGrid(true)}><Grid2X2 size={18}/></button></div></header>
 {selected&&<div className="drive-selection"><strong>{selected.name}</strong><button onClick={()=>open(selected)}><ExternalLink size={15}/>{label('Open','打开')}</button>{selected.mimeType!=='application/vnd.google-apps.folder'&&<a href={endpoint+'?download='+encodeURIComponent(selected.id)}><Download size={15}/>{label('Download','下载')}</a>}{view!=='trash'&&writable&&<>{['rename','move','copy','trash'].map(operation=><button key={operation} disabled={busy||(operation==='copy'&&(selected.mimeType==='application/vnd.google-apps.folder'||selected.capabilities?.canCopy===false))||(operation==='trash'&&selected.capabilities?.canTrash===false)||(['move','rename'].includes(operation)&&selected.capabilities?.canEdit===false)} onClick={()=>start(operation,selected)}>{({rename:label('Rename','重命名'),move:label('Move','移动'),copy:label('Make a copy','创建副本'),trash:label('Move to trash','移至回收站')})[operation]}</button>)}</>}<a href={'https://drive.google.com/'+(selected.mimeType==='application/vnd.google-apps.folder'?'drive/folders/':'file/d/')+encodeURIComponent(selected.id)+(selected.mimeType==='application/vnd.google-apps.folder'?'':'/view')} target="_blank" rel="noopener noreferrer">{view==='trash'?label('Restore in Google Drive','在 Google Drive 中恢复'):label('Share / manage access in Drive','在 Drive 中共享或管理权限')}</a></div>}
 <div className={grid?'drive-items drive-grid':'drive-items'} role="list" aria-busy={busy}>{!grid&&<div className="drive-columns"><span>{t('Name')}</span><span>{label('Modified','修改时间')}</span><span>{label('Size','大小')}</span></div>}{items.map(file=><div role="listitem" key={file.id} className={'drive-item'+(selected?.id===file.id?' selected':'')}><button className="drive-file-name" onClick={()=>setSelected(file)} onDoubleClick={()=>open(file)}>{file.mimeType==='application/vnd.google-apps.folder'?<Folder size={24}/>:<File size={24}/>}<span>{file.name}</span></button><small>{file.modifiedTime?new Date(file.modifiedTime).toLocaleDateString(language):'—'}</small><small>{file.size?Math.max(1,Math.round(Number(file.size)/1024))+' KB':'—'}</small><button aria-label={label('Open ','打开 ')+file.name} onClick={()=>open(file)}><ExternalLink size={16}/></button></div>)}</div>{busy&&<p role="status">{t('Loading…')}</p>}{!busy&&!items.length&&<p className="file-empty">{label('No files here.','此处没有文件。')}</p>}{next&&<button disabled={busy} onClick={()=>void more()}>{t('Load more')}</button>}
 <p className="drive-access-note">{label('File changes are available for files created here or selected with Google Picker.','可修改在此创建或通过 Google Picker 选择的文件。')} <a href={'/drive-picker?language='+encodeURIComponent(language)+'&returnTo='+encodeURIComponent('/?page='+pageId)}>{t('Choose Google Drive files to edit')}</a></p>{error&&<p role="alert">{error}</p>}</div><input ref={upload} type="file" multiple hidden onChange={e=>void uploadFiles(e.target.files)}/>
 {dialog&&<div className="drive-dialog-backdrop" onClick={e=>{if(e.target===e.currentTarget&&!busy)setDialog(null);}}><form ref={dialogRef} className="drive-dialog" role="dialog" aria-modal="true" aria-label={dialog.operation} onKeyDown={e=>{if(e.key==='Escape'&&!busy)setDialog(null);if(e.key==='Tab'){const controls=Array.from(e.currentTarget.querySelectorAll<HTMLElement>('button:not(:disabled),input:not(:disabled),a[href]'));const first=controls[0],last=controls.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus();}}}} onSubmit={e=>{e.preventDefault();void apply();}}><h3>{({mkdir:label('New folder','新建文件夹'),rename:label('Rename','重命名'),move:label('Move','移动'),copy:label('Make a copy','创建副本'),trash:label('Move to trash','移至回收站')})[dialog.operation]}</h3><p>{dialog.file?.name}</p>{['mkdir','rename','copy'].includes(dialog.operation)&&<label>{t('Name')}<input autoFocus required value={name} onChange={e=>setName(e.target.value)}/></label>}{['move','copy'].includes(dialog.operation)&&<fieldset><legend>{label('Destination folder','目标文件夹')}</legend><nav><button type="button" onClick={()=>{setDestination('root');setFolderTrail([]);void folderList('root');}}>{label('My Drive','我的云端硬盘')}</button>{folderTrail.map((folder,i)=><button type="button" key={folder.id} onClick={()=>{setDestination(folder.id);setFolderTrail(folderTrail.slice(0,i+1));void folderList(folder.id);}}>{folder.name}</button>)}</nav>{folders.filter(f=>f.id!==dialog.file?.id).map(folder=><button type="button" key={folder.id} onClick={()=>{setDestination(folder.id);setFolderTrail([...folderTrail,{id:folder.id,name:folder.name}]);void folderList(folder.id);}}><Folder size={16}/>{folder.name}</button>)}{folderNext&&<button type="button" onClick={()=>void folderList(destination,folderNext)}>{t('Load more')}</button>}</fieldset>}{error&&<p role="alert">{error}</p>}<footer><button type="button" disabled={busy} onClick={()=>setDialog(null)}>{t('Cancel')}</button><button disabled={busy||!writable}>{busy?t('Working…'):label('Confirm','确认')}</button></footer></form></div>}
 </section>;
}
