import {hasGoogleDriveScopes} from './google-scope';
import {requireStorageTool} from '@/app/connectors/storage-policy';
import {storageProviders,providers,type StorageProvider} from './contracts';import {setting,vaultReady,vaultPath,vaultRead,vaultWrite,vaultDelete,signedIn} from './vault';import {lock,unlock} from '@/db/store';import {safeReturnTo,validateOAuthState} from '@/app/connections/google-drive/crypto';
// A provider authenticates the server either with a client secret or, where supported
// (Microsoft), with a certificate: <PREFIX>_CERT_KEY_FILE names a PEM private key that
// never leaves the server and <PREFIX>_CERT_THUMBPRINT is the certificate's SHA-1
// thumbprint (hex) registered with the app. No shared secret has to be copied anywhere.
const credentials=(provider:StorageProvider)=>{const p=storageProviders[provider],keyFile=setting(p.prefix+'_CERT_KEY_FILE'),thumbprint=setting(p.prefix+'_CERT_THUMBPRINT').replace(/[^0-9a-f]/gi,'');return {id:setting(p.prefix+'_CLIENT_ID'),secret:setting(p.prefix+'_CLIENT_SECRET')||(keyFile&&thumbprint?'certificate':''),keyFile,thumbprint};};
const b64url=(data:Uint8Array|string)=>Buffer.from(data).toString('base64').replaceAll('+','-').replaceAll('/','_').replaceAll('=','');
async function clientAuth(provider:StorageProvider):Promise<Record<string,string>>{
 const c=credentials(provider);if(setting(storageProviders[provider].prefix+'_CLIENT_SECRET')||!c.keyFile)return {client_secret:c.secret};
 const [{readFile},{createSign}]=await Promise.all([import('node:fs/promises'),import('node:crypto')]);
 const now=Math.floor(Date.now()/1000),header=b64url(JSON.stringify({alg:'RS256',typ:'JWT',x5t:b64url(Buffer.from(c.thumbprint,'hex'))})),claims=b64url(JSON.stringify({aud:storageProviders[provider].token,iss:c.id,sub:c.id,jti:crypto.randomUUID(),nbf:now-60,iat:now,exp:now+600}));
 const signature=createSign('RSA-SHA256').update(header+'.'+claims).sign(await readFile(c.keyFile,'utf8'));
 return {client_assertion_type:'urn:ietf:params:oauth:client-assertion-type:jwt-bearer',client_assertion:header+'.'+claims+'.'+b64url(signature)};
}
export async function storageStatus(userId:string){return Promise.all(providers.map(async provider=>{const c=credentials(provider),configured=!!c.id&&!!c.secret&&vaultReady(),signed=!userId.startsWith('guest:');const saved=configured&&signed?await vaultRead(await vaultPath(userId,provider)):null;return {provider,name:storageProviders[provider].name,configured,signedIn:signed,connected:!!saved&&saved.ownerId===userId&&(provider!=='google'||hasGoogleDriveScopes(saved.scope))};}));}
export async function beginOAuth(provider:StorageProvider,userId:string,origin:string,returnTo:unknown){signedIn(userId);const p=storageProviders[provider],c=credentials(provider);if(!c.id||!c.secret||!vaultReady())throw Error('STORAGE_SETUP_REQUIRED');const state=crypto.randomUUID(),verifier=Array.from(crypto.getRandomValues(new Uint8Array(32)),n=>n.toString(16).padStart(2,'0')).join('');const digest=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(verifier)),challenge=btoa(String.fromCharCode(...new Uint8Array(digest))).replaceAll('+','-').replaceAll('/','_').replaceAll('=','');const redirect=(process.env.APP_URL||origin)+'/api/storage/'+provider+'/callback';await vaultWrite(await vaultPath(userId,'state-'+state),{ownerId:userId,provider,verifier,redirect,returnTo:safeReturnTo(returnTo),expires:Date.now()+600000});const url=new URL(p.authorize);url.search=new URLSearchParams({client_id:c.id,response_type:'code',redirect_uri:redirect,scope:p.scope,state,code_challenge:challenge,code_challenge_method:'S256',...(provider==='google'?{access_type:'offline',prompt:'consent'}:provider==='dropbox'?{token_access_type:'offline'}:{prompt:'select_account'})}).toString();return {state,url:url.toString()};}
async function exchange(provider:StorageProvider,values:Record<string,string>){const c=credentials(provider),r=await fetch(storageProviders[provider].token,{method:'POST',redirect:'error',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams({client_id:c.id,...await clientAuth(provider),...values}),signal:AbortSignal.timeout(20000)});if(!r.ok){const detail=await r.text().catch(()=>'');console.error('storage token exchange failed',provider,r.status,detail.slice(0,300));throw Error('STORAGE_RECONNECT_REQUIRED');}return await r.json() as {access_token?:string;refresh_token?:string;expires_in?:number;scope?:string};}
export async function finishOAuth(provider:StorageProvider,userId:string,state:string,cookie:string,code:string,cancelled=false){signedIn(userId);if(!/^[a-f0-9-]{36}$/.test(state)||state!==cookie)throw Error('STORAGE_INVALID_STATE');const lease=await lock('storage-oauth:'+state,60000);if(!lease)throw Error('STORAGE_INVALID_STATE');try{const path=await vaultPath(userId,'state-'+state),pending=await vaultRead(path);validateOAuthState(pending,userId,state,cookie);if(pending.provider!==provider)throw Error('STORAGE_INVALID_STATE');await vaultDelete(path);if(cancelled)return pending.returnTo;const t=await exchange(provider,{grant_type:'authorization_code',code,code_verifier:pending.verifier,redirect_uri:pending.redirect});if(provider==='google'&&!hasGoogleDriveScopes(t.scope))throw Error('STORAGE_RECONNECT_REQUIRED');if(!t.access_token||!t.refresh_token)throw Error('STORAGE_RECONNECT_REQUIRED');await vaultWrite(await vaultPath(userId,provider),{ownerId:userId,scope:t.scope,accessToken:t.access_token,refreshToken:t.refresh_token,expires:Date.now()+(t.expires_in||3600)*1000});return pending.returnTo;}finally{await unlock(lease);}}
export async function storageToken(provider:StorageProvider,userId:string){signedIn(userId);await requireStorageTool(userId,provider);if(!vaultReady())throw Error('STORAGE_SETUP_REQUIRED');const path=await vaultPath(userId,provider),lease=await lock('storage-token:'+userId+':'+provider,30000);if(!lease)throw Error('STORAGE_BUSY');try{const t=await vaultRead(path);if(!t||t.ownerId!==userId)throw Error('STORAGE_CONNECT_REQUIRED');if(provider==='google'&&!hasGoogleDriveScopes(t.scope))throw Error('STORAGE_RECONNECT_REQUIRED');if(t.expires>Date.now()+60000)return String(t.accessToken);const fresh=await exchange(provider,{grant_type:'refresh_token',refresh_token:t.refreshToken,...(provider==='onedrive'?{scope:storageProviders[provider].scope}:{})});if(!fresh.access_token)throw Error('STORAGE_RECONNECT_REQUIRED');await vaultWrite(path,{...t,accessToken:fresh.access_token,refreshToken:fresh.refresh_token||t.refreshToken,expires:Date.now()+(fresh.expires_in||3600)*1000});return fresh.access_token;}finally{await unlock(lease);}}
export async function disconnectStorage(provider:StorageProvider,userId:string){signedIn(userId);await vaultDelete(await vaultPath(userId,provider));}
