import {getActor} from '@/app/actor';
import {getPage,reply,sameOrigin} from '@/db/store';
import {canWritePage} from '@/app/page-permissions';
import {storageToken} from '@/app/storage/oauth';
import {requireStorageTool} from '@/app/connectors/storage-policy';
import {executeStorage,approveStorage} from '@/app/storage/service';
import {z} from 'zod';
const id=z.string().regex(/^[A-Za-z0-9_-]+$/).max(2000);
const base='https://www.googleapis.com/drive/v3/files';
async function google(url:string,token:string,init:RequestInit={}){const r=await fetch(url,{...init,headers:{...init.headers,Authorization:'Bearer '+token},redirect:'error',signal:AbortSignal.timeout(60000)});if(!r.ok)throw Error(r.status===403?'STORAGE_PERMISSION_REQUIRED':r.status===401?'STORAGE_RECONNECT_REQUIRED':'STORAGE_OPERATION_FAILED');return r;}
async function access(request:Request,params:Promise<{id:string}>,write=false){const actor=await getActor(request),page=await getPage((await params).id,actor.userId);if(!page)throw Error('PAGE_UNAVAILABLE');if(write&&(!sameOrigin(request)||!canWritePage(page)))throw Error('PAGE_READ_ONLY');return {actor,page};}
const error=(e:unknown)=>reply({error:e instanceof Error?e.message:'STORAGE_OPERATION_FAILED'},400);
export async function GET(request:Request,{params}:{params:Promise<{id:string}>}){try{const {actor}=await access(request,params),u=new URL(request.url),download=u.searchParams.get('download');await requireStorageTool(actor.userId,'google',download?'read':'list');const token=await storageToken('google',actor.userId);
 if(download){const file=id.parse(download),meta=await (await google(base+'/'+file+'?fields=name,mimeType',token)).json() as {name:string;mimeType:string};const exports:Record<string,[string,string]>={'application/vnd.google-apps.document':['application/pdf','.pdf'],'application/vnd.google-apps.spreadsheet':['application/vnd.openxmlformats-officedocument.spreadsheetml.sheet','.xlsx'],'application/vnd.google-apps.presentation':['application/pdf','.pdf']};const format=exports[meta.mimeType];if(meta.mimeType.startsWith('application/vnd.google-apps.')&&!format)throw Error('Download this file from Google Drive.');const r=await google(base+'/'+file+(format?'/export?mimeType='+encodeURIComponent(format[0]):'?alt=media'),token);return actor.finish(new Response(r.body,{headers:{'Content-Type':r.headers.get('content-type')||'application/octet-stream','Content-Disposition':"attachment; filename*=UTF-8''"+encodeURIComponent(meta.name+(format?.[1]||'')),'Cache-Control':'private, no-store','X-Content-Type-Options':'nosniff'}}));}
 const parent=id.parse(u.searchParams.get('parent')||'root'),view=u.searchParams.get('view'),search=(u.searchParams.get('search')||'').slice(0,200).replace(/\\/g,'\\\\').replace(/'/g,"\\'");let q=view==='trash'?'trashed = true':'trashed = false';if(search)q+=" and name contains '"+search+"'";else if(view==='starred')q+=' and starred = true';else if(view==='shared')q+=' and sharedWithMe = true';else if(view!=='recent'&&view!=='trash')q+=" and '"+parent+"' in parents";
 const query=new URLSearchParams({q,pageSize:'100',fields:'nextPageToken,files(id,name,mimeType,parents,size,modifiedTime,webViewLink,starred,capabilities(canEdit,canTrash,canCopy,canDownload))',orderBy:view==='recent'?'modifiedTime desc':'folder,name',...(u.searchParams.get('cursor')?{pageToken:u.searchParams.get('cursor')!}:{})});const data=await(await google(base+'?'+query,token)).json() as {files?:unknown[];nextPageToken?:string};return actor.finish(reply({items:data.files||[],next:data.nextPageToken||null}));
 }catch(e){return error(e);}}
export async function POST(request:Request,{params}:{params:Promise<{id:string}>}){try{const {actor,page}=await access(request,params,true),raw=await request.json() as {operation:unknown;args:unknown};const result=await executeStorage({provider:'google',operation:z.enum(['mkdir','rename','move','copy','trash']).parse(raw.operation),args:raw.args},actor.userId,page.id);if(!('actionId' in result))throw Error('Choose a file action.');return actor.finish(reply({result:await approveStorage(result.actionId,actor.userId)}));}catch(e){return error(e);}}
export async function PUT(request:Request,{params}:{params:Promise<{id:string}>}){try{const {actor}=await access(request,params,true);await requireStorageTool(actor.userId,'google','upload');const u=new URL(request.url),parent=id.parse(u.searchParams.get('parent')||'root'),name=z.string().min(1).max(200).parse(u.searchParams.get('name')),limit=20*1024*1024;if(Number(request.headers.get('content-length'))>limit)throw Error('Choose a file up to 20 MB.');const reader=request.body?.getReader();if(!reader)throw Error('Missing file.');const chunks:Uint8Array[]=[];let size=0;try{while(true){const {done,value}=await reader.read();if(done)break;size+=value.length;if(size>limit)throw Error('Choose a file up to 20 MB.');chunks.push(value);}}finally{await reader.cancel().catch(()=>{});}const data=new Uint8Array(size);let offset=0;for(const chunk of chunks){data.set(chunk,offset);offset+=chunk.length;}const boundary='wiki-'+crypto.randomUUID(),mime=request.headers.get('content-type')||'application/octet-stream';if(/[\r\n]/.test(mime))throw Error('Invalid content type.');const body=new Blob(['--'+boundary+'\r\nContent-Type: application/json; charset=UTF-8\r\n\r\n'+JSON.stringify({name,parents:[parent]})+'\r\n--'+boundary+'\r\nContent-Type: '+mime+'\r\n\r\n',data,'\r\n--'+boundary+'--']);const r=await google('https://www.googleapis.com/upload/drive/v3/files?uploadType=multipart',await storageToken('google',actor.userId),{method:'POST',headers:{'Content-Type':'multipart/related; boundary='+boundary},body});return actor.finish(reply({file:await r.json()}));}catch(e){return error(e);}}
