import {folderPath} from '@/app/context-files/tree';import {canWritePage} from '@/app/page-permissions';import {getActor} from '@/app/actor';import {getPage,reply,database,sameOrigin} from '@/db/store';import {listContextFiles} from '@/app/context-files/server';
export async function GET(request:Request,{params}:{params:Promise<{id:string}>}){const a=await getActor(request);try{const page=await getPage((await params).id,a.userId);if(!page)return a.finish(reply({error:'Page unavailable.'},404));const folders=await database().prepare(`SELECT path FROM page_file_folders WHERE page_id=? AND (scope='' OR scope=?)`).bind(page.id,a.userId).all<{path:string}>();return a.finish(reply({files:await listContextFiles(page.id,a.userId),folders:folders.results.map(f=>f.path)}));}catch{return a.finish(reply({error:'Could not load context files.'},503));}}

export async function POST(request:Request,{params}:{params:Promise<{id:string}>}){const actor=await getActor(request);try{
 if(!sameOrigin(request))return actor.finish(reply({error:'Invalid origin.'},403));
 const page=await getPage((await params).id,actor.userId);if(!page)return actor.finish(reply({error:'Page unavailable.'},404));
 const data=await request.json() as {path?:unknown};const path=folderPath(data.path);if(!path)throw Error('Enter a folder name.');
 await database().prepare("INSERT OR IGNORE INTO page_file_folders(id,page_id,scope,path,owner_id) SELECT ?,id,CASE WHEN owner_id=? OR (visibility='public' AND public_write=1) THEN '' ELSE ? END,?,? FROM pages WHERE id=? AND (visibility='public' OR owner_id=?)").bind(crypto.randomUUID(),actor.userId,actor.userId,path,actor.userId,page.id,actor.userId).run();return actor.finish(reply({created:true,path}));
 }catch(error){return actor.finish(reply({error:error instanceof Error?error.message:'Could not create folder.'},400));}}
