export type AnswerPage = {
  sessionId?:string;
  contextIndex?:{kind:'pages'|'jobs';items:import('./context-index/server').ContextIndexItem[]};
  forks?: {id:string;title:string;visibility:'public'|'private';publicWrite?:boolean;createdAt:string;removable?:boolean;isOriginal?:boolean}[];
  links?: import('./internal-links').InternalLink[];
  kind?: 'static'|'dynamic'|'resource';
  component?:{type:string;version:number;payload:unknown;links:{role:string;id:string;version:number;type:string;title:string}[]};
  dynamic?: import('./dynamic/units').DynamicConfig;
  parameters?: import('./components-registry/contracts').Parameters;
  applicationResult?: import('./components-registry/contracts').Parameters;
  runtimeError?: string;
  view?:import('./page-programs/contracts').PageView;
  proposals?:import('./page-programs/runtime').ProgramProposal[];
  runtime?: import('./dynamic/units').ConversionResult;
  id: string;
  question?: string;
  language: string;
  labels: {sourceMedia?:import('./url-content/media').SourceMedia[];sourceUrl?:string;sourceSummary?:string;indexEntries?:import('./disambiguation/view').IndexEntry[];templateId?:import('./templates/catalog').TemplateId;overview?:string;contents?:string;sources?:string};
  title: string;
  summary: string;
  body: string;
  category: string;
  visibility: 'public' | 'private';
  owned: boolean;
  publicWrite?: boolean;
  createdAt: string;
  updatedAt?: string;
  checkedAt?: string;
  questionCount: number;
  sources: { title: string; url: string }[];
};
