'use client';
import {useEffect,useRef,useState} from 'react';
import {loadArcGIS} from '@/app/geo/arcgis';
import {ResourcePicker} from '@/app/resources/picker';
import type {Resource} from '@/app/resources/contracts';
import {uploadPageFiles} from '@/app/context-files/upload';
import {toolHref,type SourceRef} from '@/app/tools/sources';
import {useUi} from '@/app/i18n/client';
import './style.css';
type Session={principal:string;connected:boolean;enabled:boolean;username?:string;allowed:string[];writable:boolean};
export function ArcgisPublisher({source}:{source:SourceRef}){
 const {t}=useUi(),[session,setSession]=useState<Session>(),[resource,setResource]=useState<Resource>(),[local,setLocal]=useState<File>(),[picker,setPicker]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[title,setTitle]=useState(''),[confirmed,setConfirmed]=useState(false),[query,setQuery]=useState(''),[scope,setScope]=useState('mine'),[maps,setMaps]=useState<any[]>([]),[next,setNext]=useState(-1),[input,setInput]=useState(''),[mapId,setMapId]=useState(''),[publication,setPublication]=useState<any>();
 const principal=useRef('');
 const host=useRef<HTMLDivElement>(null),view=useRef<any>(null),lock=useRef(false),endpoint='/api/pages/'+encodeURIComponent(source.page||'')+'/arcgis';
 const allowed=(name:string)=>!!session?.connected&&session.enabled&&session.allowed.includes(name);
 async function refresh(){const r=await fetch(endpoint,{cache:'no-store'}),d=await r.json() as any;if(!r.ok)throw Error(d.error);if(principal.current&&principal.current!==d.principal){setMapId('');setMaps([]);setResource(undefined);setLocal(undefined);setPublication(undefined);setConfirmed(false);}principal.current=d.principal;setSession(d);if(!d.connected||!d.enabled||!d.allowed.includes('get_item')){setMaps([]);setMapId('');}}
 useEffect(()=>{void refresh().catch(e=>setError(String(e)));const timer=setInterval(()=>void refresh().catch(()=>{setSession(undefined);setMapId('');}),30000);return()=>clearInterval(timer);},[source.page]);
 useEffect(()=>{if(source.file&&source.name){setResource({space:(source.space||'page') as Resource['space'],id:source.file,name:source.name,kind:'file',...(source.connector?{connectorId:source.connector}:{})});setTitle(source.name.replace(/\.[^.]+$/,''));}},[source.file,source.page]);
 async function task(fn:()=>Promise<void>){if(lock.current)return;lock.current=true;setBusy(true);setError('');try{await fn();}catch(e){setError(e instanceof Error?e.message:'ArcGIS operation failed.');}finally{lock.current=false;setBusy(false);}}
 async function call(tool:string,args:unknown){const r=await fetch(endpoint,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({tool,args})}),d=await r.json() as any;if(!r.ok)throw Error(d.error);if(d.result?.confirmationRequired)throw Error('Approve this action in Connectors.');return d.result;}
 function select(r:Resource){setResource(r);setLocal(undefined);setTitle(r.name.replace(/\.[^.]+$/,''));setPublication(undefined);setConfirmed(false);}
 async function search(start=1){const me=scope==='mine'?session?.username:undefined;const quote=(s:string)=>'"'+s.replace(/["\\]/g,' ')+'"';const q='type:"Web Map"'+(me?' AND owner:'+quote(me):'')+(query.trim()?' AND title:'+quote(query.trim()):'');const result=await call('search_items',{query:q,start,num:20});setMaps(old=>start===1?result.results:[...old,...result.results]);setNext(result.nextStart);}
 async function open(value:string){let id=value.trim();if(id.startsWith('https://')){const u=new URL(id);if(!/(^|\.)arcgis\.com$/.test(u.hostname))throw Error('Use an ArcGIS Online map URL.');id=u.searchParams.get('webmap')||u.searchParams.get('id')||'';}if(!/^[a-f0-9]{32}$/i.test(id))throw Error('Enter a Web Map ID or URL.');const item=await call('get_item',{itemId:id});if(item.metadata?.type!=='Web Map')throw Error('Choose a Web Map item.');setMapId(id);}
 async function publish(){if(!confirmed||!source.page)throw Error('Confirm the selected upload first.');let selected=resource;if(local){await uploadPageFiles(source.page,[local],f=>{selected={space:'page',id:f.id,name:f.name,kind:'file'};});setResource(selected);setLocal(undefined);}if(!selected)throw Error('Choose a GIS file.');const result=await call('publish_file',{pageId:source.page,resource:selected});setPublication(result);}
 async function check(){const service=publication?.services?.[0];if(!service?.serviceItemId)throw Error('Inspect the source item in ArcGIS Online before retrying.');const result=await call('publication_status',{itemId:service.serviceItemId,...(service.jobId?{jobId:service.jobId}:{})});setPublication((p:any)=>({...p,status:result.status}));if(result.status==='completed')setError('');}
 async function saveMap(){const result=await call('create_web_map',{title:title||resource?.name||'GIS map',layerItemIds:[publication.services[0].serviceItemId]});setPublication((p:any)=>({...p,mapId:result.itemId}));setMapId(result.itemId);}
 useEffect(()=>{if(!mapId)return;let disposed=false;void (async()=>{try{const r=await fetch(endpoint+'?map='+mapId,{cache:'no-store'}),d=await r.json() as any;if(!r.ok)throw Error(d.error);const modules=await loadArcGIS(),[identity,WebMap,MapView]=await modules(['@arcgis/core/identity/IdentityManager.js','@arcgis/core/WebMap.js','@arcgis/core/views/MapView.js']);if(disposed)return;identity.registerToken(d.credential);view.current=new MapView({container:host.current,map:new WebMap({portalItem:{id:mapId,portal:{url:'https://www.arcgis.com'}}})});await view.current.when();}catch(e){if(!disposed)setError(String(e));}})();return()=>{disposed=true;view.current?.destroy();view.current=null;};},[mapId,endpoint]);
 return <section className="arcgis-publisher"><header><span>ARCGIS ONLINE</span><h2>{t('ArcGIS Maps')}</h2><p>{t('Browse maps and publish connected GIS data using your ArcGIS connector.')}</p></header><p>{session?.connected?t('Connected ArcGIS account')+': '+session.username:t('Connect your own ArcGIS Online account in Connectors above.')} {session?.connected&&!session.enabled&&t('Enable ArcGIS Online in Connectors to use this app.')}</p><button disabled={busy} onClick={()=>void task(refresh)}>{t('Refresh connection')}</button>
 <fieldset disabled={busy||!allowed('search_items')}><legend>{t('Browse ArcGIS Online maps')}</legend><select aria-label={t('Map scope')} value={scope} onChange={e=>{setScope(e.target.value);setNext(-1);setMaps([]);}}><option value="mine">{t('My maps')}</option><option value="all">{t('All accessible maps')}</option></select><input aria-label={t('Search map titles')} value={query} onChange={e=>setQuery(e.target.value)}/><button onClick={()=>void task(()=>search())}>{t('Search maps')}</button><ul>{maps.map(m=><li key={m.id}><button disabled={!allowed('get_item')} onClick={()=>void task(()=>open(m.id))}>{m.title}</button> <small>{m.owner} · {m.access}</small></li>)}</ul>{next>0&&<button onClick={()=>void task(()=>search(next))}>{t('Load more')}</button>}</fieldset>
 <fieldset disabled={busy||!allowed('get_item')}><legend>{t('Open map')}</legend><label>{t('ArcGIS map URL or item ID')}<input value={input} onChange={e=>setInput(e.target.value)}/></label><button disabled={!input.trim()} onClick={()=>void task(()=>open(input))}>{t('Open map')}</button></fieldset>
 <fieldset disabled={busy||!session?.writable||!allowed('publish_file')}><legend>{t('Publish GIS data')}</legend><button onClick={()=>setPicker(true)}>{t('Choose from connected storage')}</button><label>{t('Or upload a local file to Page files')}<input type="file" accept=".zip,.geojson,.json,.csv,.tsv" onChange={e=>{const f=e.target.files?.[0];if(f){if(f.size>10*1024*1024){setError('Choose a file up to 10 MB.');return;}setLocal(f);setResource(undefined);setTitle(f.name.replace(/\.[^.]+$/,''));setPublication(undefined);setConfirmed(false);}}}/></label><p>{local?.name||resource?.name||t('No file selected')}</p><small>{t('GeoJSON, coordinate CSV/TSV, or complete zipped shapefiles; up to 10 MB.')}</small><label>{t('Map title')}<input value={title} onChange={e=>setTitle(e.target.value)}/></label><label className="arcgis-confirm"><input type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/>{t('Upload this data to my ArcGIS account as a private hosted layer. Storage credits may apply.')}</label><button disabled={!confirmed||(!local&&!resource)||!!publication} onClick={()=>void task(publish)}>{t('Publish layer')}</button></fieldset>{session&&!session.writable&&<p>{t('Fork this page to publish data or create maps. Read-only pages allow map browsing.')}</p>}
 {publication&&<div role="status"><p>{publication.status||publication.state}</p>{publication.sourceUrl&&<a href={publication.sourceUrl} target="_blank" rel="noopener noreferrer">{t('Source item')}</a>}<button disabled={busy||!allowed('publication_status')} onClick={()=>void task(check)}>{t('Check publication status')}</button>{publication.status==='completed'&&<button disabled={busy||!allowed('create_web_map')||!!publication.mapId} onClick={()=>void task(saveMap)}>{t('Create and display web map')}</button>}{publication.instruction&&<p>{publication.instruction}</p>}</div>}{error&&<p role="alert">{error}</p>}{mapId&&<a href={'https://www.arcgis.com/apps/mapviewer/index.html?webmap='+mapId} target="_blank" rel="noopener noreferrer">{t('Open map in ArcGIS Online')}</a>}<div className="arcgis-published-map" hidden={!mapId} ref={host}/><a href={toolHref('hub',source)}>{t('All apps')}</a>
 {picker&&source.page&&<ResourcePicker pageId={source.page} onClose={()=>setPicker(false)} onSelect={items=>{setPicker(false);const files=items.filter(i=>i.type==='resource'&&i.resource.kind==='file');if(files.length!==1){setError('Choose one GIS file or shapefile ZIP.');return;}select((files[0] as {resource:Resource}).resource);}}/>}</section>;
}
