export type ArcRequest=(path:string,values?:Record<string,string|Blob>)=>Promise<any>;
export type PublishProgress={sourceId?:string;layerId?:string;mapId?:string;jobId?:string;phase:string};
export function portalUrl(value:string){const u=new URL(value);if(u.protocol!=='https:'||!/^([a-z0-9-]+\.)?maps\.arcgis\.com$|^www\.arcgis\.com$/.test(u.hostname)||u.port||u.username||u.password)throw Error('Use an ArcGIS Online organization URL.');return u.origin;}
export function webMap(title:string,layerId:string,url:string,layers:{id:number;name?:string}[],extent?:number[][]){return {version:'2.31',authoringApp:'AgenticWiKi',operationalLayers:layers.map(l=>({id:layerId+'_'+l.id,itemId:layerId,title:l.name||title,url:url+'/'+l.id,layerType:'ArcGISFeatureLayer',visibility:true,opacity:1})),baseMap:{title:'Satellite imagery',baseMapLayers:[{id:'imagery',layerType:'ArcGISTiledMapServiceLayer',url:'https://services.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer',visibility:true,opacity:1}]},...(extent?{initialState:{viewpoint:{targetGeometry:{xmin:extent[0][0],ymin:extent[0][1],xmax:extent[1][0],ymax:extent[1][1],spatialReference:{wkid:4326}}}}}:{})};}
// Each write runs once. On failures the UI retains item IDs for recovery; it never retries uploads automatically.
export async function publishMap(request:ArcRequest,username:string,file:File,title:string,progress:(p:PublishProgress)=>void,wait=()=>new Promise(r=>setTimeout(r,2000))){
 const user='content/users/'+encodeURIComponent(username),state:PublishProgress={phase:'Uploading source'};const update=(p:Partial<PublishProgress>)=>{Object.assign(state,p);progress({...state});};
 const shape=/\.zip$/i.test(file.name),added=await request(user+'/addItem',{title,type:shape?'Shapefile':'GeoJson',tags:'AgenticWiKi',file});if(!added.id)throw Error('ArcGIS did not return a source item ID.');update({sourceId:added.id,phase:'Publishing hosted layer'});
 const published=await request(user+'/publish',{itemID:added.id,filetype:shape?'shapefile':'geojson',publishParameters:JSON.stringify({name:'wiki_'+crypto.randomUUID().replaceAll('-','')})}),service=published.services?.[0];if(!service?.serviceItemId)throw Error(service?.error?.message||'ArcGIS did not return a hosted layer.');update({layerId:service.serviceItemId,jobId:service.jobId});
 let complete=false;for(let i=0;i<90;i++){const status=await request(user+'/items/'+state.layerId+'/status',{jobType:'publish',...(state.jobId?{jobId:state.jobId}:{})});if(status.status==='completed'){complete=true;break;}if(['failed','error','cancelled'].includes(status.status))throw Error(status.statusMessage||'ArcGIS publishing failed.');await wait();}if(!complete)throw Error('Publishing is still pending. Open the layer in ArcGIS Online to check status; do not submit it again.');
 const item=await request('content/items/'+state.layerId);if(!item.url)throw Error('Published layer has no service URL.');
 // ArcGIS service URLs are returned by the authenticated portal, never from selected file content.
 const details=await request(item.url);if(!details.layers?.length)throw Error('The published service contains no map layers.');update({phase:'Saving web map'});
 const map=await request(user+'/addItem',{title,type:'Web Map',tags:'AgenticWiKi',text:JSON.stringify(webMap(title,state.layerId!,item.url,details.layers,item.extent))});if(!map.id)throw Error('Layer published, but the web map was not saved.');update({mapId:map.id,phase:'Published privately'});return {...state};
}
