'use client';
import {useEffect,useRef,useState} from 'react';
import {Folder,File,Upload,FolderPlus,ChevronRight,Pencil,X} from 'lucide-react';
import {useUi} from '@/app/i18n/client';
import {buildFileTree,type FileTree} from './tree';
import {FileBrowser,type FileEntry} from '@/app/templates/file-browser';
import type {ContextFile} from './server';
import type {AnswerPage} from '@/app/page-types';
export function ContextFiles({page,revision,busy}:{page:AnswerPage;revision:number;onUpload?:()=>void;busy:boolean}){
 const {t}=useUi(),[files,setFiles]=useState<ContextFile[]>([]),[folders,setFolders]=useState<string[]>([]),[error,setError]=useState(''),[working,setWorking]=useState(false),[target,setTarget]=useState(''),[newFolder,setNewFolder]=useState<string|null>(null),[editing,setEditing]=useState<ContextFile|null>(null),[name,setName]=useState(''),[moveTo,setMoveTo]=useState('');const input=useRef<HTMLInputElement>(null),directory=useRef<HTMLInputElement>(null);
 async function load(signal?:AbortSignal){const r=await fetch('/api/pages/'+page.id+'/files',{signal}),d=await r.json() as {files:ContextFile[];folders:string[];error?:string};if(!r.ok)throw Error(d.error);setFiles(d.files);setFolders(d.folders||[]);}
 useEffect(()=>{const c=new AbortController();void load(c.signal).catch(e=>{if(!c.signal.aborted)setError(String(e));});return()=>c.abort();},[page.id,revision,page.visibility,page.publicWrite]);
 async function action(run:()=>Promise<void>){setWorking(true);setError('');try{await run();await load();}catch(e){setError(e instanceof Error?e.message:'Could not update files.');}finally{setWorking(false);}}
 async function request(url:string,method:string,data?:unknown){const r=await fetch(url,{method,headers:{'Content-Type':'application/json'},body:data?JSON.stringify(data):undefined}),d=await r.json() as {error?:string};if(!r.ok)throw Error(d.error);}
 async function upload(list:FileList|null){if(!list)return;const selected=Array.from(list);await action(async()=>{for(const file of selected){if(file.size>10*1024*1024)throw Error('Choose a file up to 10 MB.');const relative=file.webkitRelativePath?.split('/').slice(0,-1).join('/')||'',path=[target,relative].filter(Boolean).join('/');const r=await fetch('/api/components/upload',{method:'POST',headers:{'Content-Type':file.type||'application/octet-stream','X-Page-Id':page.id,'X-File-Name':encodeURIComponent(file.name),'X-Folder-Path':encodeURIComponent(path)},body:file});if(!r.ok){const d=await r.json() as {error?:string};throw Error(d.error);}}});if(input.current)input.current.value='';if(directory.current)directory.current.value='';}
 const tree=buildFileTree(files,folders),paths:string[]=[''];function collect(node:FileTree<ContextFile>){node.folders.forEach(f=>{paths.push(f.path);collect(f);});}collect(tree);
 const items:FileEntry[]=[];
 function collectEntries(node:FileTree<ContextFile>){
  for(const folder of node.folders){items.push({id:'folder:'+folder.path,name:folder.name,kind:'folder',parents:node.path?['folder:'+node.path]:[]});collectEntries(folder);}
  for(const file of node.files)items.push({id:file.id,name:file.name,kind:'file',url:file.url,parents:node.path?['folder:'+node.path]:[]});
 }
 collectEntries(tree);
 function fileActions(entry:FileEntry){const file=files.find(f=>f.id===entry.id);return file&&<><small>{Math.max(1,Math.round(file.size/1024))} KB</small>{file.removable&&<span className="page-file-actions"><button disabled={working||busy} aria-label={t('Rename or move')+': '+file.name} title={t('Rename or move')} onClick={()=>{setEditing(file);setName(file.name);setMoveTo(file.folderPath);}}><Pencil size={13}/></button><button disabled={working||busy} aria-label={t('Remove from context')+': '+file.name} title={t('Remove from context')} onClick={()=>void action(()=>request(file.url,'DELETE'))}><X size={13}/></button></span>}</>;}
 return <details className="context-files file-explorer" open><summary><Folder size={17}/><strong>{t('Page files')}</strong><small>{files.length}</small></summary>
  <div className="file-explorer-toolbar"><label>{t('Folder')}<select value={target} onChange={e=>setTarget(e.target.value)}>{paths.map(path=><option key={path} value={path}>{path||t('Root')}</option>)}</select></label><button disabled={working||busy} onClick={()=>input.current?.click()}><Upload size={14}/>{t('Upload files')}</button><button disabled={working||busy} onClick={()=>directory.current?.click()}>{t('Upload folder')}</button><button disabled={working||busy} onClick={()=>setNewFolder('')}><FolderPlus size={14}/>{t('New folder')}</button></div>
  <input ref={input} hidden type="file" multiple onChange={e=>void upload(e.target.files)}/><input ref={directory} hidden type="file" multiple {...{webkitdirectory:''}} onChange={e=>void upload(e.target.files)}/>
  {newFolder!==null&&<form className="file-explorer-form" onSubmit={e=>{e.preventDefault();void action(async()=>{await request('/api/pages/'+page.id+'/files','POST',{path:[target,newFolder].filter(Boolean).join('/')});setNewFolder(null);});}}><input aria-label={t('Folder name')} value={newFolder} onChange={e=>setNewFolder(e.target.value)} required/><button disabled={working}>{t('Create folder')}</button><button type="button" onClick={()=>setNewFolder(null)}>{t('Cancel')}</button></form>}
  {editing&&<form className="file-explorer-form" onSubmit={e=>{e.preventDefault();void action(async()=>{await request(editing.url,'PATCH',{name,folderPath:moveTo});setEditing(null);});}}><label>{t('Name')}<input value={name} onChange={e=>setName(e.target.value)} required/></label><label>{t('Move to folder')}<select value={moveTo} onChange={e=>setMoveTo(e.target.value)}>{paths.map(path=><option key={path} value={path}>{path||t('Root')}</option>)}</select></label><button disabled={working}>{t('Save changes')}</button><button type="button" onClick={()=>setEditing(null)}>{t('Cancel')}</button></form>}
  <FileBrowser items={items} title={t('Page files')} language={page.language} renderActions={fileActions}/>{!files.length&&!folders.length&&<p>{t('No files yet. Upload files or create a folder.')}</p>}{working&&<p role="status">{t('Working…')}</p>}{error&&<p role="alert">{t(error)}</p>}
 </details>;
}
