import {Buffer} from 'node:buffer';
import {z} from 'zod';
import {env} from '@/server/runtime';
import {getPage} from '@/db/store';
import {contextFiles,listContextFiles,type FilePart} from './server';
import {parse} from 'csv-parse/sync';
import ExcelJS from 'exceljs';
import {PDFDocument} from 'pdf-lib';
import yauzl from 'yauzl';
export const readOptions=z.object({mode:z.enum(['auto','text','table','pdf','image','archive']).default('auto'),sheet:z.string().max(200).optional(),start:z.number().int().min(1).max(1000000).default(1),count:z.number().int().min(1).max(200).default(50),column:z.number().int().min(1).max(16384).default(1),columns:z.number().int().min(1).max(50).default(20),query:z.string().max(200).optional()}).strict();
export async function archiveEntries(bytes:Buffer){return new Promise<{name:string;size:number}[]>((resolve,reject)=>{yauzl.fromBuffer(bytes,{lazyEntries:true},(error,zip)=>{if(error||!zip)return reject(Error('Invalid or unsupported ZIP archive.'));let total=0;const entries:{name:string;size:number}[]=[];zip.on('error',reject);zip.on('entry',entry=>{total+=entry.uncompressedSize;if(total>40*1024*1024||entries.length>=10000){zip.close();reject(Error('Archive expands beyond the 40 MB processing limit.'));return;}entries.push({name:entry.fileName,size:entry.uncompressedSize});zip.readEntry();});zip.on('end',()=>resolve(entries));zip.readEntry();});});}
const textTypes=/^(txt|md|json|jsonl|csv|tsv|html?|xml|py|js|jsx|ts|tsx|css|sql|yaml|yml|log|r|sh|java|c|cpp|h|rs|go|toml|ini|tex)$/;
export async function decodeFile(bytes:Buffer,name:string,mimeType:string,raw:unknown={}):Promise<{data:Record<string,unknown>;parts?:FilePart[]}>{
 const o=readOptions.parse(raw),ext=name.split('.').pop()?.toLowerCase()||'',mode=o.mode==='auto'?ext==='pdf'?'pdf':/^(png|jpe?g|webp|gif)$/.test(ext)?'image':/^(xlsx|csv|tsv)$/.test(ext)?'table':ext==='zip'?'archive':textTypes.test(ext)?'text':'auto':o.mode;
 if(bytes.length>10*1024*1024)throw Error('File exceeds the 10 MB reading limit.');
 const data={name,mimeType,size:bytes.length,mode};
 if(mode==='table'){
  let rows:unknown[][]=[],total=0,sheets:{name:string;rows:number;columns:number}[]=[],sheet=o.sheet||'',maxColumns=0;
  if(ext==='xlsx'){
   await archiveEntries(bytes);const workbook=new ExcelJS.Workbook();await workbook.xlsx.load(bytes as any);sheets=workbook.worksheets.map(s=>({name:s.name,rows:s.rowCount,columns:s.columnCount}));const ws=o.sheet?workbook.getWorksheet(o.sheet):workbook.worksheets[0];if(!ws)throw Error('Sheet not found. Available sheets: '+sheets.map(s=>s.name).join(', '));sheet=ws.name;total=ws.rowCount;maxColumns=ws.columnCount;
   for(let n=o.start;n<=Math.min(total,o.start+o.count-1);n++){const row:unknown[]=[];for(let c=o.column;c<=Math.min(maxColumns,o.column+o.columns-1);c++){const cell=ws.getRow(n).getCell(c),v=cell.value;row.push(v&&typeof v==='object'&&'formula'in v?{formula:v.formula,cachedResult:v.result??null}:cell.type===ExcelJS.ValueType.Hyperlink?{text:cell.text,hyperlink:(v as any).hyperlink}:cell.text.length>1000?cell.text.slice(0,1000):v instanceof Date?v.toISOString():typeof v==='object'&&v!==null?cell.text:v);}rows.push(row);}
  }else if(ext==='csv'||ext==='tsv'){
   const parsed=parse(bytes.toString('utf8'),{delimiter:ext==='tsv'?'\t':',',bom:true,relax_column_count:true,skip_empty_lines:false,max_record_size:100000}) as string[][];total=parsed.length;maxColumns=parsed.reduce((n,r)=>Math.max(n,r.length),0);rows=parsed.slice(o.start-1,o.start-1+o.count).map(r=>r.slice(o.column-1,o.column-1+o.columns).map(v=>v.slice(0,1000)));sheet=name;sheets=[{name,rows:total,columns:maxColumns}];
  }else throw Error('Structured tables support XLSX, CSV and TSV. Use auto for legacy XLS documents.');
  let used=0;const boundedRows:unknown[][]=[];for(const rawRow of rows){const row=rawRow.map(v=>{const text=JSON.stringify(v)??'null';return text.length>300?{truncated:true,preview:text.slice(0,260)}:v;});const size=JSON.stringify(row).length;if(used+size>18000)break;used+=size;boundedRows.push(row);}return {data:{...data,sheets,sheet,totalRows:total,totalColumns:maxColumns,startRow:o.start,startColumn:o.column,rows:boundedRows,nextRow:o.start+boundedRows.length<=total?o.start+boundedRows.length:null,nextColumn:o.column+o.columns<=maxColumns?o.column+o.columns:null,note:'Row and column numbers are one-based. Formulas are not executed; cached results may be stale. Truncated cell text is limited to 1000 characters. Request further ranges as needed.'}};
 }
 if(mode==='pdf'){
  const doc=await PDFDocument.load(bytes),total=doc.getPageCount();if(o.start>total)throw Error('Page number exceeds PDF page count.');const count=Math.min(o.count,10,total-o.start+1),slice=await PDFDocument.create(),pages=await slice.copyPages(doc,Array.from({length:count},(_,i)=>o.start-1+i));pages.forEach(p=>slice.addPage(p));const encoded=Buffer.from(await slice.save()).toString('base64');return {data:{...data,totalPages:total,startPage:o.start,endPage:o.start+count-1,nextPage:o.start+count<=total?o.start+count:null,note:'Selected PDF pages are supplied as multimodal input, including text and page images. Cite original page numbers.'},parts:[{type:'input_file',filename:name.replace(/\.pdf$/i,'')+'-pages.pdf',file_data:'data:application/pdf;base64,'+encoded}]};
 }
 if(mode==='image'){
  if(!/^(png|jpe?g|webp|gif)$/.test(ext))throw Error('Vision supports PNG, JPEG, WebP and GIF. Convert other image formats first.');return {data:{...data,note:'Inspect the attached image visually. Describe only visible evidence; state uncertainty for tiny text or ambiguous details.'},parts:[{type:'input_image',image_url:'data:image/'+(ext==='jpg'?'jpeg':ext)+';base64,'+bytes.toString('base64')}]};
 }
 if(mode==='text'){
  if(!textTypes.test(ext))throw Error('This is not a supported text format. Use auto or a suitable file reader.');const text=bytes.toString('utf8');if(text.includes('\u0000'))throw Error('Binary or non-UTF-8 text. Convert to UTF-8 first.');const lines=text.split(/\r?\n/),matching=o.query?lines.map((text,i)=>({line:i+1,text})).filter(r=>r.text.toLowerCase().includes(o.query!.toLowerCase())):lines.map((text,i)=>({line:i+1,text}));let length=0;const selected=matching.slice(o.start-1,o.start-1+o.count).map(r=>({...r,text:r.text.slice(0,4000)})).filter(r=>{length+=r.text.length;return length<=18000;});return {data:{...data,totalLines:lines.length,matches:matching.length,lines:selected,next:o.start+selected.length<=matching.length?o.start+selected.length:null,note:'With query, start indexes matching lines; line numbers refer to the original file. Long lines are clipped to 4000 characters.'}};
 }
 if(mode==='archive'){const entries=await archiveEntries(bytes);return {data:{...data,totalEntries:entries.length,entries:entries.slice(o.start-1,o.start-1+o.count),next:o.start+o.count<=entries.length?o.start+o.count:null,note:'Archive inventory only; entries are not extracted or executed.'}};}
 if(/^(docx?|pptx?|xls|odt|rtf)$/.test(ext)){if(/^(docx|pptx|odt)$/.test(ext))await archiveEntries(bytes);return {data:{...data,note:'Document supplied for text understanding. Embedded images/charts are not guaranteed to be visible; convert to PDF or upload those images separately. Legacy spreadsheet input may omit rows; convert to XLSX for exact ranged reading.'},parts:[{type:'input_file',filename:name,file_data:'data:'+mimeType+';base64,'+bytes.toString('base64')}]};}
 return {data:{...data,supported:false,note:'Stored but not decoded by this reader. Use an authorized sandbox with a suitable parser or convert the file. Audio/video and arbitrary binary formats are not automatically understood.'}};
}
export async function readUploadedFile(pageId:string,userId:string,fileId:string,options:unknown={}){
 if(!await getPage(pageId,userId))throw Error('Page context is inaccessible.');const file=(await contextFiles(pageId,userId)).find(f=>f.row.id===fileId);if(!file)throw Error('File is not attached to this page or is inaccessible.');const {row,data}=file;if(!String(data.location).startsWith('r2://FILES/uploads/'))throw Error('File contents unavailable.');if(data.size>10*1024*1024)throw Error('File exceeds the 10 MB reading limit.');const object=await (env as unknown as {FILES:R2Bucket}).FILES.get(data.location.slice('r2://FILES/'.length));if(!object)throw Error('File unavailable.');const result=await decodeFile(Buffer.from(await object.arrayBuffer()),row.display_name||data.fileName,data.mimeType||'application/octet-stream',options);return {...result,data:{...result.data,fileId,pageId,folderPath:row.folder_path||''}};
}
export async function listUploadedFiles(pageId:string,userId:string){if(!await getPage(pageId,userId))throw Error('Page context is inaccessible.');return listContextFiles(pageId,userId);}
