'use client';
import {useEffect,useRef,useState} from 'react';
import type {AnswerPage} from '@/app/page-types';
import type {HttpDefinition} from './http-contracts';
export function ApiRunner({page,onConfigured}:{page:AnswerPage;onConfigured:(page:AnswerPage)=>void}){
 const definition=page.component!.payload as {execution:string;baseUrl:string;authentication:string;http?:HttpDefinition};
 const [operation,setOperation]=useState(definition.http?.operations[0]?.name||''),[input,setInput]=useState('{}'),[result,setResult]=useState<unknown>(),[error,setError]=useState(''),[busy,setBusy]=useState(false),[editing,setEditing]=useState(false),[credential,setCredential]=useState(''),[confirmed,setConfirmed]=useState(false);
 const [configuration,setConfiguration]=useState(JSON.stringify(definition.http||{operations:[{name:'request',method:'GET',path:new URL(definition.baseUrl).pathname,parameters:[],response:'json'}]},null,2));
 const request=useRef<AbortController|null>(null);useEffect(()=>()=>request.current?.abort(),[]);
 const op=definition.http?.operations.find(o=>o.name===operation),writes=op&&op.method!=='GET';
 async function send(configure=false){setBusy(true);setError('');setResult(undefined);const c=new AbortController();request.current=c;try{const body=configure?{http:JSON.parse(configuration),...(credential.trim()?{credentialId:credential.trim()}:{})}:{operation,parameters:JSON.parse(input)};const response=await fetch('/api/components/'+encodeURIComponent(page.id)+(configure?'/configure-api':'/execute'),{method:'POST',headers:{'Content-Type':'application/json',...(!configure&&writes&&confirmed?{'X-Confirm-Api-Write':'yes'}:{})},body:JSON.stringify(body),signal:c.signal});const d=await response.json() as {error?:string;page:AnswerPage;result:unknown};if(!response.ok)throw new Error(d.error);if(configure)onConfigured(d.page);else setResult(d.result);}catch(e){if(!c.signal.aborted)setError(e instanceof Error?e.message:'API request failed.');}finally{setBusy(false);setConfirmed(false);}}
 return <section className="api-runner"><h2>API execution</h2>{definition.execution==='http'&&definition.http?<><label>Operation<select value={operation} onChange={e=>{setOperation(e.target.value);setConfirmed(false);}}>{definition.http.operations.map(o=><option key={o.name} value={o.name}>{o.name} · {o.method} {o.path}</option>)}</select></label><label>Parameters (JSON)<textarea value={input} onChange={e=>{setInput(e.target.value);setConfirmed(false);}} rows={4}/></label>{writes&&<label><input type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/> Confirm this {op.method} request to {new URL(definition.baseUrl).origin+op.path}</label>}<button disabled={busy||!!writes&&!confirmed} onClick={()=>void send()}>Run API request</button></>:<p>Configure the API’s HTTP operations before running it.</p>}{page.owned&&<><button disabled={busy} onClick={()=>setEditing(v=>!v)}>{editing?'Close configuration':'Configure HTTP operations'}</button>{editing&&<><label>HTTP definition (JSON)<textarea value={configuration} onChange={e=>setConfiguration(e.target.value)} rows={12}/></label>{definition.authentication!=='none'&&<label>Credential component ID<input value={credential} onChange={e=>setCredential(e.target.value)} placeholder="Reference only—never paste a secret"/></label>}<button disabled={busy} onClick={()=>void send(true)}>Save as a new API component</button></>}</>}{error&&<p role="alert">{error}</p>}{result!==undefined&&<pre>{JSON.stringify(result,null,2)}</pre>}<p className="api-policy-note">The server must enable this endpoint. Authenticated calls also require a secret binding and a policy granting you access.</p></section>;
}
