import {parse} from 'csv-parse/browser/esm/sync';
export type DataTable={columns:string[];rows:string[][]};
export function csvTable(text:string,delimiter=','):DataTable{const rows=parse(text,{bom:true,skip_empty_lines:true,relax_column_count:false,max_record_size:100000,delimiter}) as string[][];if(!rows.length)throw Error('No rows found.');if(rows.length>10001||rows[0].length>100)throw Error('Use up to 10,000 rows and 100 columns.');return {columns:rows[0],rows:rows.slice(1)};}
export function jsonTable(raw:unknown):DataTable{if(!Array.isArray(raw)||!raw.length||raw.length>10000||raw.some(r=>!r||typeof r!=='object'||Array.isArray(r)))throw Error('Use a JSON array of up to 10,000 records.');const columns=[...new Set(raw.flatMap(r=>Object.keys(r)))];if(columns.length>100)throw Error('Use up to 100 columns.');return {columns,rows:raw.map(r=>columns.map(k=>r[k]==null?'':typeof r[k]==='object'?JSON.stringify(r[k]):String(r[k])))};}
export function csvExport(table:DataTable){const escape=(raw:string)=>{const value=/^[\t\r\n ]*[=+@-]/.test(raw)?"'"+raw:raw;return /[",\r\n]/.test(value)?'"'+value.replaceAll('"','""')+'"':value;};return [table.columns,...table.rows].map(row=>row.map(escape).join(',')).join('\r\n');}
export type ZipEntry={name:string;size:number;compressed:number;method:number;offset:number;crc:number;directory:boolean};
export function zipEntries(bytes:Uint8Array):ZipEntry[]{
 const v=new DataView(bytes.buffer,bytes.byteOffset,bytes.byteLength),u16=(n:number)=>v.getUint16(n,true),u32=(n:number)=>v.getUint32(n,true);let end=-1;
 for(let i=bytes.length-22;i>=Math.max(0,bytes.length-65557);i--)if(u32(i)===0x06054b50&&i+22+u16(i+20)===bytes.length){end=i;break;}
 if(end<0)throw Error('Invalid ZIP archive.');if(u16(end+4)||u16(end+6)||u16(end+8)!==u16(end+10))throw Error('Multi-volume ZIP is unsupported.');const count=u16(end+10);if(count>1000)throw Error('Use an archive with up to 1,000 entries.');let pos=u32(end+16),total=0;const entries:ZipEntry[]=[];
 for(let i=0;i<count;i++){if(pos+46>end||u32(pos)!==0x02014b50)throw Error('Invalid ZIP directory.');if(u16(pos+8)&1)throw Error('Encrypted ZIP is unsupported.');const compressed=u32(pos+20),size=u32(pos+24),nameLength=u16(pos+28),extra=u16(pos+30),comment=u16(pos+32),offset=u32(pos+42);if(size===0xffffffff||offset===0xffffffff||compressed===0xffffffff)throw Error('ZIP64 is unsupported.');if((total+=size)>40*1024*1024||size>10*1024*1024)throw Error('ZIP exceeds the 40 MB expanded limit or 10 MB per entry.');if(pos+46+nameLength+extra+comment>end||offset+30>bytes.length)throw Error('Invalid ZIP entry.');const name=new TextDecoder().decode(bytes.subarray(pos+46,pos+46+nameLength));if(name.includes('\0')||name.split(/[\\/]/).includes('..')||/^[\\/]|^[A-Za-z]:/.test(name))throw Error('Unsafe archive path.');entries.push({name,size,compressed,offset,crc:u32(pos+16),method:u16(pos+10),directory:name.endsWith('/')});pos+=46+nameLength+extra+comment;}
 return entries;
}
export async function extractZip(bytes:Uint8Array,entry:ZipEntry){const v=new DataView(bytes.buffer,bytes.byteOffset,bytes.byteLength),p=entry.offset;if(v.getUint32(p,true)!==0x04034b50||v.getUint16(p+8,true)!==entry.method)throw Error('Invalid ZIP file header.');const start=p+30+v.getUint16(p+26,true)+v.getUint16(p+28,true);if(start+entry.compressed>bytes.length)throw Error('Truncated ZIP entry.');let output:Uint8Array;const compressed=bytes.slice(start,start+entry.compressed);
 if(entry.method===0)output=compressed;else if(entry.method===8){const reader=new Blob([compressed as BlobPart]).stream().pipeThrough(new DecompressionStream('deflate-raw')).getReader(),chunks:Uint8Array[]=[];let size=0;try{while(true){const r=await reader.read();if(r.done)break;if((size+=r.value.length)>entry.size||size>10*1024*1024)throw Error('ZIP entry exceeds its size limit.');chunks.push(r.value);}}finally{await reader.cancel().catch(()=>{});}output=new Uint8Array(size);let n=0;for(const c of chunks){output.set(c,n);n+=c.length;}}else throw Error('Only stored and Deflate ZIP entries are supported.');
 let crc=0xffffffff;for(const b of output){crc^=b;for(let j=0;j<8;j++)crc=(crc>>>1)^((crc&1)?0xedb88320:0);}if(output.length!==entry.size||((crc^0xffffffff)>>>0)!==entry.crc)throw Error('ZIP checksum failed.');return output;
}
