import type {AnswerPage} from '@/app/page-types';
export type SourceRef={page?:string;file?:string;connector?:string;name?:string;language?:string};
export function toolHref(app:string,source:SourceRef={}){const q=new URLSearchParams();for(const [k,v] of Object.entries(source))if(v)q.set(k,v);if(app!=='map')q.set('app',app);return (app==='map'?'/maps':'/tools')+'?'+q;}
export async function limitedBlob(response:Response){if(!response.ok)throw Error('File could not be read. Check your access and connection.');const reader=response.body?.getReader();if(!reader)throw Error('File is empty.');const chunks:Uint8Array[]=[];let size=0;try{while(true){const {done,value}=await reader.read();if(done)break;size+=value.byteLength;if(size>10*1024*1024)throw Error('Choose a file up to 10 MB.');chunks.push(value);}}finally{await reader.cancel().catch(()=>{});}return new Blob(chunks as BlobPart[],{type:response.headers.get('content-type')||'application/octet-stream'});}
export async function readSourceFile(source:SourceRef){if(!source.page||!source.file)throw Error('Choose a file first.');
 if(source.connector){const r=await fetch('/api/pages/'+encodeURIComponent(source.page)+'/adma',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({connectorId:source.connector,tool:'read_text_file',args:{file_id:source.file}})}),d=await r.json() as {error?:string;result?:{content?:string;contentType?:string}};if(!r.ok)throw Error(d.error||'ADMA read failed.');if(typeof d.result?.content!=='string')throw Error('ADMA returned no text content.');return new File([d.result.content],source.name||'data.json',{type:d.result.contentType||'text/plain'});}
 const r=await fetch('/api/pages/'+encodeURIComponent(source.page)+'/files'),d=await r.json() as {files?:{id:string;name:string;mimeType:string}[]};if(!r.ok)throw Error('Page files are inaccessible.');const file=d.files?.find(f=>f.id===source.file);if(!file)throw Error('File is not attached to this page or is inaccessible.');return new File([await limitedBlob(await fetch('/api/pages/'+encodeURIComponent(source.page)+'/files/'+encodeURIComponent(file.id)))],file.name,{type:file.mimeType});
}
export const nativeApps=[{id:'map',name:'Geo Viewer',description:'Visualize coordinates, geographic files and map services.'},{id:'table',name:'Table Studio',description:'Filter, sort and edit CSV, TSV and spreadsheet data.'},{id:'json',name:'JSON Studio',description:'Validate, format and explore JSON; convert records to CSV.'},{id:'text',name:'Text Studio',description:'Edit text and Markdown, find and replace, and export.'},{id:'image',name:'Image Studio',description:'Inspect, resize and rotate images; export PNG or JPEG.'},{id:'pdf',name:'PDF Viewer',description:'Read PDF documents inside this workspace.'},{id:'archive',name:'Archive Explorer',description:'Inspect ZIP contents and extract selected files locally.'}] as const;

export function nativePageSource(page:Pick<AnswerPage,'id'|'language'|'parameters'>):SourceRef{const p=page.parameters||{},str=(key:string)=>typeof p[key]==='string'?p[key] as string:undefined;return {page:str('sourcePage')||page.id,file:str('file'),connector:str('connector'),name:str('name'),language:page.language};}
