'use client';
import {useEffect,useRef,useState} from 'react';
import {ArrowLeft,Download,FileUp,Grid2X2,Search,RotateCw,ArrowUpDown} from 'lucide-react';
import {useUi} from '@/app/i18n/client';
import {nativeApps,readSourceFile,toolHref,type SourceRef} from './sources';
import {csvTable,jsonTable,csvExport,zipEntries,extractZip,type DataTable,type ZipEntry} from './data';
import './style.css';
export function Workbench({app='hub',source={}}:{app?:string;source?:SourceRef}){
 const {t}=useUi(),selectedApp=nativeApps.find(a=>a.id===app),fileInput=useRef<HTMLInputElement>(null),[file,setFile]=useState<File|null>(null),[text,setText]=useState(''),[error,setError]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[query,setQuery]=useState(''),[replace,setReplace]=useState(''),[table,setTable]=useState<DataTable|null>(null),[page,setPage]=useState(0),[sort,setSort]=useState<{column:number;desc:boolean}|null>(null),[objectUrl,setObjectUrl]=useState(''),[zip,setZip]=useState<{bytes:Uint8Array;entries:ZipEntry[]}|null>(null),[width,setWidth]=useState(800),[height,setHeight]=useState(600),[rotation,setRotation]=useState(0),[pageFiles,setPageFiles]=useState<{id:string;name:string}[]>([]);
 const [activeSource,setActiveSource]=useState(source);
 const alive=useRef(true);useEffect(()=>{alive.current=true;return()=>{alive.current=false;};},[]);
 useEffect(()=>{if(!file||!['image','pdf'].includes(app)){setObjectUrl('');return;}const url=URL.createObjectURL(file);setObjectUrl(url);return()=>URL.revokeObjectURL(url);},[file,app]);
 async function task(fn:()=>Promise<void>|void){setBusy(true);setError('');setMessage('');try{await fn();}catch(e){if(alive.current)setError(String(e));}finally{if(alive.current)setBusy(false);}}
 async function open(next:File,ref:SourceRef={page:source.page,language:source.language}){if(next.size>10*1024*1024)throw Error('Choose a file up to 10 MB.');setTable(null);setZip(null);setText('');setQuery('');setPage(0);setSort(null);setRotation(0);const ext=next.name.split('.').at(-1)?.toLowerCase();
 if(app==='image'){if(!['png','jpg','jpeg','webp','gif'].includes(ext||''))throw Error('Choose a PNG, JPEG, WebP or GIF image.');const bitmap=await createImageBitmap(next);setWidth(bitmap.width);setHeight(bitmap.height);bitmap.close();}
 else if(app==='pdf'){if(ext!=='pdf')throw Error('Choose a PDF document.');}
 else if(app==='archive'){if(ext!=='zip')throw Error('Choose a ZIP archive.');const bytes=new Uint8Array(await next.arrayBuffer());setZip({bytes,entries:zipEntries(bytes)});}
 else if(app==='table'&&ext==='xlsx'){const bytes=new Uint8Array(await next.arrayBuffer());zipEntries(bytes);const {default:ExcelJS}=await import('exceljs');const wb=new ExcelJS.Workbook();await wb.xlsx.load(bytes as any);const ws=wb.worksheets[0];if(!ws||ws.rowCount>10001||ws.columnCount>100)throw Error('First sheet must have at most 10,000 data rows and 100 columns.');const rows:string[][]=[];ws.eachRow({includeEmpty:true},row=>rows.push(Array.from({length:ws.columnCount},(_,i)=>row.getCell(i+1).text)));setTable({columns:rows[0]||[],rows:rows.slice(1)});setMessage(t('Opened the first worksheet. Formulas are not executed; values may be cached.'));}
 else {if(!['txt','md','csv','tsv','json','geojson','xml','kml','gpx','log','yaml','yml','html','css','js','py'].includes(ext||''))throw Error('Choose a supported text file.');const value=await next.text();if(value.includes('\0'))throw Error('File is not UTF-8 text.');setText(value);if(app==='table')setTable(ext==='json'?jsonTable(JSON.parse(value)):csvTable(value,ext==='tsv'?'\t':','));}
 setFile(next);setActiveSource(ref);
 }
 const initial=useRef('');useEffect(()=>{const key=JSON.stringify(source)+app;if(source.file&&selectedApp&&initial.current!==key){initial.current=key;void task(async()=>open(await readSourceFile(source),source));}},[source.page,source.file,source.connector,app]);
 useEffect(()=>{let active=true;if(source.page)fetch('/api/pages/'+encodeURIComponent(source.page)+'/files').then(async r=>{if(!r.ok)throw Error('Page files are inaccessible.');const d=await r.json() as {files:{id:string;name:string}[]};if(active)setPageFiles(d.files);}).catch(e=>{if(active)setError(String(e));});return()=>{active=false;};},[source.page]);
 function download(content:BlobPart,name:string,type='text/plain'){const url=URL.createObjectURL(new Blob([content],{type})),a=document.createElement('a');a.href=url;a.download=name.replace(/[\\/]/g,'_');a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
 function exportText(){download(text,file?.name||('document.'+(app==='json'?'json':'txt')),app==='json'?'application/json':'text/plain');}
 async function exportImage(type:string){if(!file)return;if(!Number.isInteger(width)||!Number.isInteger(height)||width<1||height<1||width*height>16000000||width>8000||height>8000)throw Error('Use dimensions up to 8,000 pixels and 16 megapixels.');const bitmap=await createImageBitmap(file),canvas=document.createElement('canvas'),swap=rotation%180!==0;canvas.width=swap?height:width;canvas.height=swap?width:height;const ctx=canvas.getContext('2d')!;if(type==='image/jpeg'){ctx.fillStyle='white';ctx.fillRect(0,0,canvas.width,canvas.height);}ctx.translate(canvas.width/2,canvas.height/2);ctx.rotate(rotation*Math.PI/180);ctx.drawImage(bitmap,-width/2,-height/2,width,height);bitmap.close();const blob=await new Promise<Blob>((resolve,reject)=>canvas.toBlob(b=>b?resolve(b):reject(Error('Image export failed.')),type,.92));download(blob,(file.name.replace(/\.[^.]+$/,'')||'image')+(type==='image/png'?'.png':'.jpg'),type);}
 const rows=table?table.rows.map((row,index)=>({row,index})).filter(({row})=>!query||row.some(v=>v.toLowerCase().includes(query.toLowerCase()))):[];if(sort)rows.sort((a,b)=>a.row[sort.column].localeCompare(b.row[sort.column],undefined,{numeric:true})*(sort.desc?-1:1));
 return <section className={'tool-app tool-'+app}><header className="tool-header"><a href={source.page?'/?page='+encodeURIComponent(source.page):'/'}><ArrowLeft size={17}/>{t('Back to page')}</a><h1>{t(selectedApp?.name||'Native apps')}</h1><a href={toolHref('hub',activeSource)}><Grid2X2 size={17}/>{t('All apps')}</a></header>
 <nav className="tool-links" aria-label={t('Related apps')}>{nativeApps.map(a=><a key={a.id} href={toolHref(a.id,activeSource)} aria-current={app===a.id?'page':undefined}>{t(a.name)}</a>)}</nav>
 {!selectedApp?<div className="tool-hub"><h2>{t('Choose a tool for your data')}</h2><p>{t('Open page files in connected tools. Each app checks access to the original file.')}</p><div>{nativeApps.map(a=><a key={a.id} href={toolHref(a.id,activeSource)}><strong>{t(a.name)}</strong><span>{t(a.description)}</span></a>)}</div></div>:<><div className="tool-actions"><button disabled={busy} onClick={()=>fileInput.current?.click()}><FileUp size={17}/>{t('Open local file')}</button><input type="file" hidden ref={fileInput} accept={app==='image'?'.png,.jpg,.jpeg,.webp,.gif':app==='pdf'?'.pdf':app==='archive'?'.zip':app==='table'?'.csv,.tsv,.json,.xlsx':app==='json'?'.json,.geojson':'.txt,.md,.csv,.tsv,.json,.xml,.kml,.gpx,.log,.yaml,.yml,.html,.css,.js,.py'} onChange={e=>{const next=e.target.files?.[0];e.target.value='';if(next)void task(()=>open(next));}}/>{pageFiles.length>0&&<select aria-label={t('Page files')} disabled={busy} value="" onChange={e=>{if(e.target.value)void task(async()=>open(await readSourceFile({...source,file:e.target.value,connector:undefined}),{...source,file:e.target.value,connector:undefined}));}}><option value="">{t('Choose a page file')}</option>{pageFiles.map(f=><option key={f.id} value={f.id}>{f.name}</option>)}</select>}<strong>{file?.name||t('No file selected')}</strong></div>
 <div className="tool-workspace">
 {app==='table'&&<>{table?<><div className="tool-actions"><Search size={17}/><input aria-label={t('Filter rows')} placeholder={t('Filter rows')} value={query} onChange={e=>{setQuery(e.target.value);setPage(0);}}/><span>{rows.length} {t('rows')}</span><button onClick={()=>download(csvExport({...table,rows:rows.map(r=>r.row)}),'export.csv','text/csv')}><Download size={16}/>{t('Export CSV')}</button><button onClick={()=>download(JSON.stringify(rows.map(r=>Object.fromEntries(table.columns.map((k,i)=>[k,r.row[i]]))),null,2),'export.json','application/json')}>{t('Export JSON')}</button><a href={toolHref('map',activeSource)}>{t('View on map')}</a></div><div className="tool-table-scroll"><table><thead><tr>{table.columns.map((c,i)=><th key={i}><button onClick={()=>setSort({column:i,desc:sort?.column===i?!sort.desc:false})}>{c}<ArrowUpDown size={12}/></button></th>)}</tr></thead><tbody>{rows.slice(page*100,page*100+100).map(({row,index})=><tr key={index}>{row.map((cell,c)=><td key={c}><input aria-label={table.columns[c]+' '+(index+2)} value={cell} onChange={e=>setTable(old=>old?{...old,rows:old.rows.map((r,i)=>i===index?r.map((v,j)=>j===c?e.target.value:v):r)}:old)}/></td>)}</tr>)}</tbody></table></div><div className="tool-actions"><button disabled={page===0} onClick={()=>setPage(p=>p-1)}>{t('Previous')}</button><span>{page+1} / {Math.max(1,Math.ceil(rows.length/100))}</span><button disabled={(page+1)*100>=rows.length} onClick={()=>setPage(p=>p+1)}>{t('Next')}</button></div></>:<p>{t('Open CSV, TSV, a JSON array, or an XLSX workbook to begin.')}</p>}</>}
 {app==='json'&&<><div className="tool-actions"><button onClick={()=>void task(()=>{setText(JSON.stringify(JSON.parse(text),null,2));setMessage(t('Valid JSON'));})}>{t('Format and validate')}</button><button onClick={()=>void task(()=>setText(JSON.stringify(JSON.parse(text))))}>{t('Minify')}</button><button onClick={()=>void task(()=>download(csvExport(jsonTable(JSON.parse(text))),'records.csv','text/csv'))}>{t('Convert to CSV')}</button><button onClick={exportText}>{t('Download')}</button></div><textarea className="tool-editor" aria-label={t('JSON editor')} spellCheck={false} value={text} onChange={e=>setText(e.target.value)} placeholder={'{\n  "data": []\n}'}/></>}
 {app==='text'&&<><div className="tool-actions"><input aria-label={t('Find text')} placeholder={t('Find text')} value={query} onChange={e=>setQuery(e.target.value)}/><input aria-label={t('Replace with')} placeholder={t('Replace with')} value={replace} onChange={e=>setReplace(e.target.value)}/><button disabled={!query} onClick={()=>setText(v=>v.split(query).join(replace))}>{t('Replace all')}</button><button onClick={exportText}><Download size={16}/>{t('Download')}</button><span>{text.length} {t('characters')} · {text.split('\n').length} {t('lines')}</span></div><textarea className="tool-editor" aria-label={t('Text editor')} spellCheck value={text} onChange={e=>setText(e.target.value)}/></>}
 {app==='image'&&<><div className="tool-actions"><label>{t('Width')}<input aria-label={t('Width')} type="number" min="1" max="8000" value={width} onChange={e=>setWidth(Number(e.target.value))}/></label><label>{t('Height')}<input aria-label={t('Height')} type="number" min="1" max="8000" value={height} onChange={e=>setHeight(Number(e.target.value))}/></label><button disabled={!file} onClick={()=>setRotation(v=>(v+90)%360)}><RotateCw size={16}/>{t('Rotate')}</button><button disabled={!file||busy} onClick={()=>void task(()=>exportImage('image/png'))}>PNG</button><button disabled={!file||busy} onClick={()=>void task(()=>exportImage('image/jpeg'))}>JPEG</button></div><div className="tool-image-stage">{objectUrl?<img src={objectUrl} alt={file?.name||''} style={{transform:'rotate('+rotation+'deg)',maxWidth:rotation%180?'50%':'90%',maxHeight:450}}/>:<p>{t('Open an image to inspect or resize it.')}</p>}</div><p>{t('Exports use the chosen dimensions. Animated images export as a still frame.')}</p></>}
 {app==='pdf'&&(objectUrl?<><iframe className="tool-pdf-frame" src={objectUrl} title={file?.name||'PDF'}/><a href={objectUrl} download={file?.name}>{t('Download PDF')}</a></>:<p>{t('Open a PDF document to read it here.')}</p>)}
 {app==='archive'&&(zip?<><p>{zip.entries.length} {t('entries')}</p><div className="tool-archive-list">{zip.entries.map((entry,i)=><div key={i}><span>{entry.directory?'▰':'▤'} {entry.name}</span><small>{entry.size.toLocaleString()} B</small><button disabled={busy||entry.directory} onClick={()=>void task(async()=>download(await extractZip(zip.bytes,entry) as BlobPart,entry.name.split('/').at(-1)||'file','application/octet-stream'))}>{t('Extract file')}</button></div>)}</div></>:<p>{t('Open a ZIP archive to inspect and extract files locally.')}</p>)}
 </div><p className="tool-note">{t('Changes stay in this tab. Download your result before leaving; the original file is unchanged.')}</p></>}
 {busy&&<p role="status">{t('Loading…')}</p>}{error&&<p role="alert">{error}</p>}{message&&<p role="status">{message}</p>}
 </section>;
}
