import {folderPath,fileName} from '@/app/context-files/tree';
import {env} from '@/server/runtime';import {getActor} from '@/app/actor';import {reply,database,sameOrigin} from '@/db/store';import {contextFiles} from '@/app/context-files/server';
export async function GET(request:Request,{params}:{params:Promise<{id:string;fileId:string}>}){const a=await getActor(request);try{const {id,fileId}=await params,file=(await contextFiles(id,a.userId)).find(f=>f.row.id===fileId);if(!file||!String(file.data.location).startsWith('r2://FILES/uploads/'))return a.finish(reply({error:'File unavailable.'},404));const object=await (env as unknown as {FILES:R2Bucket}).FILES.get(file.data.location.slice('r2://FILES/'.length));if(!object)return a.finish(reply({error:'File unavailable.'},404));const inline=new URL(request.url).searchParams.get('inline')==='1';const extension=String(file.data.fileName).split('.').pop()?.toLowerCase()||'';
 const types:Record<string,string>={png:'image/png',jpg:'image/jpeg',jpeg:'image/jpeg',gif:'image/gif',webp:'image/webp',svg:'image/svg+xml',mp4:'video/mp4',webm:'video/webm',ogg:'video/ogg'};
 const type=inline?types[extension]:undefined;
 const headers:Record<string,string>={'Content-Type':type||'application/octet-stream','Content-Disposition':(type?'inline':'attachment')+"; filename*=UTF-8''"+encodeURIComponent(file.row.display_name||file.data.fileName),'Cache-Control':'no-store, private','Vary':'Cookie','X-Content-Type-Options':'nosniff',...(type==='image/svg+xml'?{'Content-Security-Policy':"default-src 'none'; style-src 'unsafe-inline'; img-src data:"}:{})};
 if(type&&type.startsWith('video/')){const bytes=await object.arrayBuffer(),range=request.headers.get('range')?.match(/^bytes=(\d+)-(\d*)$/);headers['Accept-Ranges']='bytes';if(range){const start=Number(range[1]),end=Math.min(range[2]?Number(range[2]):bytes.byteLength-1,bytes.byteLength-1);if(start>end||start>=bytes.byteLength)return new Response(null,{status:416,headers:{'Content-Range':'bytes */'+bytes.byteLength}});headers['Content-Range']=`bytes ${start}-${end}/${bytes.byteLength}`;headers['Content-Length']=String(end-start+1);return a.finish(new Response(bytes.slice(start,end+1),{status:206,headers}));}return a.finish(new Response(bytes,{headers}));}
 return a.finish(new Response(object.body,{headers}));}catch{return a.finish(reply({error:'Could not open file.'},503));}}
export async function DELETE(request:Request,{params}:{params:Promise<{id:string;fileId:string}>}){const a=await getActor(request);if(!sameOrigin(request))return a.finish(reply({error:'Invalid origin.'},403));const {id,fileId}=await params;const result=await database().prepare("DELETE FROM page_files WHERE id=? AND page_id=? AND EXISTS(SELECT 1 FROM pages p WHERE p.id=page_files.page_id AND (p.visibility='public' OR p.owner_id=?)) AND ((scope<>'' AND owner_id=?) OR (scope='' AND EXISTS(SELECT 1 FROM pages p WHERE p.id=page_files.page_id AND (p.owner_id=? OR (p.visibility='public' AND p.public_write=1)))))").bind(fileId,id,a.userId,a.userId,a.userId).run();return a.finish(reply(result.meta.changes?{removed:true}:{error:'File unavailable.'},result.meta.changes?200:404));}

export async function PATCH(request:Request,{params}:{params:Promise<{id:string;fileId:string}>}){const actor=await getActor(request);if(!sameOrigin(request))return actor.finish(reply({error:'Invalid origin.'},403));try{
 const {id,fileId}=await params,data=await request.json() as {folderPath?:unknown;name?:unknown};const path=folderPath(data.folderPath),name=fileName(data.name);
 const r=await database().prepare("UPDATE page_files SET folder_path=?,display_name=? WHERE id=? AND page_id=? AND EXISTS(SELECT 1 FROM pages p WHERE p.id=page_files.page_id AND (p.visibility='public' OR p.owner_id=?)) AND ((scope<>'' AND owner_id=?) OR (scope='' AND EXISTS(SELECT 1 FROM pages p WHERE p.id=page_files.page_id AND (p.owner_id=? OR (p.visibility='public' AND p.public_write=1)))))").bind(path,name,fileId,id,actor.userId,actor.userId,actor.userId).run();return actor.finish(reply(r.meta.changes?{saved:true}:{error:'File unavailable.'},r.meta.changes?200:403));
 }catch(error){return actor.finish(reply({error:error instanceof Error?error.message:'Could not update file.'},400));}}
