import {askAgent,spawnAgent,recordAction,type Agent} from '@/app/agents/runtime';
import {createComponent,type AgentContext} from '@/app/components-registry/registry';
import {formSchema,validateParameters,parametersSchema} from '@/app/components-registry/contracts';
import {codeSchema} from './contracts';
import {runProgram,sandboxStatus} from './service';
import type {DynamicConfig,ConverterLabels} from '@/app/dynamic/units';
export async function composeBackend(question:string,context:AgentContext,router:Agent,signal?:AbortSignal){
 const status=sandboxStatus(context.userId);if(!status.configured||!status.allowed)throw new Error('SANDBOX_NOT_CONFIGURED');
 const coder=router,ctx={...context,agent:coder};
 let feedback='';
 for(let attempt=0;attempt<2;attempt++){
  const d=await askAgent(coder,'Implement a complete server-backed form application in language '+context.language+'. Return formJson {kind:"form",submit:string,fields:[{name,label,type:"number"|"text",default:null}],outputs:[{name,label}]}. ProgramJson is {kind:"sandbox-program",language:"javascript"|"python",code:string}. Use requested language or choose the best. JavaScript exports async function main(input); Python defines main(input). Return an object whose scalar fields match every output name. Use loops, standard-library imports and algorithms as needed. Runtime is Linux with Node/Python, no network, packages beyond standard library, persistent state or secrets. Validate inputs and bound work to 30 seconds. Never fake unavailable APIs. Return at least two distinct independently calculated examples in examplesJson [{input:{...},output:{...}}]. frontendQuestion describes interface; backendQuestion describes reusable algorithm without example-specific inputs.',{question,feedback},{type:'object',additionalProperties:false,properties:{title:{type:'string'},summary:{type:'string'},formJson:{type:'string'},programJson:{type:'string'},examplesJson:{type:'string'},frontendQuestion:{type:'string'},backendQuestion:{type:'string'}},required:['title','summary','formJson','programJson','examplesJson','frontendQuestion','backendQuestion']},signal,undefined,[],{context,reasoningEffort:'medium'});
  try{const form=formSchema.parse(JSON.parse(d.formJson)),program=codeSchema.parse(JSON.parse(d.programJson)),examples=JSON.parse(d.examplesJson);if(!Array.isArray(examples)||examples.length<2||examples.length>4||new Set(examples.map(e=>JSON.stringify(e.input))).size<2)throw new Error('Provide two to four independent test cases');
   for(const example of examples){const input=validateParameters(form,example.input),execution=await runProgram(program,input,ctx);if(!execution.ok)throw new Error(execution.stderr);const actual=parametersSchema.parse(execution.result),expected=parametersSchema.parse(example.output);for(const o of form.outputs){const a=actual[o.name],b=expected[o.name];if(!Object.hasOwn(actual,o.name)||!Object.hasOwn(expected,o.name)||(typeof a==='number'?(typeof b!=='number'||Math.abs(a-b)>1e-8*Math.max(1,Math.abs(b))):a!==b))throw new Error('Program output did not match expected example');}}
   const frontend=await createComponent(d.frontendQuestion,'frontend_template',form,ctx),backend=await createComponent(d.backendQuestion,'backend_code',program,ctx);
   if(JSON.stringify(JSON.parse(frontend.payload))!==JSON.stringify(form)||JSON.stringify(JSON.parse(backend.payload))!==JSON.stringify(program))throw new Error('An existing component has a different implementation. Use a more precise component question.');
   const workflow=await createComponent(d.backendQuestion+' — workflow','workflow',{kind:'workflow',steps:[{name:'run',component:{id:backend.id,version:backend.version}}]},ctx);
   const config:DynamicConfig={template:'component-form-v1',executor:'component-workflow-v1',version:1,capability:'application',labels:{overview:context.language.startsWith('zh')?'概述':'Overview',invalid:context.language.startsWith('zh')?'执行失败，请检查输入或沙箱配置。':'Execution failed. Check the inputs or sandbox configuration.'} as ConverterLabels,components:{frontend:{id:frontend.id,version:frontend.version},workflow:{id:workflow.id,version:workflow.version}},form};
   await recordAction(router,'Receive tested backend application',{frontend:frontend.id,backend:backend.id,workflow:workflow.id,executedExamples:examples.length});return {title:String(d.title).slice(0,200),summary:String(d.summary).slice(0,800),config,parameters:{},components:[{role:'frontend',component:frontend},{role:'workflow',component:workflow}]};
  }catch(error){feedback=error instanceof Error?error.message.slice(0,2000):'Validation failed';await recordAction(coder,'Runtime validation failed',{feedback});if(feedback.startsWith('SANDBOX_'))throw error;}
 }
 throw new Error('APPLICATION_VALIDATION_FAILED');
}
