'use client';
import {useDismissFloating} from '@/app/use-dismiss-floating';
import {useUi} from '@/app/i18n/client';
import {useEffect,useState,useRef} from 'react';
type Status={configured:boolean;desktopConfigured:boolean;provider:string;allowed:boolean;internet:boolean;sessions:{id:string;expiresAt:number}[]};
export function SandboxPanel(){
 const {t,locale}=useUi();

 const surface=useRef<HTMLElement>(null),trigger=useRef<HTMLButtonElement>(null);
 const [open,setOpen]=useState(false),[status,setStatus]=useState<Status|null>(null),[tab,setTab]=useState<'code'|'desktop'>('code'),[busy,setBusy]=useState(false),[error,setError]=useState(''),[result,setResult]=useState(''),[language,setLanguage]=useState<'javascript'|'python'>('javascript'),[code,setCode]=useState('export async function main(input) {\n  return { result: input.value * 2 };\n}'),[input,setInput]=useState('{"value":21}'),[session,setSession]=useState(''),[image,setImage]=useState(''),[task,setTask]=useState(''),[text,setText]=useState('');
 const url=useRef('');
 async function request(path:string,body?:unknown,method='POST'){const r=await fetch(path,{method,headers:body?{'Content-Type':'application/json'}:undefined,body:body?JSON.stringify(body):undefined});const d=await r.json() as any;if(!r.ok)throw Error(d.error||'Request failed');return d;}
 async function load(){try{const d=await request('/api/sandboxes',undefined,'GET');setStatus(d);if(!session&&d.sessions[0])setSession(d.sessions[0].id);}catch(e){setError(String(e));}}
 async function screen(id=session){if(!id)return;const r=await fetch('/api/sandboxes/'+id);if(!r.ok)throw Error('Desktop expired or unavailable.');const next=URL.createObjectURL(await r.blob());if(url.current)URL.revokeObjectURL(url.current);url.current=next;setImage(next);}
 useEffect(()=>{if(open)void load();},[open]);
 useEffect(()=>{if(session&&open&&tab==='desktop')void screen().catch(e=>setError(e.message));},[session,open,tab]);
 useEffect(()=>()=>{if(url.current)URL.revokeObjectURL(url.current);},[]);
 async function perform(fn:()=>Promise<void>){setBusy(true);setError('');try{await fn();}catch(e){setError(e instanceof Error?e.message:'Request failed');}finally{setBusy(false);}}
 const enabled=!!status?.configured&&!!status.allowed,desktopEnabled=!!status?.desktopConfigured&&!!status.allowed;
 const action=(action:unknown)=>perform(async()=>{await request('/api/sandboxes/'+session,{action});await screen();});
 useDismissFloating(open,surface,()=>setOpen(false),trigger);
 return <><button ref={trigger} className="upload-data" onClick={()=>setOpen(!open)} aria-expanded={open}>{t("Sandboxes")}</button>{open&&<aside ref={surface} className="sandbox-panel" aria-label={t("Code and desktop sandboxes")}><header><h2>{t("Sandboxes")}</h2><button onClick={()=>setOpen(false)} aria-label={t("Close sandbox panel")}>×</button></header><div className="sandbox-tabs"><button aria-pressed={tab==='code'} onClick={()=>setTab('code')}>{t("JavaScript / Python")}</button><button aria-pressed={tab==='desktop'} onClick={()=>setTab('desktop')}>{t("Desktop")}</button><button onClick={()=>void load()}>{t("Refresh connection")}</button></div>
  {status&&!status.allowed&&<p>{t("Sign in with an authorized account to use sandboxes.")}</p>}{tab==='code'&&<p className="sandbox-note">{t("Backend execution: OpenAI-hosted sandbox.")}</p>}{status&&tab==='code'&&!status.configured&&<p>{t("Connect OpenAI to enable backend execution.")}</p>}{status&&tab==='desktop'&&!status.desktopConfigured&&<p>{t("Desktop computer use requires a separate E2B connection. OpenAI runs the web-app backend code.")}</p>}
  {error&&<p className="request-error" role="alert">{t(error)}</p>}
  {tab==='code'?<><label>{t("Language")}<select value={language} onChange={e=>{const l=e.target.value as typeof language;setLanguage(l);setCode(l==='python'?'def main(input):\n    return {"result": input["value"] * 2}':'export async function main(input) {\n  return { result: input.value * 2 };\n}');}}><option value="javascript">{t("JavaScript (Node.js)")}</option><option value="python">{t("Python")}</option></select></label><label>{t("Backend program")}<textarea rows={10} value={code} onChange={e=>setCode(e.target.value)} spellCheck={false}/></label><label>{t("Input JSON")}<textarea rows={2} value={input} onChange={e=>setInput(e.target.value)} spellCheck={false}/></label><button disabled={!enabled||busy} onClick={()=>void perform(async()=>{const d=await request('/api/sandboxes/run',{program:{kind:'sandbox-program',language,code},input:JSON.parse(input)});setResult(JSON.stringify(d,null,2));})}>{busy?t("Running…"):t("Run in isolated sandbox")}</button><p className="sandbox-note">{t("30-second program limit. Sandbox setup may take longer. Cleanup is requested after each run.")}</p>{result&&<pre>{result}</pre>}</>:<>
  <div className="sandbox-tabs"><button disabled={!desktopEnabled||busy} onClick={()=>void perform(async()=>{const d=await request('/api/sandboxes');setSession(d.id);setImage('');await load();})}>{t("New desktop")}</button>{status?.sessions.length? <select aria-label={t("Active desktop")} value={session} onChange={e=>{setSession(e.target.value);setImage('');}}>{status.sessions.map(s=><option value={s.id} key={s.id}>{s.id.slice(0,8)}{t("· expires")}{new Date(s.expiresAt).toLocaleTimeString(locale)}</option>)}</select>:null}<button disabled={!session||busy} onClick={()=>void perform(()=>screen())}>{t("Screenshot")}</button><button disabled={!session} onClick={()=>void perform(async()=>{await request('/api/sandboxes/'+session,undefined,'DELETE');setSession('');setImage('');await load();})}>{t("Stop desktop")}</button></div>
  <p className="sandbox-note">{t("Private 10-minute session · Internet")}{status?.internet?t("enabled"):t("disabled")}{t(". Click the screenshot to click the desktop.")}</p>
  {image&&<img className="desktop-screen" src={image} alt={t("Current private sandbox desktop")} onClick={e=>{if(busy)return;const r=e.currentTarget.getBoundingClientRect();void action({type:'click',x:Math.min(1023,Math.floor((e.clientX-r.left)/r.width*1024)),y:Math.min(767,Math.floor((e.clientY-r.top)/r.height*768)),button:'left'});}}/>}
  {session&&<><div className="sandbox-tabs">{(['browser','editor','terminal'] as const).map(application=><button disabled={busy} key={application} onClick={()=>void action({type:'launch',application})}>{application}</button>)}<button disabled={busy} onClick={()=>void action({type:'press',keys:['Return']})}>{t("Enter")}</button><button disabled={busy} onClick={()=>void action({type:'press',keys:['Tab']})}>{t("Tab")}</button></div><label>{t("Type into desktop")}<input value={text} onChange={e=>setText(e.target.value)}/></label><button disabled={busy||!text} onClick={()=>void action({type:'type',text})}>{t("Type text")}</button><label>{t("Task for the computer-use agent")}<textarea rows={3} value={task} onChange={e=>setTask(e.target.value)} placeholder={t("Open the text editor and write a short note.")}/></label><button disabled={busy||!task} onClick={()=>void perform(async()=>{const d=await request('/api/sandboxes/'+session,{task});setResult(d.message);await screen();})}>{busy?t("Agent working…"):t("Run up to six actions")}</button>{result&&<p aria-live="polite">{result}</p>}</>}
  </>}
 </aside>}</>;
}
