import {getActor} from '@/app/actor';import {finishOAuth} from '@/app/storage/oauth';import {providerSchema} from '@/app/storage/contracts';import {isEarthEngineState,finishEarthEngine,EE_COOKIE} from '@/app/earth-engine/oauth';
export async function GET(r:Request,{params}:{params:Promise<{provider:string}>}){const a=await getActor(r),url=new URL(r.url);
 // The Earth Engine connector shares the Google OAuth client and this registered redirect.
 if((await params).provider==='google'&&await isEarthEngineState(a.userId,url.searchParams.get('state')||''))return a.finish(await earthEngineCallback(r,a.userId,url));
let path='/',result='failed',provider='';try{provider=providerSchema.parse((await params).provider);const prefix='agenticwiki_storage_'+provider+'=',cookie=r.headers.get('cookie')?.split(';').map(s=>s.trim()).find(s=>s.startsWith(prefix))?.slice(prefix.length)||'';path=await finishOAuth(providerSchema.parse(provider),a.userId,url.searchParams.get('state')||'',cookie,url.searchParams.get('code')||'',url.searchParams.has('error'));result=url.searchParams.has('error')?'cancelled':'connected';}catch{}const target=new URL(path,process.env.APP_URL||url.origin);target.searchParams.set('storage',result);const headers:Record<string,string>={Location:target.toString(),'Cache-Control':'no-store','Referrer-Policy':'no-referrer'};if(provider)headers['Set-Cookie']='agenticwiki_storage_'+provider+'=; Path=/api/storage/'+provider+'; HttpOnly; SameSite=Lax; Max-Age=0'+(new URL(process.env.APP_URL||r.url).protocol==='https:'?'; Secure':'');return a.finish(new Response(null,{status:303,headers}));}

async function earthEngineCallback(r:Request,userId:string,url:URL){
 let path='/',status='failed';
 try{const prefix=EE_COOKIE+'=',cookie=r.headers.get('cookie')?.split(';').map(s=>s.trim()).find(s=>s.startsWith(prefix))?.slice(prefix.length)||'';const done=await finishEarthEngine(userId,url.searchParams.get('state')||'',cookie,url.searchParams.get('code')||'',url.searchParams.has('error'));path=done.returnTo;status=done.status;}catch(e){console.error('earth engine connect failed',e instanceof Error?e.message:e);}
 const target=new URL(path,process.env.APP_URL||url.origin);target.searchParams.set('earthengine',status);
 return new Response(null,{status:303,headers:{Location:target.toString(),'Cache-Control':'no-store','Referrer-Policy':'no-referrer','Set-Cookie':EE_COOKIE+'=; Path=/api/storage/google; HttpOnly; SameSite=Lax; Max-Age=0'+(target.protocol==='https:'?'; Secure':'')}});
}
