import {isFileOnlyScope} from '@/app/storage/google-scope';
import {requireStorageTool} from '@/app/connectors/storage-policy';
import {env} from '@/server/runtime';
import {lock,unlock} from '@/db/store';
import {DRIVE_SCOPE,encryptSecret,decryptSecret,userSecretPath,safeReturnTo,folderListUrl,validateOAuthState} from './crypto';
const setting=(name:string)=>(env as unknown as Record<string,string>)[name]||process.env[name]||'';
const bucket=()=>{const b=(env as unknown as {FILES?:R2Bucket}).FILES;if(!b)throw new Error('GOOGLE_DRIVE_STORAGE_UNAVAILABLE');return b;};
function config(){const clientId=setting('GOOGLE_CLIENT_ID'),clientSecret=setting('GOOGLE_CLIENT_SECRET'),key=setting('GOOGLE_TOKEN_ENCRYPTION_KEY');let valid=false;try{valid=atob(key).length===32;}catch{}return {clientId,clientSecret,key,configured:!!clientId&&!!clientSecret&&valid};}
function requireUser(userId:string){if(userId.startsWith('guest:'))throw new Error('GOOGLE_DRIVE_SIGN_IN_REQUIRED');}
async function read(path:string){const object=await bucket().get(path);return object?decryptSecret(await object.text(),config().key,path):null;}
async function write(path:string,value:unknown){await bucket().put(path,await encryptSecret(value,config().key,path),{httpMetadata:{contentType:'application/octet-stream'}});}
export async function connectionStatus(userId:string){const configured=config().configured;if(userId.startsWith('guest:')||!configured)return {configured,connected:false,signedIn:!userId.startsWith('guest:')};const token=await read(await userSecretPath(userId));return {configured,connected:!!token&&token.ownerId===userId&&isFileOnlyScope(token.scope),signedIn:true};}
export async function beginConnection(userId:string,origin:string,returnTo:unknown){requireUser(userId);const c=config();if(!c.configured)throw new Error('GOOGLE_DRIVE_SETUP_REQUIRED');const state=crypto.randomUUID(),verifier=Array.from(crypto.getRandomValues(new Uint8Array(32)),v=>v.toString(16).padStart(2,'0')).join(''),challenge=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(verifier)),redirectUri=(process.env.APP_URL||origin)+'/api/connections/google-drive/callback';
 await write('secrets/google-drive-state/'+state,{ownerId:userId,verifier,redirectUri,returnTo:safeReturnTo(returnTo),expires:Date.now()+600000});
 const url=new URL('https://accounts.google.com/o/oauth2/v2/auth');url.search=new URLSearchParams({client_id:c.clientId,redirect_uri:redirectUri,response_type:'code',scope:DRIVE_SCOPE,access_type:'offline',prompt:'consent',state,code_challenge:btoa(String.fromCharCode(...new Uint8Array(challenge))).replaceAll('+','-').replaceAll('/','_').replaceAll('=',''),code_challenge_method:'S256'}).toString();return {url:url.toString(),state};}
async function exchange(values:Record<string,string>){const c=config();const r=await fetch('https://oauth2.googleapis.com/token',{method:'POST',redirect:'error',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams({client_id:c.clientId,client_secret:c.clientSecret,...values}),signal:AbortSignal.timeout(20000)});if(!r.ok)throw new Error('GOOGLE_DRIVE_RECONNECT_REQUIRED');return await r.json() as {access_token?:string;refresh_token?:string;expires_in?:number;scope?:string};}
export async function finishConnection(userId:string,state:string,cookieState:string,code:string){requireUser(userId);if(!/^[a-f0-9-]{36}$/.test(state)||state!==cookieState||!code||code.length>4000)throw new Error('GOOGLE_DRIVE_INVALID_STATE');const lease=await lock('google-oauth:'+state,60000);if(!lease)throw new Error('GOOGLE_DRIVE_INVALID_STATE');
 try{const path='secrets/google-drive-state/'+state,pending=await read(path);validateOAuthState(pending,userId,state,cookieState);await bucket().delete(path);const token=await exchange({grant_type:'authorization_code',code,redirect_uri:pending.redirectUri,code_verifier:pending.verifier});if(!token.access_token||!token.refresh_token||!isFileOnlyScope(token.scope))throw new Error('GOOGLE_DRIVE_PERMISSION_REQUIRED');
 await write(await userSecretPath(userId),{ownerId:userId,accessToken:token.access_token,refreshToken:token.refresh_token,scope:token.scope,expires:Date.now()+(token.expires_in||3600)*1000});return pending.returnTo as string;
 }finally{await unlock(lease);}}
async function accessToken(userId:string){requireUser(userId);if(!config().configured)throw new Error('GOOGLE_DRIVE_SETUP_REQUIRED');const path=await userSecretPath(userId),token=await read(path);if(!token||token.ownerId!==userId||!isFileOnlyScope(token.scope))throw new Error('GOOGLE_DRIVE_CONNECT_REQUIRED');if(token.expires>Date.now()+60000)return String(token.accessToken);
 const lease=await lock('google-refresh:'+userId,30000);if(!lease)throw new Error('GOOGLE_DRIVE_BUSY');try{const result=await exchange({grant_type:'refresh_token',refresh_token:token.refreshToken});if(!result.access_token)throw new Error('GOOGLE_DRIVE_RECONNECT_REQUIRED');await write(path,{...token,accessToken:result.access_token,refreshToken:result.refresh_token||token.refreshToken,expires:Date.now()+(result.expires_in||3600)*1000});return result.access_token;}finally{await unlock(lease);}}
export async function listFolders(userId:string,pageToken?:string){await requireStorageTool(userId,'google','list');if(pageToken&&pageToken.length>3000)throw new Error('GOOGLE_DRIVE_INVALID_CURSOR');const token=await accessToken(userId),r=await fetch(folderListUrl(pageToken),{headers:{Authorization:'Bearer '+token},redirect:'error',signal:AbortSignal.timeout(20000)});if(!r.ok)throw new Error(r.status===401?'GOOGLE_DRIVE_RECONNECT_REQUIRED':'GOOGLE_DRIVE_LIST_FAILED');const data=await r.json() as {files?:{id:string;name:string;modifiedTime?:string;parents?:string[];webViewLink?:string}[];nextPageToken?:string;incompleteSearch?:boolean};return {folders:(data.files||[]).map(f=>({id:f.id,name:f.name,modifiedTime:f.modifiedTime,parents:f.parents||[],url:'https://drive.google.com/drive/folders/'+encodeURIComponent(f.id)})),nextPageToken:data.nextPageToken||null,incomplete:!!data.incompleteSearch};}
export async function disconnect(userId:string){requireUser(userId);const path=await userSecretPath(userId),token=await read(path);if(token?.ownerId===userId){const r=await fetch('https://oauth2.googleapis.com/revoke',{method:'POST',redirect:'error',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams({token:token.refreshToken}),signal:AbortSignal.timeout(20000)});if(!r.ok&&r.status!==400)throw new Error('GOOGLE_DRIVE_DISCONNECT_FAILED');}await bucket().delete(path);}

export async function cancelConnection(userId:string,state:string,cookieState:string){requireUser(userId);if(!/^[a-f0-9-]{36}$/.test(state)||state!==cookieState)throw new Error('GOOGLE_DRIVE_INVALID_STATE');const path='secrets/google-drive-state/'+state,pending=await read(path);validateOAuthState(pending,userId,state,cookieState);await bucket().delete(path);return safeReturnTo(pending.returnTo);}
