'use client';
import {useEffect,useMemo,useState} from 'react';
import {Activity,Braces,Clock3,File,Folder,Play,RefreshCw,Search,Server,Square,Terminal} from 'lucide-react';
import {useUi} from '@/app/i18n/client';
import './style.css';
type Account={id:string;name:string;allowed:string[]};type Job={id:string;name:string;state:string;partition:string;elapsed:string;timeLimit:string;nodes:number;reason:string};type Entry={name:string;kind:'file'|'folder';size:number;modified:string};
const starter=`#!/bin/bash\n#SBATCH --job-name=agenticwiki-job\n#SBATCH --time=00:10:00\n#SBATCH --mem=2G\n#SBATCH --cpus-per-task=1\n#SBATCH --output=slurm-%j.out\n\nset -euo pipefail\necho "Started on $(hostname) at $(date)"\n# module load <software>\n# Replace this line with your computation\nsleep 10\necho "Finished at $(date)"\n`;
export function HccApp({pageId,writable}:{pageId:string;writable:boolean}){
 const {t}=useUi(),endpoint='/api/pages/'+encodeURIComponent(pageId)+'/hcc',[accounts,setAccounts]=useState<Account[]>([]),[account,setAccount]=useState(''),[tab,setTab]=useState<'jobs'|'submit'|'files'|'software'>('jobs'),[jobs,setJobs]=useState<Job[]>([]),[files,setFiles]=useState<Entry[]>([]),[path,setPath]=useState('~'),[script,setScript]=useState(starter),[work,setWork]=useState('~/agenticwiki-jobs'),[scriptName,setScriptName]=useState('job.submit'),[moduleQuery,setModuleQuery]=useState(''),[modules,setModules]=useState<string[]>([]),[details,setDetails]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');
 const connection=accounts.find(a=>a.id===account),can=(name:string)=>!!connection?.allowed.includes(name);
 async function call(tool:string,args:Record<string,unknown>={},confirm=false){const r=await fetch(endpoint,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({connectorId:account,tool,args,confirm})}),d=await r.json() as any;if(!r.ok)throw Error(d.error||'UNL HCC request failed.');if(d.result?.confirmationRequired)throw Error('Enable this tool in Connectors.');return d.result;}
 async function task(fn:()=>Promise<void>){setBusy(true);setError('');setNotice('');try{await fn();}catch(e){setError(e instanceof Error?e.message:String(e));}finally{setBusy(false);}}
 async function loadJobs(){const r=await call('list_jobs',{limit:200});setJobs(r.jobs||[]);}
 async function loadFiles(next=path){const r=await call('list_files',{path:next,limit:300});setPath(next);setFiles(r.items||[]);}
 useEffect(()=>{let live=true;fetch(endpoint).then(r=>r.json()).then((d:any)=>{if(!live)return;if(d.error)throw Error(d.error);setAccounts(d.accounts||[]);setAccount(d.accounts?.[0]?.id||'');}).catch(e=>live&&setError(String(e)));return()=>{live=false;};},[endpoint]);
 useEffect(()=>{if(!account)return;void task(loadJobs);},[account]);
 const parent=useMemo(()=>path==='~'?'~':path.replace(/\/+$/,'').replace(/\/[^/]+$/,'')||'/',[path]);
 return <section className="hcc-app">
  <header className="hcc-top"><div className="hcc-brand"><span className="hcc-n">N</span><div><strong>UNL Holland Computing Center</strong><small>Swan · Slurm workspace</small></div></div><label>{t('Account')}<select value={account} disabled={busy} onChange={e=>setAccount(e.target.value)}>{accounts.map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select></label><a href="https://swan-ood.unl.edu" target="_blank" rel="noreferrer">Open OnDemand ↗</a></header>
  {!account?<div className="hcc-empty"><Server size={42}/><h2>{t('Connect UNL HCC')}</h2><p>{t('Add and enable the UNL HCC connector to manage Swan jobs and files here.')}</p></div>:<><nav className="hcc-tabs">{([['jobs',Activity,'Jobs'],['submit',Play,'Submit job'],['files',Folder,'Files'],['software',Braces,'Software']] as const).map(([id,Icon,label])=><button key={id} aria-current={tab===id?'page':undefined} onClick={()=>{setTab(id);if(id==='files'&&!files.length)void task(()=>loadFiles());}}><Icon size={17}/>{t(label)}</button>)}</nav>
  {tab==='jobs'&&<div className="hcc-panel"><div className="hcc-panel-head"><div><h2>{t('Slurm jobs')}</h2><p>{t('Current jobs for the connected HCC account')}</p></div><button disabled={busy||!can('list_jobs')} onClick={()=>void task(loadJobs)}><RefreshCw size={16}/>{t('Refresh')}</button></div><div className="hcc-job-table"><div className="hcc-row hcc-columns"><span>ID</span><span>{t('Name')}</span><span>{t('State')}</span><span>{t('Partition')}</span><span>{t('Elapsed')}</span><span>{t('Actions')}</span></div>{jobs.map(j=><div className="hcc-row" key={j.id}><code>{j.id}</code><strong>{j.name}</strong><span><i className={'hcc-state '+j.state.toLowerCase()}/>{j.state}</span><span>{j.partition}</span><span>{j.elapsed} / {j.timeLimit}</span><span><button disabled={busy||!can('job_details')} onClick={()=>void task(async()=>setDetails((await call('job_details',{job_id:j.id})).details))}>{t('Details')}</button><button className="hcc-stop" disabled={busy||!writable||!can('cancel_job')} onClick={()=>{if(confirm(t('Cancel this Slurm job?')))void task(async()=>{await call('cancel_job',{job_id:j.id},true);setNotice(t('Job cancelled.'));await loadJobs();});}}><Square size={12}/>{t('Cancel')}</button></span></div>)}{!jobs.length&&!busy&&<p className="hcc-zero">{t('No active Slurm jobs.')}</p>}</div>{details&&<aside className="hcc-details"><button onClick={()=>setDetails('')}>×</button><h3>{t('Job details')}</h3><pre>{details}</pre></aside>}</div>}
  {tab==='submit'&&<div className="hcc-submit"><div><h2>{t('Submit a Slurm job')}</h2><p>{t('Review the script and requested resources before submitting.')}</p><label>{t('Working directory')}<input value={work} onChange={e=>setWork(e.target.value)}/></label><label>{t('Script name')}<input value={scriptName} onChange={e=>setScriptName(e.target.value)}/></label><button disabled={busy||!writable||!can('submit_job')} onClick={()=>void task(async()=>{const r=await call('submit_job',{script,working_directory:work,script_name:scriptName},true);setNotice(t('Submitted Slurm job')+' '+r.jobId);setTab('jobs');await loadJobs();})}><Play size={16}/>{t('Submit job')}</button>{!writable&&<p>{t('Fork this page to submit jobs from your private workspace.')}</p>}</div><div className="hcc-editor"><div><Terminal size={15}/><span>{scriptName}</span></div><textarea spellCheck={false} value={script} onChange={e=>setScript(e.target.value)}/></div></div>}
  {tab==='files'&&<div className="hcc-panel"><div className="hcc-panel-head"><div><h2>{t('Swan files')}</h2><form onSubmit={e=>{e.preventDefault();void task(()=>loadFiles(path));}}><input value={path} onChange={e=>setPath(e.target.value)}/><button disabled={busy||!can('list_files')}>{t('Open')}</button></form></div><button disabled={busy||path==='~'} onClick={()=>void task(()=>loadFiles(parent))}>↑ {t('Parent')}</button></div><div className="hcc-files">{files.map(item=><button key={item.name} onClick={()=>item.kind==='folder'?void task(()=>loadFiles(path.replace(/\/$/,'')+'/'+item.name)):void task(async()=>setDetails((await call('read_text_file',{path:path.replace(/\/$/,'')+'/'+item.name,limit:50000})).content))}>{item.kind==='folder'?<Folder size={21}/>:<File size={21}/>}<strong>{item.name}</strong><small>{item.kind==='file'?item.size.toLocaleString()+' B':t('Folder')}</small><time>{item.modified?.slice(0,19)}</time></button>)}</div>{details&&<aside className="hcc-details"><button onClick={()=>setDetails('')}>×</button><h3>{t('File preview')}</h3><pre>{details}</pre></aside>}</div>}
  {tab==='software'&&<div className="hcc-panel"><div className="hcc-panel-head"><div><h2>{t('Software modules')}</h2><p>{t('Search modules available on Swan')}</p></div></div><form className="hcc-module-search" onSubmit={e=>{e.preventDefault();void task(async()=>setModules((await call('search_modules',{query:moduleQuery})).results||[]));}}><Search size={17}/><input required value={moduleQuery} onChange={e=>setModuleQuery(e.target.value)} placeholder="python, matlab, gcc…"/><button disabled={busy||!can('search_modules')}>{t('Search')}</button></form><pre className="hcc-module-results">{modules.join('\n')}</pre></div>}</>}
  {busy&&<p className="hcc-status"><Clock3 size={15}/>{t('Working…')}</p>}{notice&&<p className="hcc-notice">{notice}</p>}{error&&<p role="alert" className="hcc-error">{error}</p>}
 </section>;
}
