'use client';
import {useEffect,useRef,useState} from 'react';
import {useUi} from '@/app/i18n/client';
import './style.css';
type Account={id:string;name:string;allowed:string[]};
type Item={id:string;name:string;is_public:boolean;file_type?:string;file_size?:number;created_at?:string;kind:'file'|'folder'};
export function AdmaApp({pageId,writable}:{pageId:string;writable:boolean}){
 const {t}=useUi(),[accounts,setAccounts]=useState<Account[]>([]),[account,setAccount]=useState(''),[items,setItems]=useState<Item[]>([]),[trail,setTrail]=useState<Item[]>([]),[query,setQuery]=useState(''),[grid,setGrid]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState(''),[selected,setSelected]=useState<Item|null>(null),[detail,setDetail]=useState(''),[name,setName]=useState(''),[newName,setNewName]=useState(''),[confirmDelete,setConfirmDelete]=useState(false);
 const sequence=useRef(0),upload=useRef<HTMLInputElement>(null),folder=trail.at(-1)?.id,connection=accounts.find(a=>a.id===account),can=(tool:string)=>!!connection?.allowed.includes(tool),endpoint='/api/pages/'+encodeURIComponent(pageId)+'/adma';
 async function call(tool:string,args:Record<string,unknown>,confirm=false){const r=await fetch(endpoint,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({connectorId:account,tool,args,confirm})});const d=await r.json() as {error?:string;result?:any;accounts?:Account[]};if(!r.ok)throw Error(d.error||'ADMA request failed.');if(d.result?.confirmationRequired)throw Error('Enable this tool in Connectors.');return d.result;}
 async function load(){const version=++sequence.current;setBusy(true);setError('');setSelected(null);setDetail('');try{const [files,folders]=await Promise.all([can('list_files')?call('list_files',folder?{folder_id:folder}:{}):Promise.resolve({files:[]}),can('list_folders')?call('list_folders',folder?{parent_id:folder}:{}):Promise.resolve({folders:[]})]);if(version!==sequence.current)return;setItems([...(folders.folders||[]).map((x:Item)=>({...x,kind:'folder'})),...(files.files||[]).map((x:Item)=>({...x,kind:'file'}))]);}catch(e){if(version===sequence.current){setError(String(e));setItems([]);}}finally{if(version===sequence.current)setBusy(false);}}
 useEffect(()=>{let active=true;setItems([]);setAccounts([]);setAccount('');fetch(endpoint).then(async r=>{const d=await r.json() as {error?:string;result?:any;accounts?:Account[]};if(!r.ok)throw Error(d.error);if(active){setAccounts(d.accounts||[]);setAccount(d.accounts?.[0]?.id||'');}}).catch(e=>{if(active)setError(String(e));});return()=>{active=false;++sequence.current;};},[endpoint]);
 useEffect(()=>{setItems([]);if(account)void load();return()=>{++sequence.current;};},[account,folder]);
 async function change(tool:string,args:Record<string,unknown>){setBusy(true);setError('');try{await call(tool,args,true);setConfirmDelete(false);setNewName('');await load();}catch(e){setError(String(e));}finally{setBusy(false);}}
 async function inspect(item:Item){setSelected(item);setName(item.name);setDetail('');setConfirmDelete(false);const tool=item.kind==='folder'?'folder_info':'file_metadata';if(!can(tool))return;try{const result=await call(tool,item.kind==='folder'?{folder_id:item.id}:{file_id:item.id});setDetail(JSON.stringify(result,null,2));}catch(e){setError(String(e));}}
 const visible=items.filter(x=>x.name.toLocaleLowerCase().includes(query.toLocaleLowerCase())).sort((a,b)=>a.kind===b.kind?a.name.localeCompare(b.name):a.kind==='folder'?-1:1);
 return <section className="adma-app" aria-label="ADMA"><header><div className="adma-brand">AD<span>MA</span></div><div><h2>{t('Data workspace')}</h2><p>{t('Files and folders in your ADMA account')}</p></div><a href="https://adma.aisoup.net/dashboard/" target="_blank" rel="noreferrer">{t('Open in ADMA')} ↗</a></header>
 {!account?<p>{t('Enable your ADMA connection in Connectors to browse your files.')}</p>:<><div className="adma-toolbar">{accounts.length>1&&<select aria-label={t('Account')} value={account} onChange={e=>{setTrail([]);setAccount(e.target.value);}}>{accounts.map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select>}<input aria-label={t('Search files')} placeholder={t('Search files')} value={query} onChange={e=>setQuery(e.target.value)}/><button disabled={busy} onClick={()=>void load()}>{t('Refresh')}</button><button aria-pressed={grid} onClick={()=>setGrid(!grid)}>{grid?t('List view'):t('Grid view')}</button></div>
 <nav className="adma-trail" aria-label={t('Folders')}><button onClick={()=>setTrail([])}>{t('All my items')}</button>{trail.map((x,i)=><span key={x.id}> / <button onClick={()=>setTrail(trail.slice(0,i+1))}>{x.name}</button></span>)}</nav><p className="adma-hint">{folder?t('Showing this folder’s contents.'):t('ADMA shows root folders and all your files here, including files in nested folders.')}</p>
 {(!can('list_files')||!can('list_folders'))&&<p>{t('Enable list_files and list_folders in Connectors to browse all items.')}</p>}
 {writable&&<div className="adma-toolbar"><input aria-label={t('New folder name')} placeholder={t('New folder name')} value={newName} onChange={e=>setNewName(e.target.value)}/><button disabled={busy||!newName.trim()||!can('create_folder')} onClick={()=>void change('create_folder',{name:newName.trim(),...(folder?{parent_id:folder}:{})})}>{t('New folder')}</button><button disabled={busy||!can('upload_text_file')} onClick={()=>upload.current?.click()}>{t('Upload text / CSV / JSON')}</button><input hidden ref={upload} type="file" accept=".txt,.csv,.tsv,.json,.geojson,.md,.xml" onChange={e=>{const file=e.target.files?.[0];e.target.value='';if(!file)return;if(file.size>48000){setError(t('Choose a text file up to 48 KB.'));return;}void file.text().then(content=>change('upload_text_file',{filename:file.name,content,...(folder?{folder_id:folder}:{})})).catch(e=>setError(String(e)));}}/></div>}
 <div className={'adma-items '+(grid?'adma-grid':'adma-list')} aria-busy={busy}>{visible.map(item=><article key={item.kind+item.id}><button className="adma-item" onClick={()=>item.kind==='folder'?(setTrail([...trail,item]),setQuery('')):void inspect(item)}><span className={item.kind==='folder'?'adma-folder':'adma-file'} aria-hidden="true">{item.kind==='folder'?'▰':'▤'}</span><strong>{item.name}</strong><small>{item.kind==='folder'?t('Folder'):item.file_type||t('File')} · {item.is_public?t('Public'):t('Private')}</small></button><button className="adma-details" onClick={()=>void inspect(item)}>{t('Details')}</button></article>)}</div>
 {!busy&&!visible.length&&<p>{t('No items found.')}</p>}
 {selected&&<aside className="adma-inspector"><button className="adma-close" onClick={()=>{setSelected(null);setConfirmDelete(false);}}>{t('Close')}</button><h3>{selected.name}</h3><a target="_blank" rel="noreferrer" href={'https://adma.aisoup.net/'+selected.kind+'/'+encodeURIComponent(selected.id)+'/'}>{t('Open in ADMA')} ↗</a>{detail&&<details><summary>{t('Metadata')}</summary><pre>{detail}</pre></details>}{selected.kind==='file'&&can('read_text_file')&&<button disabled={busy} onClick={()=>{setBusy(true);void call('read_text_file',{file_id:selected.id}).then(r=>setDetail(typeof r==='string'?r:JSON.stringify(r,null,2))).catch(e=>setError(String(e))).finally(()=>setBusy(false));}}>{t('Read text file')}</button>}
 {writable&&<><div className="adma-toolbar"><input aria-label={t('Name')} value={name} onChange={e=>setName(e.target.value)}/><button disabled={busy||!name.trim()||!can('update_'+selected.kind)} onClick={()=>void change('update_'+selected.kind,{id:selected.id,name:name.trim()})}>{t('Rename')}</button><button disabled={busy||!can('update_'+selected.kind)} onClick={()=>void change('update_'+selected.kind,{id:selected.id,is_public:!selected.is_public})}>{selected.is_public?t('Make private'):t('Make public')}</button></div>{confirmDelete?<div role="alert"><p>{t('Permanently delete this item? Folder contents are also deleted. This cannot be undone.')}</p><button disabled={busy} onClick={()=>void change('delete_'+selected.kind,{id:selected.id})}>{t('Confirm permanent deletion')}</button><button onClick={()=>setConfirmDelete(false)}>{t('Cancel')}</button></div>:<button disabled={busy||!can('delete_'+selected.kind)} onClick={()=>setConfirmDelete(true)}>{t('Delete permanently')}</button>}</>}
 </aside>}
 <p className="adma-hint">{t('Additional actions require their tools to be checked in Connectors. Use ADMA for binary uploads, downloads, maps and processing tools.')}</p></>}
 {busy&&<p role="status">{t('Loading…')}</p>}{error&&<p role="alert">{error}</p>}
 </section>;
}
