'use client';
import {useEffect,useRef,useState} from 'react';
import {Cloud,Sprout,LayoutDashboard,Map,Wrench,BookOpen,Folder,File,Database,Globe,HardDrive,Search,Upload,ExternalLink,Grid2X2,List} from 'lucide-react';
import {toolHref} from '@/app/tools/sources';
import {useUi} from '@/app/i18n/client';
import './style.css';
type Account={id:string;name:string;allowed:string[]};
type Item={id:string;name:string;is_public:boolean;file_type?:string;file_size?:number;created_at?:string;kind:'file'|'folder';thirdPartySource?:string};
export function AdmaApp({pageId,writable}:{pageId:string;writable:boolean}){
 const {t,locale}=useUi(),[catalog,setCatalog]=useState<Item[]>([]),[catalogError,setCatalogError]=useState(''),[accounts,setAccounts]=useState<Account[]>([]),[account,setAccount]=useState(''),[items,setItems]=useState<Item[]>([]),[trail,setTrail]=useState<Item[]>([]),[query,setQuery]=useState(''),[grid,setGrid]=useState(false),[busy,setBusy]=useState(false),[loaded,setLoaded]=useState(false),[error,setError]=useState(''),[selected,setSelected]=useState<Item|null>(null),[detail,setDetail]=useState(''),[name,setName]=useState(''),[newName,setNewName]=useState(''),[confirmDelete,setConfirmDelete]=useState(false);
 const sequence=useRef(0),upload=useRef<HTMLInputElement>(null),folder=trail.at(-1)?.id,connection=accounts.find(a=>a.id===account),can=(tool:string)=>!!connection?.allowed.includes(tool),endpoint='/api/pages/'+encodeURIComponent(pageId)+'/adma';
 async function call(tool:string,args:Record<string,unknown>,confirm=false){const r=await fetch(endpoint,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({connectorId:account,tool,args,confirm})});const d=await r.json() as {error?:string;result?:any;accounts?:Account[]};if(!r.ok)throw Error(d.error||'ADMA request failed.');if(d.result?.confirmationRequired)throw Error('Enable this tool in Connectors.');return d.result;}
 async function load(){const version=++sequence.current;setBusy(true);setError('');setSelected(null);setDetail('');try{const [files,folders]=await Promise.all([can('list_files')?call('list_files',folder?{folder_id:folder}:{}):Promise.resolve({files:[]}),can('list_folders')?call('list_folders',folder?{parent_id:folder}:{}):Promise.resolve({folders:[]})]);if(version!==sequence.current)return;setLoaded(true);setItems([...(folders.folders||[]).map((x:Item)=>({...x,kind:'folder',thirdPartySource:trail.at(-1)?.thirdPartySource})),...(files.files||[]).map((x:Item)=>({...x,kind:'file',thirdPartySource:trail.at(-1)?.thirdPartySource}))]);}catch(e){if(version===sequence.current){setLoaded(false);setError(String(e));setItems([]);}}finally{if(version===sequence.current)setBusy(false);}}
 useEffect(()=>{let active=true;setItems([]);setAccounts([]);setAccount('');fetch(endpoint).then(async r=>{const d=await r.json() as {error?:string;result?:any;accounts?:Account[]};if(!r.ok)throw Error(d.error);if(active){setAccounts(d.accounts||[]);setAccount(d.accounts?.[0]?.id||'');}}).catch(e=>{if(active)setError(String(e));});return()=>{active=false;++sequence.current;};},[endpoint]);
 useEffect(()=>{setItems([]);setLoaded(false);if(account)void load();return()=>{++sequence.current;};},[account,folder]);
 useEffect(()=>{let active=true;setCatalog([]);setCatalogError('');if(account)fetch(endpoint+'?catalog=third-party&connector='+encodeURIComponent(account)).then(async r=>{const d=await r.json() as {items:Item[];error?:string};if(!r.ok)throw Error(d.error||'Could not load third-party data.');if(active)setCatalog(d.items);}).catch(e=>{if(active)setCatalogError(String(e));});return()=>{active=false;};},[account,endpoint]);
 async function change(tool:string,args:Record<string,unknown>){setBusy(true);setError('');try{await call(tool,args,true);setConfirmDelete(false);setNewName('');await load();}catch(e){setError(String(e));}finally{setBusy(false);}}
 async function inspect(item:Item){setSelected(item);setName(item.name);setDetail('');setConfirmDelete(false);const tool=item.kind==='folder'?'folder_info':'file_metadata';if(!can(tool))return;try{const result=await call(tool,item.kind==='folder'?{folder_id:item.id}:{file_id:item.id});setDetail(JSON.stringify(result,null,2));}catch(e){setError(String(e));}}
 const visible=items.filter(x=>x.name.toLocaleLowerCase().includes(query.toLocaleLowerCase())).sort((a,b)=>a.kind===b.kind?a.name.localeCompare(b.name):a.kind==='folder'?-1:1);
 const mapHref='/maps?'+new URLSearchParams({page:pageId,language:locale,connector:account});
 const stats=[{label:t('Files in view'),value:items.filter(x=>x.kind==='file').length,Icon:File},{label:t('Folders in view'),value:items.filter(x=>x.kind==='folder').length,Icon:Folder},{label:t('Public files in view'),value:items.filter(x=>x.kind==='file'&&x.is_public).length,Icon:Globe},{label:t('File size in view'),value:(items.filter(x=>x.kind==='file').reduce((n,x)=>n+(Number(x.file_size)||0),0)/1048576).toFixed(1)+' MB',Icon:HardDrive}];
 return <section className="adma-app" aria-label="ADMA"><nav className="adma-navigation" aria-label={t('ADMA navigation')}><a className="adma-brand" href="https://adma.aisoup.net/dashboard/" target="_blank" rel="noreferrer"><Sprout size={27}/>ADMA</a><button aria-current="page" onClick={()=>{setTrail([]);setQuery('');}}><LayoutDashboard size={17}/>{t('Dashboard')}</button><a href={mapHref}><Map size={17}/>{t('Maps')}</a><a href={toolHref('hub',{page:pageId,language:locale})}><Wrench size={17}/>{t('Tools')}<ExternalLink size={12}/></a><a href="https://adma.aisoup.net/documentation/" target="_blank" rel="noreferrer"><BookOpen size={17}/>{t('Documentation')}<ExternalLink size={12}/></a></nav>
 <div className="adma-dashboard"><header className="adma-welcome"><div><h2>{t('Welcome to your ADMA dashboard')}</h2><p>{t('Manage your agricultural data files and folders')}</p></div><a href="https://adma.aisoup.net/dashboard/" target="_blank" rel="noreferrer">{t('Open in ADMA')} <ExternalLink size={15}/></a></header><div className="adma-statistics">{stats.map(({label,value,Icon})=><div className="adma-stat" key={label}><strong>{loaded?value:'—'}</strong><span><Icon size={17}/>{label}</span></div>)}</div>
 {!account?<p>{t('Enable your ADMA connection in Connectors to browse your files.')}</p>:<><section className="adma-data-card"><div className="adma-card-heading"><h3><Database size={19}/>{t('Data')}</h3><button aria-pressed={grid} onClick={()=>setGrid(!grid)}>{grid?<List size={17}/>:<Grid2X2 size={17}/>} {grid?t('List view'):t('Grid view')}</button></div><div className="adma-card-body"><div className="adma-toolbar">{accounts.length>1&&<select aria-label={t('Account')} value={account} onChange={e=>{setTrail([]);setAccount(e.target.value);}}>{accounts.map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select>}<Search size={18}/><input aria-label={t('Search files')} placeholder={t('Search files')} value={query} onChange={e=>setQuery(e.target.value)}/><button disabled={busy} onClick={()=>void load()}>{t('Refresh')}</button></div>
 <nav className="adma-trail" aria-label={t('Folders')}><button onClick={()=>setTrail([])}>{t('All my items')}</button>{trail.map((x,i)=><span key={x.id}> / <button onClick={()=>setTrail(trail.slice(0,i+1))}>{x.name}</button></span>)}</nav><p className="adma-hint">{folder?t('Showing this folder’s contents.'):t('ADMA shows root folders and all your files here, including files in nested folders.')}</p>
 {(!can('list_files')||!can('list_folders'))&&<p>{t('Enable list_files and list_folders in Connectors to browse all items.')}</p>}
 {writable&&!trail.at(-1)?.thirdPartySource&&<div className="adma-toolbar"><input aria-label={t('New folder name')} placeholder={t('New folder name')} value={newName} onChange={e=>setNewName(e.target.value)}/><button disabled={busy||!newName.trim()||!can('create_folder')} onClick={()=>void change('create_folder',{name:newName.trim(),...(folder?{parent_id:folder}:{})})}>{t('New folder')}</button><button disabled={busy||!can('upload_text_file')} onClick={()=>upload.current?.click()}>{t('Upload text / CSV / JSON')}</button><input hidden ref={upload} type="file" accept=".txt,.csv,.tsv,.json,.geojson,.md,.xml" onChange={e=>{const file=e.target.files?.[0];e.target.value='';if(!file)return;if(file.size>48000){setError(t('Choose a text file up to 48 KB.'));return;}void file.text().then(content=>change('upload_text_file',{filename:file.name,content,...(folder?{folder_id:folder}:{})})).catch(e=>setError(String(e)));}}/></div>}
 <div className={'adma-items '+(grid?'adma-grid':'adma-list')} aria-busy={busy}>{visible.map(item=><article key={item.kind+item.id}><button className="adma-item" onClick={()=>item.kind==='folder'?(setTrail([...trail,item]),setQuery('')):void inspect(item)}><span className={item.kind==='folder'?'adma-folder':'adma-file'} aria-hidden="true">{item.kind==='folder'?<Folder size={28} fill="currentColor" strokeWidth={1}/>:<File size={26}/>}</span><strong>{item.name}</strong><small>{item.kind==='folder'?t('Folder'):item.file_type||t('File')} · {item.is_public?t('Public'):t('Private')}</small></button><button className="adma-details" onClick={()=>void inspect(item)}>{t('Details')}</button></article>)}</div>
 {loaded&&!busy&&!error&&!visible.length&&<div className="adma-empty"><Folder size={48}/><h3>{t('No items found.')}</h3><p>{query?t('Try another search.'):t('Your connected ADMA account has no items in this view.')}</p></div>}
 {selected&&<aside className="adma-inspector"><button className="adma-close" onClick={()=>{setSelected(null);setConfirmDelete(false);}}>{t('Close')}</button><h3>{selected.name}</h3><a target="_blank" rel="noreferrer" href={'https://adma.aisoup.net/'+selected.kind+'/'+encodeURIComponent(selected.id)+'/'}>{t('Open in ADMA')} ↗</a>{selected.kind==='file'&&/\.(geojson|json|csv|tsv|kml|gpx)$/i.test(selected.name)&&<a className="adma-map-link" href={mapHref+'&file='+encodeURIComponent(selected.id)+'&name='+encodeURIComponent(selected.name)}><Map size={16}/>{t('View on map')}</a>}{selected.kind==='file'&&can('read_text_file')&&/\.(json|geojson|csv|tsv|txt|md|xml|kml|gpx|log|yaml|yml)$/i.test(selected.name)&&<a className="adma-map-link" href={toolHref('hub',{page:pageId,connector:account,file:selected.id,name:selected.name,language:locale})}>{t('Open with…')}</a>}{detail&&<details><summary>{t('Metadata')}</summary><pre>{detail}</pre></details>}{selected.kind==='file'&&can('read_text_file')&&<button disabled={busy} onClick={()=>{setBusy(true);void call('read_text_file',{file_id:selected.id}).then(r=>setDetail(typeof r==='string'?r:JSON.stringify(r,null,2))).catch(e=>setError(String(e))).finally(()=>setBusy(false));}}>{t('Read text file')}</button>}
 {writable&&!selected.thirdPartySource&&<><div className="adma-toolbar"><input aria-label={t('Name')} value={name} onChange={e=>setName(e.target.value)}/><button disabled={busy||!name.trim()||!can('update_'+selected.kind)} onClick={()=>void change('update_'+selected.kind,{id:selected.id,name:name.trim()})}>{t('Rename')}</button><button disabled={busy||!can('update_'+selected.kind)} onClick={()=>void change('update_'+selected.kind,{id:selected.id,is_public:!selected.is_public})}>{selected.is_public?t('Make private'):t('Make public')}</button></div>{confirmDelete?<div role="alert"><p>{t('Permanently delete this item? Folder contents are also deleted. This cannot be undone.')}</p><button disabled={busy} onClick={()=>void change('delete_'+selected.kind,{id:selected.id})}>{t('Confirm permanent deletion')}</button><button onClick={()=>setConfirmDelete(false)}>{t('Cancel')}</button></div>:<button disabled={busy||!can('delete_'+selected.kind)} onClick={()=>setConfirmDelete(true)}>{t('Delete permanently')}</button>}</>}
 </aside>}
 </div></section><p className="adma-hint">{t('Additional actions require their tools to be checked in Connectors. Use ADMA for binary uploads and downloads. Maps and native tools open here.')}</p></>}
 {busy&&<p role="status">{t('Loading…')}</p>}{error&&<p role="alert">{error}</p>}
 <section className="adma-data-card adma-third-party"><div className="adma-card-heading"><h3><Cloud size={19}/>{t('Third-party data')}</h3><span>{catalog.length} {t('items')}</span></div><div className="adma-card-body"><p className="adma-hint">{t('Public integration data published in ADMA’s third-party catalog. Open a folder to browse it here.')}</p>{catalog.map(item=><button className="adma-catalog-item" key={item.id} disabled={busy} onClick={()=>{setQuery('');if(item.kind==='folder')setTrail([item]);else void inspect(item);}}><Folder size={25}/><strong>{item.name}</strong><span>{item.thirdPartySource}</span><small>{t('Public')}</small></button>)}{!account&&<p>{t('Enable your ADMA connection in Connectors to browse your files.')}</p>}{account&&!catalog.length&&!catalogError&&<p>{t('No public third-party items found.')}</p>}{catalogError&&<p role="alert">{catalogError}</p>}</div></section>
 <div className="adma-destinations"><a href={mapHref}><Map size={26}/><div><strong>{t('Maps')}</strong><span>{t('Visualize geospatial data here')}</span></div><ExternalLink size={16}/></a><a href={toolHref('hub',{page:pageId,language:locale})}><Wrench size={26}/><div><strong>{t('Tools')}</strong><span>{t('Open native file and data tools')}</span></div><ExternalLink size={16}/></a></div></div></section>;
}
