// Parameter names mirror ADMA's Celery task signatures, not its legacy HTML forms.
export type ProcessingField={name:string;label:string;type:'file'|'folder'|'text'|'number'|'select';required?:boolean;options?:string[];value?:string|number};
const file=(name:string,label:string,required=true):ProcessingField=>({name,label,type:'file',required});
const folder=(name='output_dir_id'):ProcessingField=>({name,label:'Output folder',type:'folder'});
export const processingCatalog:{slug:string;name:string;description:string;fields:ProcessingField[]}[]=[
 {slug:'seeding-tool',name:'Seeding Tool',description:'Create seeding polygons, boundaries and statistics.',fields:[file('file_id','Seeding shapefile or GeoPackage'),folder()]},
 {slug:'shape-to-json',name:'Shape to JSON',description:'Convert a shapefile to GeoJSON for maps.',fields:[file('file_id','Input shapefile'),folder()]},
 {slug:'si-tool',name:'SI Tool',description:'Calculate crop Sufficiency Index using NDRE or satellite imagery.',fields:[{name:'workflow',label:'Workflow',type:'select',required:true,options:['standard_uav','standard_satellite','sbf_uav','sbf_satellite'],value:'standard_uav'},file('buffer_shp_id','Buffer sectors'),file('csv_file_id','Input CSV'),file('ndre_shp_id','NDRE shapefile',false),file('nir_tif_id','NIR raster',false),file('rededge_tif_id','Red-edge raster',false),file('indicator_shp_id','Indicator blocks',false),{name:'field_column',label:'Field column',type:'text'},{name:'si_column_name',label:'SI output column',type:'text',value:'SI'},folder('output_folder_id')]},
 {slug:'yield-summary',name:'Yield Summary',description:'Analyze yields, ANOVA and economic metrics.',fields:[file('treatment_file_id','Treatment sectors'),file('yield_file_id','Yield shapefile'),{name:'total_n_values',label:'Total nitrogen values (comma-separated)',type:'text',required:true},{name:'buffer_distance',label:'Buffer distance (m)',type:'number',value:-30},{name:'corn_price',label:'Corn price per bushel',type:'number',value:4.35},{name:'n_price',label:'Nitrogen price per lb',type:'number',value:0.5},folder()]},
 {slug:'valid-yield-extractor',name:'Valid Yield Extractor',description:'Filter harvest points to valid application areas.',fields:[file('plots_file_id','Treatment plots'),file('app_file_id','As-applied data'),file('harv_file_id','Harvest data'),{name:'crs',label:'Projected coordinate system',type:'text',value:'EPSG:26914'},{name:'rate_tolerance',label:'Rate tolerance',type:'number',value:0.1},...([['plot_id_col','Plot ID column'],['target_rate_col','Target rate column'],['applied_rate_col','Applied rate column'],['yield_col','Yield column']] as const).map(([name,label])=>({name,label,type:'text' as const})),folder('output_folder_id')]},
];
export const processingRunName=(slug:string)=>'run_'+slug.replaceAll('-','_');
