'use client';
import {useEffect,useState,useRef} from 'react';
import {processingCatalog,processingRunName,type ProcessingField} from './processing-catalog';
import {useUi} from '@/app/i18n/client';
import {toolHref} from '@/app/tools/sources';
import './processing.css';
type Account={id:string;name:string;allowed:string[]};type Item={id:string;name:string;is_public?:boolean};
export function ProcessingPanel({pageId,writable,initialTool=''}:{pageId:string;writable:boolean;initialTool?:string}){
 const {t,locale}=useUi(),[accounts,setAccounts]=useState<Account[]>([]),[account,setAccount]=useState(''),[slug,setSlug]=useState(processingCatalog.some(s=>s.slug===initialTool)?initialTool:processingCatalog[0].slug),[values,setValues]=useState<Record<string,string>>({}),[files,setFiles]=useState<Item[]>([]),[folders,setFolders]=useState<Item[]>([]),[busy,setBusy]=useState(false),[error,setError]=useState(''),[task,setTask]=useState(''),[result,setResult]=useState<any>(null);
 const operation=useRef<{key:string;id:string}|null>(null);
 const spec=processingCatalog.find(s=>s.slug===slug)!,connection=accounts.find(a=>a.id===account),can=(name:string)=>!!connection?.allowed.includes(name),endpoint='/api/pages/'+encodeURIComponent(pageId)+'/adma',historyKey='adma-processing:'+pageId+':'+account;
 async function call(tool:string,args:Record<string,unknown>,confirm=false){const r=await fetch(endpoint,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({connectorId:account,tool,args,confirm})}),d:any=await r.json();if(!r.ok)throw Error(d.error||'ADMA request failed.');if(d.result?.confirmationRequired)throw Error('Enable this tool in Connectors.');return d.result;}
 useEffect(()=>{let live=true;fetch(endpoint).then(r=>r.json()).then((d:any)=>{if(!live)return;if(d.error)throw Error(d.error);setAccounts(d.accounts||[]);setAccount(d.accounts?.[0]?.id||'');}).catch(e=>live&&setError(String(e)));return()=>{live=false;};},[endpoint]);
 useEffect(()=>{setValues(Object.fromEntries(spec.fields.filter(f=>f.value!==undefined).map(f=>[f.name,String(f.value)])));},[slug]);
 useEffect(()=>{setFiles([]);setFolders([]);setResult(null);setTask('');if(!account)return;try{setTask(localStorage.getItem(historyKey)||'');}catch{}let live=true;Promise.all([can('list_files')?call('list_files',{}):{files:[]},can('list_folders')?call('list_folders',{}):{folders:[]}]).then(([a,b])=>{if(live){setFiles((a.files||[]).filter((f:Item)=>f.is_public===false));setFolders((b.folders||[]).filter((f:Item)=>f.is_public===false));}}).catch(e=>live&&setError(String(e)));return()=>{live=false;};},[account]);
 async function run(){setBusy(true);setError('');setResult(null);try{const args=Object.fromEntries(spec.fields.filter(f=>values[f.name]?.trim()).map(f=>[f.name,f.type==='number'?Number(values[f.name]):values[f.name].trim()]));const key=JSON.stringify([account,slug,args]);if(operation.current?.key!==key)operation.current={key,id:crypto.randomUUID()};const r=await call(processingRunName(slug),{...args,operation_id:operation.current.id},true);setTask(r.task_id);setResult(r);try{localStorage.setItem(historyKey,r.task_id);}catch{}}catch(e){setError(String(e));}finally{setBusy(false);}}
 async function check(){setBusy(true);setError('');try{setResult(await call('processing_status',{task_id:task}));}catch(e){setError(String(e));}finally{setBusy(false);}}
 const outputFiles:Item[]=[];function collect(value:any,depth=0){if(!value||depth>8)return;if(Array.isArray(value)){value.forEach(v=>collect(v,depth+1));return;}if(typeof value==='object'){if(typeof value.id==='string'&&typeof value.name==='string'&&/^[a-f0-9-]{36}$/i.test(value.id)&&!outputFiles.some(f=>f.id===value.id))outputFiles.push(value);Object.values(value).forEach(v=>collect(v,depth+1));}}collect(result?.result);
 function field(f:ProcessingField){return <label key={f.name}>{t(f.label)}{f.required?' *':''}{f.type==='select'?<select required={f.required} value={values[f.name]||''} onChange={e=>setValues({...values,[f.name]:e.target.value})}>{f.options?.map(x=><option key={x}>{x}</option>)}</select>:<><input list={f.type==='file'?'processing-files':f.type==='folder'?'processing-folders':undefined} required={f.required} type={f.type==='number'?'number':'text'} step="any" value={values[f.name]||''} onChange={e=>setValues({...values,[f.name]:e.target.value})}/>{['file','folder'].includes(f.type)&&<small>{t('Choose an ID from the list or paste an ADMA resource ID.')}</small>}</>}</label>;}
 return <section className="adma-processing"><header><h2>{t('ADMA processing tools')}</h2><p>{t('Run agricultural data tools with your connected ADMA account.')}</p></header>{!account?<p>{t('Enable your ADMA connection in Connectors to browse your files.')}</p>:<><div className="processing-selectors"><label>{t('Account')}<select value={account} disabled={busy} onChange={e=>setAccount(e.target.value)}>{accounts.map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select></label><label>{t('Tool')}<select value={slug} disabled={busy} onChange={e=>setSlug(e.target.value)}>{processingCatalog.map(s=><option key={s.slug} value={s.slug}>{s.name}</option>)}</select></label></div><p>{t(spec.description)}</p>{!writable&&<p>{t("Fork this page to run tools in your private workspace.")}</p>}<p>{t('Processing writes output files. Use private input files and a private output folder. Copy shared datasets into your private ADMA workspace first.')}</p><datalist id="processing-files">{files.map(f=><option key={f.id} value={f.id}>{f.name}</option>)}</datalist><datalist id="processing-folders">{folders.map(f=><option key={f.id} value={f.id}>{f.name}</option>)}</datalist><form onSubmit={e=>{e.preventDefault();void run();}}><fieldset disabled={busy||!writable}><div className="processing-fields">{spec.fields.map(field)}</div><button disabled={!can(processingRunName(slug))||!!task&&!['SUCCESS','FAILURE','REVOKED'].includes(result?.status)}>{t('Run tool')}</button></fieldset></form>{!can(processingRunName(slug))&&<p>{t('Enable this tool in Connectors.')} <code>{processingRunName(slug)}</code></p>}<div className="processing-task"><label>{t('Task ID')}<input value={task} onChange={e=>{setTask(e.target.value);setResult(null);}}/></label><button disabled={busy||!task||!can('processing_status')} onClick={()=>void check()}>{t('Check status')}</button><button disabled={busy} onClick={()=>{operation.current=null;setTask('');setResult(null);try{localStorage.removeItem(historyKey);}catch{}}}>{t('New task')}</button></div>{result&&<><p role="status">{t('Status')}: {String(result.status||'SUBMITTED')}{result.result?.success===false?' · '+t('Task failed'):''}</p>{outputFiles.length>0&&<ul>{outputFiles.map(f=><li key={f.id}><strong>{f.name}</strong> <a href={toolHref(/\.(geojson|kml|gpx)$/i.test(f.name)?'map':'hub',{page:pageId,connector:account,file:f.id,name:f.name,language:locale})}>{t('Open with…')}</a> <a href={'https://adma.aisoup.net/file/'+encodeURIComponent(f.id)+'/'} target="_blank" rel="noreferrer">{t('Open in ADMA')}</a></li>)}</ul>}<details><summary>{t('Result details')}</summary><pre>{JSON.stringify(result,null,2)}</pre></details></>}</>}{error&&<p role="alert">{error}</p>}</section>;
}
