'use client';
import {geoFileHref} from '@/app/tools/sources';
import {RepositoryMap} from '@/app/geo/repository-map';
import {TransferActions} from '@/app/resources/actions';
import {useEffect,useRef,useState} from 'react';
import {Cloud,Folder,File,Grid2X2,List} from 'lucide-react';
import {useUi} from '@/app/i18n/client';
import {toolHref} from '@/app/tools/sources';
import {paginateItems,pageSizes} from './pagination';
type Item={id:string;name:string;kind:'file'|'folder';is_public:boolean;thirdPartySource?:string};
type Props={pageId:string;account:string;allowed:string[]};
export function ThirdPartyBrowser({pageId,account,allowed}:Props){
 const {t,locale}=useUi(),[catalog,setCatalog]=useState<Item[]>([]),[items,setItems]=useState<Item[]>([]),[trail,setTrail]=useState<Item[]>([]),[query,setQuery]=useState(''),[grid,setGrid]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[selected,setSelected]=useState<Item|null>(null),[mapItem,setMapItem]=useState<Item|null>(null),[detail,setDetail]=useState(''),[pageIndex,setPageIndex]=useState(0),[pageSize,setPageSize]=useState(50),[revision,setRevision]=useState(0);
 const sequence=useRef(0),inspection=useRef(0),folder=trail.at(-1),endpoint='/api/pages/'+encodeURIComponent(pageId)+'/adma';
 async function call(tool:string,args:Record<string,unknown>){const response=await fetch(endpoint,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({connectorId:account,tool,args})});const data=await response.json() as {error?:string;result?:any;items?:Item[]};if(!response.ok)throw Error(data.error||'ADMA request failed.');if(data.result?.confirmationRequired)throw Error('Enable this tool in Connectors.');return data.result;}
 useEffect(()=>{let active=true;if(!account||folder)return;setCatalog([]);setBusy(true);setError('');fetch(endpoint+'?catalog=third-party&connector='+encodeURIComponent(account)).then(async response=>{const data=await response.json() as {error?:string;result?:any;items?:Item[]};if(!response.ok)throw Error(data.error||'ADMA request failed.');if(active)setCatalog(data.items||[]);}).catch(e=>{if(active)setError(String(e));}).finally(()=>{if(active)setBusy(false);});return()=>{active=false;};},[account,endpoint,folder?.id,revision]);
 useEffect(()=>{const version=++sequence.current;setItems([]);setError('');if(!account||!folder)return;setBusy(true);Promise.all([allowed.includes('list_files')?call('list_files',{folder_id:folder.id}):Promise.resolve({files:[]}),allowed.includes('list_folders')?call('list_folders',{parent_id:folder.id}):Promise.resolve({folders:[]})]).then(([files,folders])=>{if(sequence.current===version)setItems([...(folders.folders||[]).map((item:Item)=>({...item,kind:'folder'})),...(files.files||[]).map((item:Item)=>({...item,kind:'file'}))]);}).catch(e=>{if(sequence.current===version)setError(String(e));}).finally(()=>{if(sequence.current===version)setBusy(false);});return()=>{++sequence.current;};},[account,endpoint,folder?.id,revision]);
 function navigate(next:Item[]){++inspection.current;setTrail(next);setQuery('');setPageIndex(0);setSelected(null);setDetail('');setBusy(false);}
 async function inspect(item:Item,read=false){const version=++inspection.current;setSelected(item);setDetail('');setError('');const tool=read?'read_text_file':item.kind==='folder'?'folder_info':'file_metadata';if(!allowed.includes(tool))return;try{const result=await call(tool,item.kind==='folder'?{folder_id:item.id}:{file_id:item.id});if(version===inspection.current)setDetail(typeof result==='string'?result:JSON.stringify(result,null,2));}catch(e){if(version===inspection.current)setError(String(e));}}
 const filtered=(folder?items:catalog).filter(item=>item.name.toLocaleLowerCase().includes(query.toLocaleLowerCase())).sort((a,b)=>a.kind===b.kind?a.name.localeCompare(b.name):a.kind==='folder'?-1:1),page=paginateItems(filtered,pageIndex,pageSize);
 const pager=(bottom=false)=><nav className="adma-pagination" aria-label={t('File list pagination')}><span role="status">{t('Showing {start}–{end} of {total} items',{start:page.start,end:page.end,total:page.total})}</span>{!bottom&&<label>{t('Items per page')}<select value={pageSize} onChange={e=>{setPageSize(Number(e.target.value));setPageIndex(0);}}>{pageSizes.map(size=><option key={size}>{size}</option>)}</select></label>}<div><button disabled={busy||!page.pageIndex} onClick={()=>setPageIndex(0)}>{t('First')}</button><button disabled={busy||!page.pageIndex} onClick={()=>setPageIndex(page.pageIndex-1)}>{t('Previous')}</button><label>{t('Page')}<select aria-label={t('Go to page')} value={page.pageIndex} disabled={busy||page.pageCount===1} onChange={e=>setPageIndex(Number(e.target.value))}>{Array.from({length:page.pageCount},(_,i)=><option key={i} value={i}>{i+1}</option>)}</select>{t('of {count}',{count:page.pageCount})}</label><button disabled={busy||page.pageIndex+1>=page.pageCount} onClick={()=>setPageIndex(page.pageIndex+1)}>{t('Next')}</button><button disabled={busy||page.pageIndex+1>=page.pageCount} onClick={()=>setPageIndex(page.pageCount-1)}>{t('Last')}</button></div></nav>;
 return <section className="adma-data-card adma-third-party" aria-label={t('Third-party data')}><div className="adma-card-heading"><h3><Cloud size={19}/>{t('Third-party data')}</h3><button aria-pressed={grid} onClick={()=>setGrid(!grid)}>{grid?<List size={17}/>:<Grid2X2 size={17}/>} {grid?t('List view'):t('Grid view')}</button></div><div className="adma-card-body">
 {!account?<p>{t('Enable your ADMA connection in Connectors to browse your files.')}</p>:<><nav className="adma-trail" aria-label={t('Folders')}><button onClick={()=>navigate([])}>{t('Third-party data')}</button>{trail.map((item,i)=><span key={item.id}> / <button onClick={()=>navigate(trail.slice(0,i+1))}>{item.name}</button></span>)}</nav><p className="adma-hint">{t(folder?'Showing this folder’s contents.':'Public integration data published in ADMA’s third-party catalog. Open a folder to browse it here.')}</p><div className="adma-toolbar"><input aria-label={t('Search files')} placeholder={t('Search files')} value={query} onChange={e=>{setQuery(e.target.value);setPageIndex(0);}}/><button disabled={busy} onClick={()=>setRevision(n=>n+1)}>{t('Refresh')}</button></div>
 {busy?<p role="status">{t('Loading…')}</p>:error?<p role="alert">{error}</p>:<>{pager()}<div className={'adma-items '+(grid?'adma-grid':'adma-list')}>{page.items.map(item=><article key={item.kind+item.id}><button className="adma-item" onClick={()=>item.kind==='folder'?navigate([...trail,item]):geoFileHref(pageId,{...item,space:'adma',connectorId:account},locale)?setMapItem(item):void inspect(item)}><span className={item.kind==='folder'?'adma-folder':'adma-file'}>{item.kind==='folder'?<Folder size={28}/>:<File size={26}/>}</span><strong>{item.name}</strong><small>{item.thirdPartySource||t(item.kind==='folder'?'Folder':'File')} · {t(item.is_public?'Public':'Private')}</small></button><button className="adma-details" onClick={()=>void inspect(item)}>{t('Details')}</button></article>)}</div>{page.pageCount>1&&pager(true)}{mapItem&&<RepositoryMap source={{page:pageId,file:mapItem.id,name:mapItem.name,space:'adma',connector:account,language:locale}} onClose={()=>setMapItem(null)}/>} {!page.total&&<p>{t(query?'Try another search.':'No items found.')}</p>}</>}
 {selected&&<aside className="adma-inspector"><button className="adma-close" onClick={()=>{++inspection.current;setSelected(null);}}>{t('Close')}</button><h3>{selected.name}</h3><TransferActions pageId={pageId} resource={{space:'adma',connectorId:account,id:selected.id,name:selected.name,kind:selected.kind}} canMove={false}/><a target="_blank" rel="noreferrer" href={'https://adma.aisoup.net/'+selected.kind+'/'+encodeURIComponent(selected.id)+'/'}>{t('Open in ADMA')} ↗</a>{selected.kind==='file'&&<><a className="adma-map-link" href={toolHref('hub',{page:pageId,connector:account,file:selected.id,name:selected.name,language:locale})}>{t('Open with…')}</a>{/\.(geojson|json|csv|tsv|kml|gpx)$/i.test(selected.name)&&<a className="adma-map-link" href={toolHref('map',{page:pageId,connector:account,file:selected.id,name:selected.name,language:locale})}>{t('View on map')}</a>}{allowed.includes('read_text_file')&&<button onClick={()=>void inspect(selected,true)}>{t('Read text file')}</button>}</>}{detail&&<pre>{detail}</pre>}</aside>}</>}
 </div></section>;
}
