'use client';
import {useEffect,useRef,useState} from 'react';
import {Map as MapIcon,Layers,Upload,Plus,Trash2,Maximize,Home,Table2,ArrowLeft} from 'lucide-react';
import {useUi} from '@/app/i18n/client';
import {loadArcGIS} from './arcgis';
import {parseGeoFile,publicLayerUrl,type GeoCollection} from './data';
import {readSourceFile,limitedBlob,toolHref,type SourceRef} from '@/app/tools/sources';
import './style.css';
type Row={id:string;title:string;visible:boolean;opacity:number;count?:number};
export function GeoViewer({source={}}:{source?:SourceRef}){
 const {t}=useUi(),host=useRef<HTMLDivElement>(null),runtime=useRef<any>(null),input=useRef<HTMLInputElement>(null),alive=useRef(true);
 const [activeSource,setActiveSource]=useState(source);
 const [ready,setReady]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[layers,setLayers]=useState<Row[]>([]),[url,setUrl]=useState(''),[service,setService]=useState('geojson'),[attributes,setAttributes]=useState<Record<string,unknown>|null>(null),[files,setFiles]=useState<{id:string;name:string}[]>([]);
 useEffect(()=>{let disposed=false;alive.current=true;let view:any;void (async()=>{try{const modules=await loadArcGIS(),[ArcGISMap,Basemap,MapView,OpenStreetMapLayer]=await modules(['@arcgis/core/Map.js','@arcgis/core/Basemap.js','@arcgis/core/views/MapView.js','@arcgis/core/layers/OpenStreetMapLayer.js']);if(disposed)return;const map=new ArcGISMap({basemap:new Basemap({baseLayers:[new OpenStreetMapLayer()],title:'OpenStreetMap'})});view=new MapView({container:host.current,map,center:[-96,38],zoom:3,popupEnabled:false});await view.when();if(disposed){view.destroy();return;}runtime.current={view,map,modules,blobs:new Map()};view.on('click',async(event:any)=>{const hit=await view.hitTest(event);if(disposed)return;const graphic=hit.results.find((r:any)=>r.type==='graphic'&&['geojson','feature'].includes(r.graphic.layer?.type))?.graphic;setAttributes(graphic?.attributes||null);});setReady(true);}catch(e){if(!disposed)setError(String(e));}})();return()=>{disposed=true;alive.current=false;runtime.current?.blobs.forEach((url:string)=>URL.revokeObjectURL(url));runtime.current=null;view?.destroy();};},[]);
 useEffect(()=>{if(!source.page)return;let active=true;fetch('/api/pages/'+encodeURIComponent(source.page)+'/files').then(async r=>{if(!r.ok)throw Error('Page files are inaccessible.');const d=await r.json() as {files:{id:string;name:string}[]};if(active)setFiles(d.files.filter(f=>/\.(geojson|json|csv|tsv|kml|gpx)$/i.test(f.name)));}).catch(e=>{if(active)setError(String(e));});return()=>{active=false;};},[source.page]);
 async function zoom(layer:any){const extent=layer.fullExtent;if(extent)await runtime.current?.view.goTo(extent.expand(1.25)).catch(()=>{});}
 async function addData(data:GeoCollection,title:string){const rt=runtime.current;if(!rt)throw Error('Map is still loading.');const [GeoJSONLayer]=await rt.modules(['@arcgis/core/layers/GeoJSONLayer.js']);
  const groups=new Map<string,typeof data.features>();for(const f of data.features){const family=f.geometry.type.replace('Multi','');if(!groups.has(family))groups.set(family,[]);groups.get(family)!.push(f);}
  const created:any[]=[];try{for(const [family,features] of groups){const blob=URL.createObjectURL(new Blob([JSON.stringify({type:'FeatureCollection',features})],{type:'application/geo+json'}));const layer=new GeoJSONLayer({url:blob,title:title+(groups.size>1?' · '+family:''),outFields:['*'],renderer:{type:'simple',symbol:family==='Point'?{type:'simple-marker',style:'circle',color:'#df5548',size:11,outline:{color:'#ffffff',width:1.5}}:family==='LineString'?{type:'simple-line',color:'#d34b40',width:2.5}:{type:'simple-fill',color:[32,137,143,0.3],outline:{color:'#167d84',width:2}}},popupEnabled:false});rt.blobs.set(layer.id,blob);created.push(layer);await layer.load();if(!alive.current){throw Error('Viewer closed.');}rt.map.add(layer);setLayers(old=>[...old,{id:layer.id,title:layer.title,visible:true,opacity:1,count:features.length}]);}await zoom(created[0]);}catch(e){for(const layer of created){rt.map.remove(layer);URL.revokeObjectURL(rt.blobs.get(layer.id));rt.blobs.delete(layer.id);layer.destroy();}setLayers(old=>old.filter(r=>!created.some(x=>x.id===r.id)));throw e;}}
 async function openFile(file:File,ref:SourceRef={page:source.page,language:source.language}){if(file.size>10*1024*1024)throw Error('Choose a file up to 10 MB.');await addData(parseGeoFile(file.name,await file.text()),file.name);setActiveSource(ref);}
 async function task(fn:()=>Promise<void>){setBusy(true);setError('');try{await fn();}catch(e){if(alive.current)setError(String(e));}finally{if(alive.current)setBusy(false);}}
 const initial=useRef('');useEffect(()=>{const key=JSON.stringify(source);if(ready&&source.file&&initial.current!==key){initial.current=key;void task(async()=>openFile(await readSourceFile(source),source));}},[ready,source.page,source.file,source.connector]);
 async function addUrl(){const safe=publicLayerUrl(url);if(service==='geojson'){const blob=await limitedBlob(await fetch(safe,{credentials:'omit',referrerPolicy:'no-referrer',signal:AbortSignal.timeout(30000)}));await addData(parseGeoFile(new URL(safe).pathname,await blob.text()),new URL(safe).pathname.split('/').at(-1)||'GeoJSON');return;}
  const modules:Record<string,string>={feature:'FeatureLayer',map:'MapImageLayer',wms:'WMSLayer',wmts:'WMTSLayer'};const [Layer]=await runtime.current.modules(['@arcgis/core/layers/'+modules[service]+'.js']);const layer=new Layer({url:safe,popupEnabled:false});try{await layer.load();runtime.current.map.add(layer);setLayers(old=>[...old,{id:layer.id,title:layer.title||new URL(safe).hostname,visible:true,opacity:1}]);await zoom(layer);}catch(e){layer.destroy();throw e;}}
 function update(id:string,patch:Partial<Row>){const layer=runtime.current?.map.findLayerById(id);if(layer)Object.assign(layer,patch);setLayers(old=>old.map(r=>r.id===id?{...r,...patch}:r));}
 function remove(id:string){const rt=runtime.current,layer=rt?.map.findLayerById(id);if(layer){rt.map.remove(layer);layer.destroy();const blob=rt.blobs.get(id);if(blob)URL.revokeObjectURL(blob);rt.blobs.delete(id);}setLayers(old=>old.filter(r=>r.id!==id));setAttributes(null);}
 return <section className="geo-app"><header className="geo-header"><MapIcon/><div><h1>{t('Geo Viewer')}</h1><span>{t('Explore your data on a map')}</span></div><a href={source.page?'/?page='+encodeURIComponent(source.page):'/'}><ArrowLeft size={16}/>{t('Back to page')}</a><a href={toolHref('table',activeSource)}><Table2 size={17}/>{t('Table Studio')}</a><a href={toolHref('hub',activeSource)}>{t('All apps')}</a></header><div className="geo-layout"><aside className="geo-sidebar"><h2><Layers size={18}/>{t('Layers')}</h2><button className="geo-primary" disabled={!ready||busy} onClick={()=>input.current?.click()}><Upload size={17}/>{t('Open geographic file')}</button><input ref={input} hidden type="file" accept=".geojson,.json,.csv,.tsv,.kml,.gpx" onChange={e=>{const file=e.target.files?.[0];e.target.value='';if(file)void task(()=>openFile(file));}}/><p>{t('GeoJSON, CSV/TSV with coordinates, KML and GPX. WGS84, up to 10 MB.')}</p>
 {files.length>0&&<label>{t('Page files')}<select disabled={!ready||busy} value="" onChange={e=>{const file=e.target.value;if(file)void task(async()=>openFile(await readSourceFile({...source,file,connector:undefined}),{...source,file,connector:undefined}));}}><option value="">{t('Choose a file')}</option>{files.map(f=><option key={f.id} value={f.id}>{f.name}</option>)}</select></label>}
 <details><summary>{t('Add public data URL')}</summary><form onSubmit={e=>{e.preventDefault();void task(addUrl);}}><label>{t('Layer type')}<select value={service} onChange={e=>setService(e.target.value)}><option value="geojson">GeoJSON / CSV / KML / GPX</option><option value="feature">ArcGIS FeatureServer</option><option value="map">ArcGIS MapServer</option><option value="wms">WMS</option><option value="wmts">WMTS</option></select></label><input required type="url" aria-label={t('Data URL')} placeholder="https://…" value={url} onChange={e=>setUrl(e.target.value)}/><button disabled={!ready||busy}><Plus size={16}/>{t('Add layer')}</button></form></details>
 <div className="geo-layers">{layers.map(row=><div className="geo-layer" key={row.id}><label><input type="checkbox" checked={row.visible} onChange={e=>update(row.id,{visible:e.target.checked})}/><strong>{row.title}</strong></label>{row.count!==undefined&&<small>{row.count} {t('features')}</small>}<div><button aria-label={t('Zoom to layer')} onClick={()=>void zoom(runtime.current.map.findLayerById(row.id))}><Maximize size={15}/></button><input aria-label={t('Layer opacity')} type="range" min="0" max="1" step="0.05" value={row.opacity} onChange={e=>update(row.id,{opacity:Number(e.target.value)} )}/><button aria-label={t('Remove layer')} onClick={()=>remove(row.id)}><Trash2 size={15}/></button></div></div>)}</div>
 {!layers.length&&<p>{t('Add a file or service to start exploring.')}</p>}<button disabled={!ready} onClick={()=>void runtime.current.view.goTo({center:[-96,38],zoom:3}).catch(()=>{})}><Home size={16}/>{t('Reset view')}</button><p className="geo-note">{t('Local files are processed in this tab and are not uploaded. Layers are not saved when you leave.')}</p></aside><div className="geo-stage"><div ref={host} className="geo-canvas" aria-label={t('Interactive map')}/>{(!ready||busy)&&!error&&<div className="geo-status" role="status">{t('Loading…')}</div>}{error&&<div className="geo-status geo-error" role="alert">{error}</div>}{attributes&&<aside className="geo-attributes"><button onClick={()=>setAttributes(null)}>{t('Close')}</button><h3>{t('Feature attributes')}</h3><dl>{Object.entries(attributes).map(([k,v])=><div key={k}><dt>{k}</dt><dd>{String(v??'')}</dd></div>)}</dl></aside>}</div></div></section>;
}
