'use client';
import {useUi} from '@/app/i18n/client';
import {useMemo,useState} from 'react';
import {Folder,File,ChevronRight,Grid2X2,List,ArrowUpRight,Search} from 'lucide-react';
export type FileEntry={id:string;name:string;kind:'folder'|'file';parents?:string[];url?:string;modifiedTime?:string};
export function FileBrowser({items,title,language='en',onFolder,initialQuery=''}:{initialQuery?:string;items:FileEntry[];title:string;language?:string;onFolder?:(id:string)=>void}){
 const {t,locale}=useUi();

 const [trail,setTrail]=useState<FileEntry[]>([]),[query,setQuery]=useState(initialQuery),[grid,setGrid]=useState(false),[reverse,setReverse]=useState(false);const zh=language.startsWith('zh');
 const current=trail.at(-1)?.id;
 const visible=useMemo(()=>{const ids=new Set(items.map(i=>i.id));return items.filter(i=>query?i.name.toLowerCase().includes(query.toLowerCase()):current?(onFolder||i.parents?.includes(current)):!i.parents?.some(p=>ids.has(p))).sort((a,b)=>Number(b.kind==='folder')-Number(a.kind==='folder')||(reverse?-1:1)*a.name.localeCompare(b.name));},[items,current,query,reverse]);
 const safeUrl=(url?:string)=>url&&(url.startsWith('/api/components/')||/^https:\/\/(?:drive\.google\.com|docs\.google\.com)\//.test(url))?url:undefined;
 return <section className="file-browser"><aside><Folder size={21}/><strong>{title}</strong><button onClick={()=>{setTrail([]);setQuery('');onFolder?.('root');}}>{t("All files")}</button><span>{items.length} {t("items loaded")}</span></aside><div className="file-browser-main"><nav aria-label={t("Breadcrumbs")}><button onClick={()=>{setTrail([]);onFolder?.('root');}}>{title}</button>{trail.map((f,i)=><span key={f.id}><ChevronRight size={15}/><button onClick={()=>{setTrail(trail.slice(0,i+1));onFolder?.(f.id);}}>{f.name}</button></span>)}</nav><div className="file-browser-tools"><label><Search size={16}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder={t("Search files")} aria-label={t("Search files")}/></label><button onClick={()=>setReverse(!reverse)}>{t("Name")} {reverse?'↓':'↑'}</button><button aria-label={t("List view")} aria-pressed={!grid} onClick={()=>setGrid(false)}><List size={18}/></button><button aria-label={t("Grid view")} aria-pressed={grid} onClick={()=>setGrid(true)}><Grid2X2 size={18}/></button></div><div className={grid?'file-entries file-grid':'file-entries'}>{visible.map(f=><div key={f.id} className="file-entry">{f.kind==='folder'?<Folder size={23}/>:<File size={23}/>}<button disabled={f.kind!=='folder'} onClick={()=>{setTrail(query?[f]:[...trail,f]);setQuery('');onFolder?.(f.id);}}>{f.name}</button>{f.modifiedTime&&<small>{new Date(f.modifiedTime).toLocaleDateString(locale)}</small>}{safeUrl(f.url)&&<a href={safeUrl(f.url)} target="_blank" rel="noopener noreferrer" aria-label={(t("Open "))+f.name}><ArrowUpRight size={18}/></a>}</div>)}</div>{!visible.length&&<p className="file-empty">{t("No loaded items here.")}</p>}</div></section>;
}
